Repository truenas/webui, pull requests merged in 2018-05, with the labels that each got.

#774 Reviewed service -> ftp tooltips:
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
Labels: Tooltips, review

#773 Reviewed the domain controller and dynamic dns tooltips:
  src/app/pages/services/components/service-dc/service-dc.component.ts
  src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
Labels: Tooltips, review

#709 Cloudcreds tooltip review
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: Tooltips, review

#718 Review Storage tooltips:
  src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
  src/app/pages/storage/disks/disk-wipe/disk-wipe.component.ts
  src/app/pages/storage/disks/disks-list/disks-list.component.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
  src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
  src/app/pages/storage/volumes/volume-delete/volume-delete.component.ts
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
  src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
  src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
  src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
  src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-add/zvol-add.component.ts
  src/app/pages/storage/volumes/zvol/zvol-edit/zvol-edit.component.ts
Labels: Tooltips, review

#777 Add ipv6 configure and options to network interfaces list
  src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
Labels: review

#783 Fix 33435
  src/app/pages/storage/storage.module.ts
  src/app/pages/storage/storage.routing.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-add/index.ts
  src/app/pages/storage/volumes/zvol/zvol-add/zvol-add.component.ts
  src/app/pages/storage/volumes/zvol/zvol-edit/index.ts
  src/app/pages/storage/volumes/zvol/zvol-edit/zvol-edit.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/index.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
Labels: review

#781 Update message that appears when switching from Angular UI to Legacy UI:
  src/app/components/common/topbar/topbar.component.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: review

#782 Made minor text fixes.
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: review

#780 Update link to encryption section of the guide for encryption tooltip.
  src/app/pages/storage/volumes/manager/manager.component.ts
Labels: review

#784 catching up with user API change.
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: review

#790 That was so uncool of you @types/d3-dsv, why you gotta go break the build?
  package.json
Labels: review

#786 Rewrite VMs/Device/Add * tooltips, also VMs/Device/Edit tooltips:
  src/app/pages/vm/devices/device-add/device-add.component.ts
  src/app/pages/vm/devices/device-cdrom-add/device-cdrom-add.component.ts
  src/app/pages/vm/devices/device-disk-add/device-disk-add.component.ts
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
  src/app/pages/vm/devices/device-nic-add/device-nic-add.component.ts
  src/app/pages/vm/devices/device-rawfile-add/device-rawfile-add.component.ts
  src/app/pages/vm/devices/device-vnc-add/device-vnc-add.component.ts
Labels: review

#789 Fix 32970
  src/app/pages/sharing/afp/afp-form/afp-form.component.ts
Labels: review

#793 Fix 33504
  src/app/app.module.ts
  src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity.module.ts
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
  src/app/pages/storage/storage.routing.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.css
  src/app/pages/storage/volumes/volume-status/volume-status.component.html
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/services/dialog.service.ts
  src/app/services/index.ts
Labels: review

#792 added "ATA Security User" and "SED password".
  src/app/pages/system/advanced/advanced.component.ts
Labels: review

#795 hiding VNC options for Dockers as it's not supported.
  src/app/pages/vm/vm-cards/vm-cards.component.html
Labels: review

#796 Fix 28607
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
Labels: review

#797 Fix 33393
  src/app/pages/storage/volumes/volume-status/volume-status.component.html
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#791 Fix/pool screen 33345
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#799 Fix/defaults show before data 33858
  src/app/pages/common/entity/entity-form/entity-form.component.html
  src/app/pages/common/entity/entity-form/entity-form.component.ts
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/common/entity/entity-task/entity-task.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#802 Fix/sort pool list 33801
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/services/storage.service.ts
Labels: review

#776 Jail Edit tooltip review
  src/app/pages/jails/jail-edit/jail-edit.component.ts
Labels: Tooltips, review

#745 Update the Jail Wizard tooltips
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: Tooltips, review

#803 Fix 34104
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
  src/app/pages/jails/jail-list/jail-list.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: review

#775 Update Jail Add tooltips formatting, grammar, and accuracy
  src/app/pages/jails/jail-add/jail-add.component.ts
Labels: Tooltips, review

#807 Update field from Volume -> Pool
  src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
Labels: review

#808 - Unbreak FreeNAS HEAD Master build, trueos have a newer npm version …
  ports/freenas/npm/Makefile
  ports/freenas/npm/distinfo
  ports/freenas/npm/files/extra-patch-bug-178881
  ports/freenas/npm/pkg-descr
  ports/freenas/npm/pkg-plist
Labels: review

#810 fix Incorrect percentage value reported when fetching RancherOS.
  src/app/pages/vm/vm-cards/vm-cards.component.ts
Labels: polishing, review

#814 Fix compile error
  src/app/app.module.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Labels: review

#813 Fix small text formatting error in Shell tooltip.
  src/app/pages/shell/shell.component.ts
Labels: Tooltips, review

#812 Clarify some prompts in the volume manager
  src/app/pages/storage/volumes/manager/manager.component.ts
Labels: polishing, review

#816 Fix 34192
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: review

#817 fix for 32424 and also fixed a traceback in console if there were no …
  src/app/pages/system/update/update.component.ts
Labels: review

#815 Fix 34107
  src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
  src/app/pages/vm/vm-cards/vm-cards.component.html
  src/app/pages/vm/vm-cards/vm-cards.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: review

#820 Fix 32424
  src/app/pages/system/update/update.component.html
  src/app/pages/system/update/update.component.ts
Labels: review

#819 fixed disk remove
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Labels: review

#818 Remove comments, restore a missing var
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/vdev/vdev.component.html
Labels: review

#821 Fix 33414
  src/app/pages/common/entity/entity-form/entity-form.component.ts
Labels: review

#811 Clean up wording and add IDs for wizard buttons
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
  src/app/pages/jails/jail-add/jail-add.component.ts
  src/app/pages/jails/jail-edit/jail-edit.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: polishing, review

#717 Reword "system is not yet available" to "Attempting to connect"
  src/app/views/sessions/signin/signin.component.html
Labels: polishing, review

#809 Update unclear field name and tooltip:
  src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: Tooltips, polishing, review

#800 Clarify and consistivize tooltips and labels
  src/app/pages/jails/jail-add/jail-add.component.ts
  src/app/pages/jails/jail-list/jail-list.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
  src/app/pages/jails/jails.routing.ts
  src/app/services/navigation/navigation.service.ts
Labels: Tooltips, polishing, review

#822 Make snapshot clone work for the root dataset like it does in the old UI
  src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
Labels: review

#785 Fix tour show logic in Account/Users, remove "you just closed User To…
  src/app/app.component.ts
  src/app/components/common/topbar/topbar.component.ts
  src/app/components/common/topbar/topbar.template.html
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts
  src/app/pages/preferences/page/forms/general-preferences-form.component.ts
  src/app/pages/preferences/page/preferences.component.ts
  src/app/pages/preferences/page/preferences.types.ts
  src/app/pages/storage/disks/disks-list/disks-list.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/services/index.ts
  src/app/services/tour.service.ts
Labels: polishing, review

#824 Fix 33948
  src/app/pages/common/entity/entity-form/entity-form.component.ts
Labels: review

#830 Add remaining translation markers throughout the UI
  src/app/core/components/corecomponents.module.ts
  src/app/core/components/widgets/widget/widget.component.html
  src/app/core/components/widgets/widget/widget.component.ts
  src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.html
  src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.ts
  src/app/core/components/widgets/widgetloadhistory/widgetloadhistory.component.html
  src/app/core/components/widgets/widgetloadhistory/widgetloadhistory.component.ts
  src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.html
  src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.ts
  src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.html
  src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
  src/app/core/components/widgets/widgetnote/widgetnote.component.html
  src/app/core/components/widgets/widgetnote/widgetnote.component.ts
  src/app/core/components/widgets/widgetnotescollection/widgetnotescollection.component.ts
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
  src/app/core/components/widgets/widgetstorage/widgetstorage.component.html
  src/app/core/components/widgets/widgetstorage/widgetstorage.component.ts
  src/app/core/components/widgets/widgetstoragecollection/widgetstoragecollection.component.ts
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
  src/app/pages/directoryservice/idmap/idmap.component.ts
  src/app/pages/directoryservice/kerberoskeytabs/kerberoskeytabs-form/kerberoskeytabs-form.component.ts
  src/app/pages/directoryservice/kerberosrealms/kerberosrealms-form/kerberosrealms-form.component.ts
  src/app/pages/directoryservice/kerberosrealms/kerberosrealms-list/kerberosrealms-list.component.ts
  src/app/pages/directoryservice/kerberossettings/kerberossettings.component.ts
  src/app/pages/directoryservice/ldap/ldap.component.ts
  src/app/pages/directoryservice/nis/nis.component.ts
  src/app/pages/reportsdashboard/reportsdashboard.component.ts
  src/app/pages/reportsdashboard/reportsdashboard.html
  src/app/pages/reportsdashboard/reportsdashboard.module.ts
Labels: review

#832 Fix 34393
  src/app/pages/jails/jail-list/jail-list.component.html
  src/app/pages/plugins/plugins-available/plugins-available-list.component.css
  src/app/pages/plugins/plugins-available/plugins-available-list.component.html
Labels: review

#829 Begin making tooltips consistent
  src/app/pages/jails/jail-add/jail-add.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: Tooltips, polishing, review

#825 Fix 34279
  src/app/pages/common/confirm-dialog/confirm-dialog.component.html
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
Labels: review

#827 FormScheduler Ticket 33327
  package.json
  src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.directive.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/entity.module.ts
  src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts
  src/assets/styles/themes/ix-blue.scss
  src/styles.css
Labels: review
