Repository truenas/webui, pull requests merged in 2018-06, with the labels that each got.

#826 Add compressratio data to pool list
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#806 Update text in form from Volume -> Pool.
  src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
Labels: polishing, review

#831 Fixed breakage with device-edit form
  src/app/pages/vm/devices/device-edit/device-edit.component.html
  src/app/pages/vm/devices/device-edit/device-edit.component.scss
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: review

#834 Fix 32247
  src/app/pages/system/update/update.component.html
  src/app/pages/system/update/update.component.ts
  src/app/services/dialog.service.ts
Labels: review

#835 Fixed a few tooltip errors.
  src/app/pages/services/components/service-afp/service-afp.component.ts
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
Labels: review

#838 Remove fab button from boot environments by moving the extra actions into buttons
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
Labels: review

#845 minor edits in script
  tests/logout.py
  tests/net_conf.py
  tests/sys_update.py
Labels: review

#844 added required to AD form, Account Name and Password
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
Labels: review

#843 Link to dash 34318
  src/app/components/common/layouts/admin-layout/admin-layout.component.css
  src/app/components/common/layouts/admin-layout/admin-layout.template.html
Labels: review

#842 Reposition oddly placed tooltip
  src/assets/styles/themes/ix-blue.scss
Labels: review

#839 Added build date to WidgetSysInfoComponent
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Labels: review

#841 Break power-related settings out into a new menu
  src/app/components/common/topbar/topbar.template.html
Labels: review

#840 style buttons and selector on update page
  src/app/pages/system/update/update.component.css
  src/app/pages/system/update/update.component.html
Labels: review

#823 Improve prompts and tooltips
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: Tooltips, polishing, review

#847 move Browse button on top of the path as needed for #34372
  src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
Labels: review

#850 fix edit mode for devices.
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
Labels: review

#851 Fix 34513
  src/app/pages/vm/devices/device-add/device-add.component.css
  src/app/pages/vm/devices/device-add/device-add.component.html
  src/app/pages/vm/devices/device-add/device-add.component.ts
  src/app/pages/vm/devices/device-add/index.ts
  src/app/pages/vm/devices/device-add2/device-add.component.html
  src/app/pages/vm/devices/device-add2/device-add.component.ts
  src/app/pages/vm/devices/device-add2/index.ts
  src/app/pages/vm/devices/device-cdrom-add/device-cdrom-add.component.ts
  src/app/pages/vm/devices/device-cdrom-add/index.ts
  src/app/pages/vm/devices/device-disk-add/device-disk-add.component.ts
  src/app/pages/vm/devices/device-disk-add/index.ts
  src/app/pages/vm/devices/device-list/device-list.component.ts
  src/app/pages/vm/devices/device-nic-add/device-nic-add.component.ts
  src/app/pages/vm/devices/device-nic-add/index.ts
  src/app/pages/vm/devices/device-rawfile-add/device-rawfile-add.component.ts
  src/app/pages/vm/devices/device-rawfile-add/index.ts
  src/app/pages/vm/devices/device-vnc-add/device-vnc-add.component.ts
  src/app/pages/vm/devices/device-vnc-add/index.ts
  src/app/pages/vm/vm.module.ts
  src/app/pages/vm/vm.routing.ts
Labels: review

#852 Fix/ellipsis on pool create page 34579
  src/app/pages/storage/volumes/manager/manager.component.css
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/vdev/vdev.component.html
Labels: review

#853 Move replication actions from fab icon into table header
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts
Labels: review

#848 Fix/pool unlock dialog 31707
  src/app/pages/storage/storage.module.ts
  src/app/pages/storage/storage.routing.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/volumeunlock-form/index.ts
  src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts
Labels: review

#858 fixed summary and validation; add T marker
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: review

#860 Fix 34315
  src/app/pages/account/account.routing.ts
  src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.css
  src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.html
  src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.ts
  src/app/pages/common/entity/entity.module.ts
  src/app/pages/directoryservice/directoryservice.routing.ts
  src/app/pages/network/network.routing.ts
  src/app/pages/plugins/plugins.routing.ts
  src/app/pages/sharing/sharing.routing.ts
  src/app/pages/storage/storage.routing.ts
  src/app/pages/system/system.routing.ts
  src/app/pages/task-calendar/task-calendar.routing.ts
Labels: review

#861 Fix 34666
  src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.ts
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
Labels: review

#862 Hide certificate and https redirect fields depending on the protocol setting in System General and move certificate to the top.
  src/app/pages/system/general/general.component.ts
Labels: review

#856 Fix/vert align table headers 34585
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/storage/volumes/manager/manager.component.css
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/vdev/vdev.component.css
  src/app/pages/storage/volumes/manager/vdev/vdev.component.html
  src/app/pages/vm/vm-cards/vm-table.component.html
  src/assets/styles/themes/ix-blue.scss
Labels: review

#859 Add legacy ui option and copyright back but only show when the websocket is available.
  src/app/views/sessions/signin/signin.component.html
Labels: review

#863 Jails vnet fix
  src/app/pages/jails/jail-add/jail-add.component.ts
  src/app/pages/jails/jail-edit/jail-edit.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: review

#864 Fix/entity job dialog 34627
  src/app/pages/common/entity/entity-job/entity-job.component.html
  src/app/pages/common/entity/entity-job/entity-job.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: review

#866 FIX 34690
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: review

#868 Fix 32547
  src/app/pages/system/general/config-save/config-save.component.ts
  src/app/services/system-general.service.ts
Labels: review

#865 Fix 27133
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/storage/disks/disks-list/disks-list.component.ts
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#867 Fix 33423
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/utils.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#869 Replication bandwidth uses kilobits not kilobytes
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Labels: review

#857 corrected storage terminology, specific location for HDD can be speci…
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: review

#855 Fix backblaze field names
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: review

#876 Webui tests scripts: function file added
  tests/acc_delete.py
  tests/acc_edit.py
  tests/acc_group.py
  tests/acc_user.py
  tests/function.py
  tests/funtion_list.py
  tests/login.py
  tests/logout.py
  tests/net_conf.py
  tests/runtest.py
  tests/serv_afp.py
  tests/serv_dc.py
  tests/serv_dns.py
  tests/serv_ftp.py
  tests/serv_iscsi.py
  tests/serv_lldp.py
  tests/serv_smb.py
  tests/serv_ssh.py
  tests/serv_webdav.py
  tests/sys_advanced.py
  tests/sys_email.py
  tests/sys_update.py
  tests/theme.py
Labels: review

#882 Attempt to fix the build with a older npm version
  ports/freenas/freenas-webui/Makefile
Labels: review

#883 fix categorie
  ports/freenas/npm/Makefile
Labels: review

#884 added VALID_CATEGORIES
  ports/freenas/npm/Makefile
Labels: review

#886 - Added also a older node version.
  ports/freenas/node/Makefile
  ports/freenas/node/distinfo
  ports/freenas/node/files/patch-deps_v8_src_arm_cpu-arm.cc
  ports/freenas/node/files/patch-deps_v8_src_base_cpu.cc
  ports/freenas/node/files/patch-deps_v8_src_base_platform_platform-freebsd.cc
  ports/freenas/node/files/patch-deps_v8_src_libsampler_sampler.cc
  ports/freenas/node/pkg-descr
  ports/freenas/node/pkg-message
  ports/freenas/node/pkg-plist
  ports/freenas/npm/Makefile
Labels: review

#888 - Fix duplicte origin
  ports/freenas/node9/Makefile
  ports/freenas/node9/distinfo
  ports/freenas/node9/files/patch-deps_v8_src_arm_cpu-arm.cc
  ports/freenas/node9/files/patch-deps_v8_src_base_cpu.cc
  ports/freenas/node9/files/patch-deps_v8_src_base_platform_platform-freebsd.cc
  ports/freenas/node9/files/patch-deps_v8_src_libsampler_sampler.cc
  ports/freenas/node9/pkg-descr
  ports/freenas/node9/pkg-message
  ports/freenas/node9/pkg-plist
  ports/freenas/npm/Makefile
Labels: review

#889 - Fix run-dependency
  ports/freenas/npm/Makefile
Labels: review

#890 More downgrads
  ports/freenas/node9/Makefile
  ports/freenas/node9/distinfo
  ports/freenas/node9/files/patch-deps_v8_src_arm_cpu-arm.cc
  ports/freenas/node9/files/patch-deps_v8_src_base_atomicops__internals__arm__gcc.h
  ports/freenas/node9/files/patch-deps_v8_src_base_cpu.cc
  ports/freenas/node9/files/patch-deps_v8_src_base_platform_platform-freebsd.cc
  ports/freenas/node9/files/patch-deps_v8_src_libsampler_sampler.cc
  ports/freenas/node9/files/patch-deps_v8_src_log-utils.h
  ports/freenas/node9/files/patch-deps_v8_src_profiler_sampler.cc
  ports/freenas/node9/pkg-descr
  ports/freenas/node9/pkg-message
  ports/freenas/node9/pkg-plist
  ports/freenas/npm/Makefile
  ports/freenas/npm/distinfo
  ports/freenas/npm/pkg-plist
Labels: review

#891 - Fix pkg origin
  ports/freenas/freenas-webui/Makefile
  ports/freenas/npm5/Makefile
  ports/freenas/npm5/distinfo
  ports/freenas/npm5/files/extra-patch-bug-178881
  ports/freenas/npm5/pkg-descr
  ports/freenas/npm5/pkg-plist
Labels: review

#895 Update Makefile
  ports/freenas/freenas-webui/Makefile
Labels: review

#899 removed entity-delete entirely.
  src/app/pages/common/entity/entity-delete/entity-delete.component.css
  src/app/pages/common/entity/entity-delete/entity-delete.component.html
  src/app/pages/common/entity/entity-delete/entity-delete.component.ts
  src/app/pages/common/entity/entity-delete/index.ts
  src/app/pages/common/entity/entity.module.ts
  src/app/pages/vm/devices/device-delete/device-delete.component.ts
  src/app/pages/vm/devices/device-delete/index.ts
  src/app/pages/vm/vm-delete/index.ts
  src/app/pages/vm/vm-delete/vm-delete.component.ts
  src/app/pages/vm/vm.module.ts
  src/app/pages/vm/vm.routing.ts
Labels: review

#892 FIX 34681
  src/app/pages/shell/shell.component.ts
Labels: review

#875 Fix issues in TFTP with non-usable exec permissions and no users in dropdown
  src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/services/components/service-tftp/service-tftp.component.ts
  src/app/pages/services/services.module.ts
Labels: review

#902 - Attempt to fix build on truenas env
  ports/freenas/node9/Makefile
Labels: review

#901 Fix tooltip for the IPv6 Default Gateway
  src/app/pages/network/configuration/configuration.component.ts
Labels: review

#880 Smart tooltip
  src/app/pages/services/components/service-smart/service-smart.component.ts
Labels: review

#871 Update component text a little.
  src/app/pages/system/update/update.component.ts
Labels: review

#881 Update Cloud Sync tooltips
  src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: review

#872 Be clear about what the boot pool status button does
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
Labels: review

#903 Change text overflow setting to remove scrollbar
  src/assets/styles/themes/ix-blue.scss
Labels: review

#893 Fix 34879
  src/app/pages/common/entity/entity-form/entity-form.component.ts
  src/app/pages/sharing/afp/afp-form/afp-form.component.ts
  src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: review

#887 Feature/modify entity table footer 33579
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/common/entity/entity-table/entity-table.component.scss
Labels: review

#873 Fix alignment on About Dialog
  src/app/components/common/dialog/about/about-dialog.component.css
  src/app/components/common/dialog/about/about-dialog.component.html
Labels: review

#904 Fix 34789
  src/app/pages/jails/jail-add/jail-add.component.ts
Labels: review

#896 Delete timeout
  src/app/app.module.ts
  src/app/components/common/topbar/topbar.component.ts
Labels: review

#894 Fix edit mode for certificates/csr and fix the tooltips
  src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
Labels: review

#898 Fix issue where datatable rows get stuck at original window size
  src/assets/styles/themes/ix-blue.scss
Labels: review

#885 Dismiss snackbar upon successful login
  src/app/views/sessions/signin/signin.component.ts
Labels: review

#874 Fix 34711
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/system/general/config-save/config-save.component.html
  src/app/pages/system/general/config-save/config-save.component.ts
  src/app/pages/system/general/config-save/index.ts
  src/app/pages/system/general/general.component.ts
  src/app/pages/system/system.module.ts
  src/app/pages/system/system.routing.ts
Labels: review

#877 Add cancel buttons to entity wizard
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.css
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
Labels: review

#905 Do not log user out after password change
  src/app/pages/account/users/change-password/change-password.component.ts
Labels: review

#908 Fix issues with unlock and detatch pool
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: review

#906 Fix 34900
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
  src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
  src/app/pages/common/entity/entity-form/entity-form.component.ts
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/system/support/support.component.ts
Labels: review

#907 Add Periodic Snapshot Task setting to SMB Add
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: review

#900 Clarify "select pool or dataset" field.
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: review

#909 Improve text in the Docker VM wizard
  src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: review

#933 How did aliases ever work???
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: review

#919 Add dummy input fields to prevent the browser from auto-filling passwords
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
Labels: review
