Repository truenas/webui, pull requests merged in 2020-02, with the labels that each got.

#3592 NAS-104874 / 11.3 / Nas 104874
  src/app/helptext/storage/volumes/volume-list.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#3603 NAS-104954 / 12.0 / NAS-104954
  src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
Labels: backport-11.3

#3606 NAS-104835 / 11.3 / Don't append a controller label if one is not available
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: backport-12.0

#3613 NAS-104588 / 12.0 / Validate against quota sizes smaller than 1G
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Labels: backport-11.3

#3622 NAS-104963 / 12.0 / NAS-104963
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Labels: backport-11.3

#3686 DOCS-302: Update Exclude Child Datasets help text (11.3-U2)
  src/app/helptext/task-calendar/replication/replication.ts
Labels: Help Text

#3685 DOCS-302: Update Exclude Child Datasets help text (12.0)
  src/app/helptext/task-calendar/replication/replication.ts
Labels: Help Text

#3681 NAS-104842 / 11.3 / NAS-104842
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
Labels: backport-12.0

#3678 NAS-105013 / 12.0 / Nas 105013
  src/app/helptext/storage/volumes/manager/manager.ts
  src/app/pages/storage/volumes/manager/manager.component.css
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
Labels: backport-11.3

#3677 NAS-104864 / 11.3 / NAS-104864
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
Labels: backport-12.0

#3669 DOCS-291 backport "enable" heptext for iSCSI extents.
  src/app/helptext/sharing/iscsi/iscsi.ts
Labels: Help Text

#3668 DOCS-291 helptext for "enable" in iSCSI extents
  src/app/helptext/sharing/iscsi/iscsi.ts
Labels: Help Text

#3640 NAS-104947 / 11.3 / NAS-104947
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
Labels: backport-12.0

#3639 NAS-105061 / 12.0 / Fix name of device when removing disk
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Labels: backport-11.3

#3663 NAS-105124 / 12.0 / Fix labels for pool import wizard job dialog
  src/app/helptext/storage/volumes/volume-import-wizard.ts
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
Labels: backport-11.3

#3632 NAS-104696 / 12.0 / Check job description for whether or not the scrub is actually complete
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-11.3

#3596 NAS-104939 / 12.0 / Nas 104939
  src/app/pages/jails/jail-list/jail-list.component.ts
  src/app/pages/jails/storages/storage-list/storage-list.component.ts
  src/app/pages/plugins/plugins.component.ts
Labels: backport-11.3
