Repository truenas/webui, pull requests merged in 2020-11, with the labels that each got.

#4790 NAS-107713 / 12.0 / Nas 107713
  src/app/helptext/storage/volumes/datasets/dataset-acl.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
Labels: backport-20.12

#4813 NAS-108124 / 20.12 / NAS-108124 add validation to naming_schema of snapshot-form to exclud…
  src/app/pages/common/entity/entity-form/components/form-errors/form-errors.component.html
  src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
Labels: backport-12.0

#4748 NAS-107702 / 12.0 / Nas 107702
  src/app/helptext/directoryservice/idmap.ts
  src/app/pages/directoryservice/idmap-form/idmap-form.component.ts
  src/app/pages/directoryservice/idmap-list/idmap-list.component.ts
Labels: backport-20.12

#4767 NAS-107889 / 12.0 / Nas 107889
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
Labels: backport-20.10

#4822 NAS-108089 / 20.12 / Nas 108089(2)
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
Labels: backport-20.12

#4781 NAS-107507 / 20.12 / Nas 107507
  src/app/helptext/services/components/service-nfs.ts
  src/app/pages/services/components/service-nfs/service-nfs.component.ts
  src/app/services/docs.service.ts
Labels: backport-12.0

#4805 NAS-107948 / 20.12 / NAS-107948 Add sys dataset warnings
  src/app/helptext/storage/volumes/volume-list.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4829 NAS-108087 / 12.0 / remove zfs_guid/nas-108087
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Labels: backport-20.12

#4810 NAS-108068 / 20.12 / NAS-108068 Re-label itop feature
  src/app/helptext/services/components/service-snmp.ts
Labels: backport-12.0

#4817 NAS-107419 / 12.0 / Nas 107419
  src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.css
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-20.12

#4838 NAS-108240 / 20.12 / Nas 108240
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: backport-20.12

#4844 NAS-108279 / 12.0 / Monitor password is required
  src/app/pages/services/components/service-ups/service-ups.component.ts
Labels: backport-20.12

#4855 Fix the friendly build
  package.json
Labels: backport-12.0

#4843 NAS-108226 / 12.0 / Adjust error handling for replace and extend actions
  src/app/helptext/storage/volumes/volume-status.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Labels: backport-20.12

#4788 NAS-107864 / 12.0 / Nas 107864
  src/app/helptext/system/email.ts
  src/app/pages/system/email/email.component.ts
Labels: backport-20.12

#4860 NAS-107928 / 12.0 / NAS-107928
  src/app/pages/reportsdashboard/components/report/report.component.ts
  src/app/pages/reportsdashboard/reports.service.ts
Labels: backport-20.12

#4848 NAS-107832 / 20.12 / Fix network activity display issue / NAS-107832
  src/app/core/components/widgets/widgetnic/widgetnic.component.ts
Labels: backport-12.0

#4845 NAS-108272 / Added 'Pool' column in disks list in 'Storage / Disks'
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
Labels: backport-20.12

#4871 NAS-108329 / 12.0 / NAS-108329
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/assets/images/servers/R10.png
  src/assets/images/servers/R20.png
  src/assets/images/servers/R40.png
  src/assets/images/servers/R50.png
Labels: backport-20.12

#4825 NAS-108085 / 12.0 / fix NAS-108085
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Labels: backport-20.12

#4872 NAS-107694 / 12.0 / Add Pool options dialog with auto-trim option
  src/app/helptext/storage/volumes/volume-list.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-20.12

#4870 NAS-108323 / 12.0 / Nas 108323
  src/app/helptext/system/cloudcredentials.ts
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: backport-20.12

#4886 NAS-108343 / 20.12 / Do not pass `force` to `iscsi.target.delete` multiple times
  src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
Labels: backport-12.0

#4898 NAS-108396 / 20.12 / NAS-108396
  src/app/pages/system/update/update.component.html
Labels: backport-12.0

#4911 NAS-107697 / 12.0 / WebUI makes firefox 80.0.1 hang
  src/app/core/components/viewchartgauge/viewchartgauge.component.ts
Labels: backport-20.12
