Repository truenas/webui, pull requests merged in 2020-08, with the labels that each got.

#4451 NAS-106868 / 12.1 / Nas 106868
  src/app/helptext/storage/volumes/datasets/dataset-acl.ts
  src/app/helptext/storage/volumes/datasets/dataset-permissions.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4461 NAS-107016 / 12.1 / Sort the timezones alphabetically in System General
  src/app/pages/system/general/general.component.ts
Labels: backport-12.0

#4464 NAS-107038 / 12.1 / NAS-107038 Fix deletion of extra properties before submitting
  src/app/pages/system/ca/ca-add/ca-add.component.ts
  src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
Labels: backport-12.0

#4466 NAS-107029 / 12.1 / Apply css class to make errors on comboboxes look better
  src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
Labels: backport-11.3, backport-12.0

#4468 NAS-107071 / 12.1 / NAS-107071 globalconfig icon to close VM device table
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/vm/devices/device-list/device-list.component.ts
Labels: backport-12.0

#4467 NAS-106964 / 12.1 / Nas 106964
  src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
  src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
Labels: backport-12.0

#4469 NAS-107072 / 12.1 / NAS-107072 Refine validation to allow only gigs and integers
  src/app/pages/system/advanced/advanced.component.ts
Labels: backport-12.0

#4476 NAS-107046 / 12.1 / Correct verbiage on physical network interface delete
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
Labels: backport-12.0

#4478 NAS-107079 / 12.1 / NAS-107079
  src/app/pages/system/ca/ca-add/ca-add.component.ts
  src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
Labels: backport-12.0

#4481 NAS-107093 / 12.1 / Fix relogin after refresh on cached section detection, use window reload
  src/app/app.component.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-12.0

#4490 NAS-107118 / 12.1 / NAS-107118
  src/app/core/services/system-profile.service.ts
Labels: backport-12.0

#4489 NAS-107120 / 12.1 / change failover_vhid to select type instead of input type
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: backport-11.3, backport-12.0

#4485 NAS-107098 / 12.1 / Listen to navigation events for cleanup to prevent memory leaks
  src/app/pages/common/entity/entity-table/entity-table.component.ts
Labels: backport-11.3, backport-12.0

#4486 NAS-107097 / 12.1 / NAS-107097 Send only top-level datasets to the flatten utility
  src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
Labels: backport-12.0

#4498 NAS-107118 / 12.1 / Check for license before checking license has ha
  src/app/core/services/system-profile.service.ts
Labels: backport-12.0

#4488 NAS-107081 / 12.1 / NAS-107081 Validate for optional CIDR
  src/app/pages/common/entity/entity-form/validators/ip-validation.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
Labels: backport-12.0

#4504 NAS-106814 / 12.1 / Nas 106814
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
Labels: backport-12.0

#4505 NAS-107030 / 12.1 / Nas 107030
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4509 NAS-107103 / 12.1 / NAS-107103 Add warning about acl mismatch
  src/app/helptext/sharing/smb/smb.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-12.0

#4519 NAS-107129 / 12.1 / Nas 107129
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/storage/disks/smart-results/smart-results.component.ts
Labels: backport-12.0

#4513 NAS-106995 / 12.0 / NAS-106995 Show user-preferred time format in uptime
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/app/services/locale.service.ts
Labels: backport-12.1

#4527 DOCS-866: Update cloud sync task "Folder" helptext
  src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
Labels: Help Text, backport-12.1

#4524 NAS-107121 / 12.0 / Nas 107121
  src/app/helptext/network/interfaces/interfaces-form.ts
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: backport-11.3, backport-12.1

#4526 NAS-107162: Update helptext about smb.conf
  src/app/helptext/sharing/smb/smb.ts
Labels: Help Text, backport-12.1

#4535 NAS-107263 / 12.0 / NAS-107263 Fix typo on pool name variable
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.1

#4531 NAS-107159 / 12.0 / Fix issues with size estimate when repeating in extend mode
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
Labels: backport-11.3, backport-12.1

#4532 NAS-107101 / 12.0 / Create better progress dialog for resilvering status
  src/app/app.module.ts
  src/app/components/common/dialog/resilver-progress/resilver-progress.component.css
  src/app/components/common/dialog/resilver-progress/resilver-progress.component.html
  src/app/components/common/dialog/resilver-progress/resilver-progress.component.ts
  src/app/components/common/topbar/topbar.component.ts
Labels: backport-12.1

#4533 DOCS-866: Update cloud sync task "Folder" helptext (12.1 port)
  src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
Labels: Help Text

#4534 NAS-107162: clarify smb.conf manual page links (12.1 port)
  src/app/helptext/sharing/smb/smb.ts
Labels: Help Text

#4528 NAS-107073 / 12.0 / NAS-107073-stable
  src/app/core/services/coreservices.module.ts
  src/app/core/services/data.service.ts
  src/app/core/services/stats.service.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: backport-12.1

#4542 NAS-106981 / 12.1 / Nas 106981
  src/app/helptext/storage/volumes/datasets/dataset-acl.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-12.0

#4545 NAS-107260 / 12.1 / NAS-107260 fixed data column sort issue
  src/app/services/storage.service.ts
Labels: backport-12.0

#4547 NAS-107248 / 12.1 / NAS-107248
  src/app/services/storage.service.ts
Labels: backport-12.0

#4544 NAS-107053 / 12.1 / NAS-107053
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Labels: backport-11.3, backport-12.0

#4556 NAS-107053 / 12.1 / NAS-107053 fix
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
Labels: backport-12.0

#4560 NAS-107265 / 11.3 / NAS-107265
  src/app/components/common/breadcrumb/breadcrumb.component.css
  src/app/components/common/breadcrumb/breadcrumb.component.html
  src/app/components/common/breadcrumb/breadcrumb.component.ts
Labels: backport-12.0

#4577 NAS-107292 / 12.1 / Nas 107292
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
Labels: backport-11.3, backport-12.0

#4575 NAS-107316 / 12.1 / NAS-107316 Delay first check of drivers
  src/app/pages/services/components/service-ups/service-ups.component.ts
Labels: backport-12.0

#4571 NAS-107326 / 12.1 / Change Documentation link
  src/app/components/common/dialog/about/about-dialog.component.html
Labels: backport-12.0

#4590 NAS-104906 / 12.0 / NAS-104906 Fix typo for remotepath
  src/app/pages/task-calendar/rsync/rsync-list/rsync-list.component.ts
Labels: backport-11.3, backport-12.1

#4589 NAS-107368 / 20.10 / Nas 107368
  src/app/helptext/sharing/smb/smb.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-12.0

#4588 NAS-107372 / 11.3 / Nas 107372
  src/app/pages/storage/import-disk/import-disk.component.ts
  src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/task-calendar/rsync/rsync-list/rsync-list.component.ts
  src/app/services/job.service.ts
Labels: backport-12.0, backport-12.1

#4594 NAS-107385 / 20.10 / NAS-107385
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/manager/manager.component.ts
Labels: backport-12.0

#4586 NAS-107361 / 20.10 / NAS-107631 Add pipe
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-12.0
