Repository truenas/webui, pull requests merged in 2020-09, with the labels that each got.

#4601 NAS-107401 / 20.10 / NAS-107401 disable autocomplete for one-time pw
  src/app/views/sessions/signin/signin.component.html
Labels: backport-11.3, backport-12.0

#4604 NAS-107177 / 11.3 / NAS-107177
  src/app/helptext/storage/volumes/volume-list.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0, backport-20.10

#4610 NAS-107400 / 11.3 / Add generic methods/calls for root password field, add root password to save config
  src/app/helptext/global-helptext.ts
  src/app/pages/system/general/general.component.ts
  src/app/services/system-general.service.ts
Labels: backport-12.0, backport-20.10

#4615 NAS-107449 / 12.0 / NAS-107449 reset string
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Labels: backport-20.10

#4618 NAS-107442 / 12.0 / NAS-107442 Remove non-existing cols from preferred list
  src/app/pages/common/entity/entity-table/entity-table.component.ts
Labels: backport-11.3, backport-20.10

#4622 NAS-106704 / 11.3 / NAS-106704
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Labels: backport-12.0, backport-20.10

#4625 NAS-107472
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
Labels: backport-20.10

#4614 NAS-107400 / 20.10 / Add generic password confirm dialog for exporting dataset keys
  src/app/app.module.ts
  src/app/helptext/global-helptext.ts
  src/app/pages/common/password-dialog/password-dialog.component.css
  src/app/pages/common/password-dialog/password-dialog.component.html
  src/app/pages/common/password-dialog/password-dialog.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/services/dialog.service.ts
Labels: backport-12.0

#4630 NAS-107513 / 12.0 / Clarify overprovision size field name
  src/app/helptext/system/advanced.ts
Labels: backport-20.10

#4637 NAS-107528 / 20.10 / Only show dedup if license is present
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Labels: backport-11.3, backport-12.0

#4644 NAS-107531 / 20.10 / NAS-107531
  src/app/helptext/task-calendar/replication/replication.ts
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Labels: backport-12.0

#4638 NAS-107502 / 12.0 / NAS-107502
  src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.ts
Labels: backport-20.10

#4627 NAS-107439 / 12.0 / NAS-107439
  src/app/helptext/directoryservice/activedirectory.ts
Labels: Help Text, backport-20.10

#4616 NAS-107436 / 12.0 / Nas 107436
  src/app/app.routes.ts
  src/app/components/common/breadcrumb/breadcrumb.component.html
  src/app/components/common/breadcrumb/breadcrumb.component.ts
  src/app/services/route-parts/route-parts.service.ts
Labels: backport-20.10

#4655 NAS-107400 / 20.10 / Remove circular dependency, console.log
  src/app/pages/common/password-dialog/password-dialog.component.ts
Labels: backport-12.0

#4658 NAS-107502 / 20.10 / NAS-107502
  src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.ts
Labels: backport-12.0

#4662 NAS-107552 / 12.0 / NAS-107552 Make all report labels aware of timezone
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/reportsdashboard/components/report/report.component.html
  src/app/pages/reportsdashboard/components/report/report.component.ts
  src/app/services/locale.service.ts
Labels: backport-20.10

#4666 NAS-107621 / 20.10 / Remove auth.token call from ping
  src/app/services/ws.service.ts
Labels: backport-12.0

#4668 NAS-107529 / 12.0 / Fix snapshot create for zvol, fix traceback on zvol menu click
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-20.10

#4684 NAS-107545 / 20.10 / Nas 107545
  src/app/pages/common/entity/entity-job/entity-job.component.html
  src/app/pages/common/entity/entity-job/entity-job.component.ts
  src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: backport-12.0

#4700 NAS-107645 / 20.10 / NAS-107645
  src/app/helptext/services/components/service-smb.ts
Labels: Help Text, backport-12.0

#4698 NAS-107661 / 20.10 / NAS-107661
  src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/sharing/iscsi/iscsi.component.ts
Labels: backport-11.3, backport-12.0

#4702 NAS-107584 / 12.0 / Nas 107584
  src/app/components/common/topbar/topbar.component.ts
  src/app/pages/system/update/update.component.ts
Labels: backport-20.10

#4710 NAS-107699 / 12.0 / NAS-107699 Use built in even-odd classes
  src/assets/styles/themes/ix-blue.scss
Labels: backport-11.3
