Repository truenas/webui, pull requests merged in 2020-03, with the labels that each got.

#3718 NAS-105215 / 11.3 / Fix hour format for manual snapshot creation
  src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#3708 NAS-105216 / 11.3 / Fix naming_schema_tooltip
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: backport-12.0, jira

#3612 NAS-103803 / 11.3 / Nas 103803
  src/app/helptext/system/update.ts
  src/app/pages/system/update/update.component.ts
Labels: backport-12.0

#3724 NAS-105267 / 11.3 / NAS-105267
  src/app/services/job.service.ts
Labels: backport-12.0

#3728 NAS-104998 / 11.3 / NAS-104998: Synchronize UI help text and 11.3 docs
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: Help Text

#3729 NAS-104998 / 12.0 / NAS-104998: Synchronize UI help text and docs (12.0 port)
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: Help Text

#3734 NAS-105125 / 12.0 / Pass in dialog service to fix error handling for certificate delete
  src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
Labels: backport-11.3

#3733 NAS-105191
  src/app/helptext/global-helptext.ts
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
Labels: backport-11.3

#3727 NAS-105113 / 11.3 / NAS-105113: Adjust field names and expand help text in Replication Tasks
  src/app/helptext/task-calendar/replication/replication-wizard.ts
  src/app/helptext/task-calendar/replication/replication.ts
Labels: Help Text

#3736 NAS-105113 / 12.0 / NAS-105113: Adjust field names and expand help text in Replication Tasks (12 port)
  src/app/helptext/task-calendar/replication/replication-wizard.ts
  src/app/helptext/task-calendar/replication/replication.ts
Labels: Help Text

#3742 NAS-105125 / 12.0 / Error message can also appear in the progress on a failed state
  src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
Labels: backport-11.3, backported

#3751 NAS-105144 / 12.0 / Do not show the disks error message when extending with stripes
  src/app/pages/storage/volumes/manager/manager.component.ts
Labels: backport-11.3

#3747 NAS-105199 / 11.3 / Reset the array of importable volumes upon success response to prevent double options
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
Labels: backport-12.0

#3759 NAS-105141 / 11.3 / NAS-105141
  src/app/core/classes/hardware/m50_rear.ts
  src/app/core/classes/hardware/vdev-labels-svg.ts
  src/app/core/classes/system-profiler.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.css
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.html
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
  src/assets/images/hardware/m50/m50_rear_1080p.png
  src/assets/images/hardware/m50/m50_rear_960w.png
Labels: backport-12.0

#3756 NAS-105302 / 11.3 / Remove nopercent for boot environment attach
  src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
Labels: backport-12.0

#3753 NAS-105253 / 11.3 / Nas 105253
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
  src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
Labels: backport-12.0

#3770 NAS-105143 / 11.3 / NAS-105143
  src/app/core/classes/system-profiler.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
Labels: backport-12.0

#3802 NAS-105366 / 12.0 / NAS-105366: Update help text for Allow Taking Empty Snapshots
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: Help Text

#3805 NAS-105301 / 12.0 / Nas 105301
  src/app/pages/systemprocesses/system-processes.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
Labels: backport-11.3

#3803 NAS-105366 / 11.3 / NAS-105366: Update help text for Allow Taking Empty Snapshots
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: Help Text

#3831 NAS-105514 / 12.0 / NAS-105514
  src/app/pages/reportsdashboard/components/report/report.component.ts
  src/app/pages/reportsdashboard/reportsdashboard.component.ts
Labels: backport-11.3

#3836 NAS-104078 / 12.0 / NAS-104078: Clean up UI text and make more consistent
  src/app/helptext/directoryservice/nis.ts
  src/app/helptext/network/configuration/configuration.ts
  src/app/helptext/services/components/service-afp.ts
  src/app/helptext/services/components/service-dynamic-dns.ts
  src/app/helptext/services/components/service-ftp.ts
  src/app/helptext/services/components/service-rsync.ts
  src/app/helptext/services/components/service-ssh.ts
  src/app/helptext/services/components/service-tftp.ts
  src/app/helptext/sharing/afp/afp.ts
  src/app/helptext/sharing/iscsi/iscsi.ts
  src/app/helptext/sharing/webdav/webdav.ts
  src/app/helptext/system/advanced.ts
  src/app/helptext/system/ca.ts
  src/app/helptext/system/certificates.ts
  src/app/helptext/system/email.ts
  src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
  src/app/helptext/task-calendar/cron/cron-form.ts
  src/app/helptext/task-calendar/replication/replication-wizard.ts
  src/app/helptext/task-calendar/resilver/resilver.ts
  src/app/helptext/task-calendar/resync/resync-form.ts
  src/app/helptext/task-calendar/scrub/scrub-form.ts
  src/app/helptext/task-calendar/smart/smart.ts
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
  src/app/helptext/vm/vm-wizard/vm-wizard.ts
  src/app/pages/system/alertservice/alert-service/alert-service.component.ts
  src/app/pages/system/system.routing.ts
Labels: Help Text
