Repository truenas/webui, pull requests merged in 2020-05, with the labels that each got.

#4002 NAS-105963 / 11.3 / NAS-105963
  src/app/components/common/topbar/topbar.component.ts
Labels: backport-12.0

#4010 NAS-105960 / 11.3 / NAS-105960: Rework Network Interface changes dialogs
  src/app/helptext/network/interfaces/interfaces-list.ts
Labels: Help Text

#4009 NAS-105960 / 12.0 / NAS-105960: Rework Network Interface changes dialogs (12.0)
  src/app/helptext/network/interfaces/interfaces-list.ts
Labels: Help Text

#4032 NAS-106012 / 11.3 / NAS-106012: update LDAP auxiliary parameters file and link
  src/app/helptext/directoryservice/ldap.ts
Labels: Help Text

#4033 NAS-106012 / 12.0 / NAS-106012: update LDAP auxiliary parameters file and link
  src/app/helptext/directoryservice/ldap.ts
Labels: Help Text

#4047 NAS-106045 / 12.0 / NAS-106045
  src/app/core/classes/system-profiler.ts
Labels: backport-11.3

#4098 NAS-106156 / 12.0 / NAS-106156
  src/app/core/services/preferences.service.ts
  src/app/pages/plugins/available-plugins/available-plugins.component.css
  src/app/pages/plugins/available-plugins/available-plugins.component.html
  src/app/pages/plugins/available-plugins/available-plugins.component.ts
Labels: backport-11.3

#4110 NAS-106176 / 12.0 / Nas 106176
  src/app/pages/jails/jail-list/jail-list.component.ts
  src/app/pages/plugins/plugins.component.ts
Labels: backport-11.3

#4109 NAS-106165 / 12.0 / Nas 106165
  src/app/helptext/account/group-list.ts
  src/app/helptext/account/user-list.ts
  src/app/pages/account/groups/group-list/group-list.component.ts
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.css
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/services/dialog.service.ts
Labels: backport-11.3

#4127 NAS-106249 / 12.0 / NAS-106249
  src/app/helptext/system/alert-settings.ts
  src/app/pages/system/alert/alert.component.ts
Labels: backport-11.3

#4145 NAS-106275 / 12.0 / NAS-106275
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Labels: backport-11.3
