Repository truenas/webui, pull requests merged in 2020-12, with the labels that each got.

#4925 NAS-108511 / 20.12 / Update Text Strings
  src/app/helptext/system/ssh-connections.ts
  src/app/helptext/system/support.ts
Labels: backport-12.0, skip jira status

#4923 NAS-108475 / 20.12 / Nas 108475
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Labels: backport-12.0

#4888 NAS-108308 / 12.0 / Add validation for file upload on cloud credential
  src/app/helptext/system/cloudcredentials.ts
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: backport-20.12, backported

#4900 NAS-108361 / 12.0 / Change icon color for unavail case on pool card / NAS-108361
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Labels: backport-20.12

#4907 NAS-108298 / 12.0 / Nas 108298
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Labels: backport-20.12

#4913 NAS-108353 / 12.0 / Moved estimateSize() method to the end of ngOnInit so proper values a…
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
Labels: backport-20.12, backported

#4934 NAS-108500 / 12.0 / fix pCloud hostname is not sent when verifying credentials
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: backport-20.12

#4937 NAS-108495 / 12.0 / NAS-108495
  src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list.component.html
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.html
Labels: backport-20.12

#4954 NAS-108530 / 12.0 / NAS-108530
  src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
  src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.html
  src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.html
  src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
  src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
  src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html
  src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
  src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
  src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
  src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.html
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
  src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
  src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/system/support/fn-support/fn-support.component.ts
  src/app/pages/system/support/production-status/production-status.component.ts
  src/app/pages/system/support/tn-support/tn-support.component.ts
Labels: backport-20.12

#4963 NAS-108628 / 12.0 / Keep yes/no enabled column for consistency
  src/app/pages/task-calendar/cron/cron-list/cron-list.component.ts
Labels: backport-20.12

#4964 NAS-105714 / 12.0 / User home directory creation case insensitive
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-20.12

#4971 NAS-108660 / 12.0 / make error text pre-formatted
  src/app/pages/common/info-dialog/info-dialog.component.scss
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
Labels: backport-20.12

#4967 NAS-108639 / 12.0 / NAS-108639
  src/app/helptext/network/interfaces/interfaces-form.ts
Labels: backport-21.02

#4975 NAS-105062 / 12.0 / Pass empty array for bridge members when Bridge type
  src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Labels: backport-21.02

#4994 NAS-108640 / 12.0 / Update Save Config modal
  src/app/helptext/system/general.ts
  src/app/pages/system/general/general.component.ts
Labels: backport-21.02

#4999 NAS-108681 / 21.02 / NAS-108681
  src/app/core/services/api.service.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: backport-12.0

#4956 NAS-108535 / 12.0 / Nas 108535
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/task-calendar/smart/smart-form/smart-form.component.ts
Labels: backport-21.02

#5005 NAS-106588 / 21.02 / Can't log in to GUI with <enter> when credentials are saved / Nas 106588
  src/app/views/sessions/signin/signin.component.html
  src/app/views/sessions/signin/signin.component.scss
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-12.0

#5003 NAS-108629 / Added case for nfsstatsbytes in optimizeLegend
  src/app/pages/reportsdashboard/reports-utils.worker.ts
Labels: backport-21.02

#4977 NAS-108600 / 12.0 / Still no Reporting graphs afer 12.0-U1 / Nas 108600
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
Labels: backport-21.02

#4973 NAS-108481 / 12.0 / zvol zfs encryption settings missing from UI
  src/app/helptext/storage/volumes/zvol-form.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
Labels: backport-21.02

#4978 NAS-108665 / 12.0 / Update email settings form
  src/app/helptext/system/email.ts
  src/app/pages/common/entity/entity-form/components/form-button/form-button.component.ts
  src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/system/email/email.component.ts
Labels: backport-21.02
