Repository truenas/webui, pull requests merged in 2020-07, with the labels that each got.

#4277 NAS-106556: Update Services/SSH/Allow Password Authentication help text
  src/app/helptext/services/components/service-ssh.ts
Labels: Help Text, backport-12.0

#4294 NAS-106483 / 12.1 / NAS-106483
  src/app/core/components/widgets/widgetnic/widgetnic.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
Labels: backport-12.0

#4319 NAS-106556 / 12.0 / NAS-106556: backport SSH helptext improvement to 12.0-BETA2
  src/app/helptext/services/components/service-ssh.ts
Labels: Help Text

#4318 NAS-106649 / 12.1 / NAS-106649
  src/app/pages/network/staticroutes/staticroute-list/staticroute-list.component.ts
Labels: backport-12.0

#4314 NAS-106612 / 12.1 / NAS-106612 Use TN Core as remote in client config
  src/app/pages/services/components/service-openvpn/service-openvpn-server/service-openvpn-server.component.ts
Labels: backport-12.0

#4333 NAS-106641 / 12.1 / NAS-106641 Update connection methods for VM and jail consoles
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/app/services/shell.service.ts
Labels: backport-12.0

#4328 NAS-106660 / 12.1 / Nas 106660
  src/app/helptext/services/components/service-rsync.ts
  src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncconfiguration-list/rsyncconfiguration-list.component.ts
  src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
Labels: backport-12.0

#4327 Remove option to restart jails/vms on dataset unlock, this should just always happen
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
Labels: backport-12.0

#4326 NAS-106653 / 12.1 / Nas 106653
  src/app/helptext/system/advanced.ts
  src/app/helptext/system/general.ts
  src/app/pages/system/advanced/advanced.component.html
  src/app/pages/system/advanced/advanced.component.ts
Labels: backport-12.0

#4341 NAS-106666 / 12.1 / Convert dataset lock into a job
  src/app/helptext/storage/volumes/volume-list.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4344 NAS-106690 / 12.1 / NAS-106690 Allow clearing of k-principal, realm, cert
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
Labels: backport-12.0

#4342 NAS-106621 / 12.1 / Nas 106621
  src/app/helptext/storage/volumes/datasets/dataset-quotas.ts
  src/app/pages/common/entity/entity-table/entity-table.component.html
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-12.0

#4340 NAS-106637 / 12.1 / NAS-106637
  src/app/pages/plugins/plugins.component.ts
Labels: backport-12.0

#4351 NAS-106583 / 12.1 / Nas 106583
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
Labels: backport-11.3, backport-12.0

#4349 NAS-106682 / 12.1 / NAS-106682
  src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts
Labels: backport-11.3, backport-12.0

#4350 NAS-106665 / 12.1 / Add salt to buildtime url to prevent caching of buildtime file
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-12.0

#4357 NAS-106665 / 12.1 / Skip buildtime check while in devmode
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-12.0

#4361 NAS-106621 / 12.1 / NAS-106621 Specify string value for error condition
  src/app/pages/common/entity/entity-table/entity-table.component.ts
Labels: backport-12.0

#4360 NAS-106737 / 12.1 / Nas 106737
  src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
Labels: backport-12.0

#4367 NAS-106671 / 12.1 / NAS-106671-master
  src/app/core/components/widgets/widgetpool/widgetpool.component.html
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: backport-12.0

#4371 NAS-106740 / 12.1 / NAS-106740
  src/app/helptext/services/components/service-ups.ts
  src/app/pages/services/components/service-ups/service-ups.component.ts
Labels: backport-12.0

#4364 NAS-106747 / 12.1 / NAS-106747 Remove get option from query
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-12.0

#4329 NAS-106560 / 12.1 / NAS-106560
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/classes/hardware/es60.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
Labels: backport-12.0

#4372 NAS-106782 / 12.1 / Improve verbiage for HA disabled reasons
  src/app/views/sessions/signin/signin.component.html
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-12.0

#4378 change FreeNAS to TrueNAS on System Support Page
  src/app/helptext/system/support.ts
Labels: backport-12.0

#4385 NAS-106749 geli uifields patch
  src/app/helptext/storage/volumes/volume-key.ts
Labels: backport-11.3, backport-12.0

#4383 NAS-106790 / 12.1 / NAS-106790 Allow for blank values
  src/app/pages/system/ca/ca-add/ca-add.component.ts
Labels: backport-12.0

#4381 NAS-106791 / 12.1 / NAS-106791
  src/app/helptext/system/ca.ts
  src/app/helptext/system/certificates.ts
  src/app/pages/system/ca/ca-add/ca-add.component.ts
  src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
Labels: backport-12.0

#4366 NAS-106527 / 12.1 / Nas 106527
  src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.html
  src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.ts
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/helptext/storage/volumes/download-key.ts
  src/app/helptext/storage/volumes/manager/manager.ts
Labels: backport-12.0

#4391 NAS-106793 / 12.0 / Ensure intervals are cleared before logging in to prevent memory leak
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-11.3, backport-12.1

#4399 NAS-106787 / 12.1 / NAS-106787
  src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts
  src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-list/authorizedaccess-list.component.ts
  src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
  src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
  src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
Labels: backport-11.3, backport-12.0

#4402 NAS-106844 / 12.1 / NAS-106844
  src/app/services/navigation/navigation.service.ts
Labels: backport-11.3, backport-12.0

#4407 NAS-106818 / 12.1 / NAS-106818
  src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts
Labels: backport-11.3, backport-12.0

#4406 NAS-106842 / 12.1 / NAS-106842 disable ip addresses when dhcp is selected
  src/app/pages/network/ipmi/ipmi.component.ts
Labels: backport-11.3, backport-12.0

#4412 NAS-106859 / 12.1 / Nas 106859
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Labels: backport-12.0

#4418 NAS-106876 / 12.1 / NAS-106876
  src/app/pages/task-calendar/scrub/scrub-list/scrub-list.component.ts
Labels: backport-12.0

#4416 NAS-106870 / 12.1 / Nas 106870
  src/app/helptext/sharing/smb/smb.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Labels: backport-12.0

#4417 NAS-106797 / 12.1 / NAS-106797
  src/app/pages/task-calendar/snapshot/snapshot-list/snapshot-list.component.ts
Labels: backport-11.3, backport-12.0

#4398 NAS-105099 / 12.1 / Improve naming schema tooltip
  src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Labels: backport-11.3, backport-12.0

#4434 NAS-106854 / 12.1 / NAS-106854
  src/app/pages/plugins/plugins.component.ts
Labels: backport-11.3, backport-12.0

#4442 NAS-106949 / 12.1 / Nas 106949
  src/app/helptext/system/2FA.ts
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
  src/app/pages/common/entity/entity-form/models/field-config.interface.ts
  src/app/pages/system/two-factor/qr-dialog.html
  src/app/pages/system/two-factor/two-factor.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-12.0

#4441 NAS-106836 / 12.1 / Add confirm passphrase field for dataset encryption
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4440 NAS-106919 / 12.1 / Use generic error handler for save debug errors
  src/app/pages/system/advanced/advanced.component.ts
Labels: backport-11.3, backport-12.0

#4447 NAS-106824 / 12.1 / Only allow exporting dataset keys if a pool has a key encrypted dataset
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#4449 NAS-106920 / 12.1 / Nas 106920
  src/app/helptext/sharing/afp/afp.ts
  src/app/helptext/sharing/smb/smb.ts
  src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
  src/app/pages/sharing/afp/afp-form/afp-form.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-12.0

#4414 NAS-106841 / 12.1 / NAS-106841
  src/app/components/common/topbar/topbar.component.ts
  src/app/helptext/topbar.ts
Labels: backport-12.0

#4455 NAS-107007 / 12.1 / NAS-107007
  src/app/pages/services/components/service-openvpn/service-openvpn-client/service-openvpn-client.component.ts
  src/app/pages/services/components/service-openvpn/service-openvpn-server/service-openvpn-server.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-12.0

#4415 NAS-106839 / 12.1 / NAS-106839
  src/app/components/common/topbar/topbar.component.ts
  src/app/components/common/topbar/topbar.template.html
  src/app/helptext/topbar.ts
Labels: backport-12.0
