Repository truenas/webui, pull requests merged in 2020-10, with the labels that each got.

#4721 NAS-107761 / 20.10 / Nas 107761
  src/app/views/sessions/signin/signin.component.html
Labels: backport-12.0

#4722 NAS-107797 / 20.10 / Fix error handling for boot env actions and traceback upon leaving pages
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
Labels: backport-12.0

#4727 "AFP" -> "SMB" in SMB helptext
  src/app/helptext/sharing/smb/smb.ts
Labels: Help Text, backport-12.0

#4735 NAS-107794 / 12.0 / NAS-107794 Update actions on changes to row
  src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
Labels: backport-20.10

#4736 NAS-107651 / 12.0 / Nas 107651
  src/app/helptext/storage/volumes/datasets/dataset-form.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Labels: backport-20.10

#4741 NAS-107638 / 12.0 / NAS-107638
  src/app/pages/jails/storages/storage-list/storage-list.component.ts
Labels: backport-11.3, backport-20.10

#4745 NAS-107851 / 12.0 / NAS-107851 Make dns_domain_name optional
  src/app/pages/directoryservice/idmap-form/idmap-form.component.ts
Labels: backport-20.10

#4753 NAS-107837 / 12.0 / Fix nfs security options to match middleware expected case
  src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
Labels: backport-20.10

#4768 NAS-107951 / 12.0 / NAS-107951 Make room for all menu items
  src/app/components/common/navigation/navigation.component.ts
  src/assets/styles/fn-styles.css
Labels: backport-11.3

#4696 NAS-107646 / 20.10 / Prevent and warn users from using ipv6 on HA
  src/app/helptext/network/interfaces/interfaces-form.ts
  src/app/pages/network/forms/interfaces-form.component.ts
Labels: backport-12.0, backported

#4709 NAS-107741 / 20.10 / Handle alerts better in alert settings
  src/app/pages/system/alert/alert.component.ts
Labels: backport-12.0, backported

#4711 NAS-107498 / 20.10 / NAS-107498
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
Labels: backport-12.0, backported

#4714 NAS-107607 / 20.10 / Nas 107607
  src/app/pages/common/entity/entity-job/entity-job.component.html
  src/app/pages/common/entity/entity-job/entity-job.component.ts
  src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: backport-12.0, backported

#4731 NAS-107821 / 20.10 / NAS-107821
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Labels: backport-12.0, backported

#4763 NAS-107884 / 20.10 / NAS-107884
  src/app/helptext/network/interfaces/interfaces-list.ts
Labels: Help Text

#4752 NAS-107892 / 20.10 / NAS-107892
  src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
Labels: backport-12.0

#4765 NAS-107921 / 12.0 / NAS-107921 Add wsDelete
  src/app/pages/storage/VMware-snapshot/VMware-snapshot-list/VMware-snapshot-list.component.ts
Labels: backport-20.10

#4762 NAS-107895 / 12.0 / NAS-107895
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
Labels: backport-11.3, backport-20.10

#4780 NAS-108024 / 12.0 / NAS-108024 Add deprecation warning
  src/app/helptext/directoryservice/ldap.ts
Labels: backport-20.12

#4792 NAS-108068 / 20.12 / Nas 108068
  src/app/helptext/services/components/service-snmp.ts
  src/app/pages/services/components/service-snmp/service-snmp.component.ts
Labels: backport-12.0
