Repository truenas/webui, pull requests merged in 2021-07, with the labels that each got.

#5635 NAS-111261 / 21.08 / NAS-111261 - Improving type safety
  src/app/core/classes/display-object.ts
  src/app/core/classes/layout-object.ts
  src/app/core/services/animation.service.ts
  src/app/core/services/interaction-manager.service.ts
  src/app/enums/service-name.enum.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/interfaces/idmap-backend-options.interface.ts
  src/app/interfaces/iscsi-global-config.interface.ts
  src/app/interfaces/openvpn-server-config.interface.ts
  src/app/pages/account/groups/group-form/group-form.component.ts
  src/app/pages/account/groups/group-list/group-list.component.ts
  src/app/pages/applications/applications.service.ts
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/applications/manage-catalogs/manage-catalogs.component.ts
  src/app/pages/applications/pod-logs/pod-logs.component.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-form/services/field-relation.service.ts
  src/app/pages/common/select-dialog/select-dialog.component.html
  src/app/pages/common/select-dialog/select-dialog.component.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/directoryservice/idmap/idmap-form.component.ts
  src/app/pages/network/forms/service-openvpn-server.component.ts
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
  src/app/pages/services/components/service-rsync/service-rsync.component.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
  src/app/pages/services/components/service-smb/service-smb.component.ts
  src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/group-quota-form/group-quota-form.component.ts
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/system/advanced/advanced-settings.component.ts
  src/app/pages/system/advanced/console-form/console-form.component.ts
  src/app/pages/system/advanced/kernel-form/kernel-form.component.ts
  src/app/pages/system/advanced/syslog-form/syslog-form.component.ts
  src/app/pages/system/general-settings/general-settings.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/general-settings/localization-form/localization-form.component.ts
  src/app/pages/system/general-settings/support/proactive/proactive.component.ts
  src/app/services/dialog.service.ts
  src/app/services/idmap.service.ts
  src/app/services/system-general.service.ts
Labels: skip jira status

#5637 NAS-111261 / None / NAS-111261 - Improving type safety 2
  src/app/app.component.ts
  src/app/core/components/pipes/convert.pipe.ts
  src/app/enums/dataset-encryption-type.enum.ts
  src/app/enums/dataset-quota-type.enum.ts
  src/app/enums/mail-security.enum.ts
  src/app/enums/replication-encryption-key-format.enum.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/interfaces/chart-release-event.interface.ts
  src/app/interfaces/dataset-encryption-summary.interface.ts
  src/app/interfaces/dataset-has-vms-query-params.interface.ts
  src/app/interfaces/dataset-quota.interface.ts
  src/app/interfaces/dataset.interface.ts
  src/app/interfaces/mail-config.interface.ts
  src/app/interfaces/ntp-server.interface.ts
  src/app/interfaces/pool-attachment.interface.ts
  src/app/interfaces/pool-process.interface.ts
  src/app/interfaces/pool-unlock-query.interface.ts
  src/app/interfaces/replication-task.interface.ts
  src/app/interfaces/resilver-config.interface.ts
  src/app/interfaces/smb-config.interface.ts
  src/app/pages/api-keys/api-keys.component.ts
  src/app/pages/applications/applications.service.ts
  src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
  src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.ts
  src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
  src/app/pages/common/entity/entity-form/components/form-toggle-button/form-toggle-button.component.ts
  src/app/pages/common/entity/table/table.component.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/shell/shell.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/email/email.component.ts
  src/app/pages/system/general-settings/general-settings.component.ts
  src/app/pages/systemprocesses/system-processes.component.ts
  src/app/services/ws.service.ts
Labels: skip jira status

#5665 NAS-111396 / 12.0 / Revert r20a slot layout to default
  src/app/core/classes/hardware/r20a.ts
Labels: jira

#5671 NAS-111433 / 21.08 / Adding no-implicit this to introduce stricter checks.
  src/app/core/services/core-service/core.service.spec.ts
  src/app/directives/common/app-let.directive.ts
  src/app/directives/common/common-directives.module.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
  src/app/pages/vm/vm-form/vm-form.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
  src/app/services/validation.service.ts
  tsconfig.json
Labels: jira

#5687 NAS-111435 / 21.08 / Show nfsstatbytes graph
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
Labels: skip jira status

#5420 NAS-109476 / 21.08 / Explain replicate_tooltip to use new name_regex option
  src/app/helptext/data-protection/replication/replication.ts
Labels: blocked
