Repository truenas/webui, pull requests merged in 2021-12, with the labels that each got.

#6189 NAS-113598 / 22.02-RC.2 / NAS-113598: Added navigation on cancel click
  src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts
Labels: backport-22.02

#6193 NAS-113724 / 22.02-RC.2 / NAS-113724: Cannot Restore Config File
  src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
Labels: backport-22.02

#6196 NAS-113701 / 22.02-RC.2 / Alerts email form
  src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.scss
  src/app/pages/system/email/email.component.ts
Labels: backport-22.02

#6205 NAS-113739 / 22.02 / Fix enclosure selector for R Series
  src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/system/view-enclosure/view-enclosure.component.scss
  src/app/pages/system/view-enclosure/view-enclosure.component.ts
Labels: backport-22.02-RC.2

#6218 NAS-113453 / 13.0 / NAS-113453: Prevent recursive shutdowns and reboots
  src/app/views/others/config-reset/config-reset.component.ts
  src/app/views/others/failover/failover.component.ts
  src/app/views/others/reboot/reboot.component.ts
  src/app/views/others/shutdown/shutdown.component.ts
Labels: backport-22.02

#6226 NAS-113814 / 13.0 / Making `getServerTime` async
  src/app/pages/reportsdashboard/components/report/report.component.ts
  src/app/pages/reportsdashboard/reports.service.ts
Labels: backport-12.0
