Repository truenas/webui, pull requests merged in 2021-03, with the labels that each got.

#5159 NAS-108924 / 12.0 / Handled INHERITTED case for compression for zvol
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
Labels: backport-21.04

#5198 NAS-109203 / 12.0 / Improve error handling for LDAP auth
  src/app/pages/directoryservice/ldap/ldap.component.ts
Labels: backport-21.04

#5204 NAS-109550 / 12.0 / Hide "Export Key" option when encryption is passphrase
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-21.04

#5202 NAS-109051 - Added warnings for encrypted datasets when creating a replication task through form or wizard
  src/app/helptext/task-calendar/replication/replication-wizard.ts
  src/app/helptext/task-calendar/replication/replication.ts
  src/app/pages/common/entity/entity-form/entity-form.component.html
  src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
  src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts
  src/assets/styles/material-reduction.css
Labels: backport-21.04

#5212 NAS-108630 / 12.0 / Fixed legend keys for battery statistics reports
  src/app/pages/reportsdashboard/reports-utils.worker.ts
Labels: backport-21.04

#5206 NAS-109511 / 12.0 / Show dialog when smart has no results
  src/app/pages/storage/disks/smart-results/smart-results.component.ts
Labels: backport-21.04

#5197 NAS-109134 / 12.0 / Fix the year displayed in Display System Processes and the Shell / Nas 109134
  src/app/services/locale.service.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-21.04

#5218 NAS-109311 / 12.0 / OpenStack_Swift auth_version values should be numbers
  src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Labels: backport-21.04

#5221 NAS-109052 / 12.0 / Fixed case where idmap has a custom name
  src/app/pages/directoryservice/idmap-list/idmap-list.component.ts
Labels: backport-21.04

#5223 NAS-109582 / 12.0 / Added case for HttpErrorResponse error handling
  src/app/pages/system/advanced/advanced.component.ts
Labels: backport-21.04

#5194 NAS-109598 / 12.0 / Add snyk and update dependency packages
  .github/CODEOWNERS
  .snyk
  package.json
Labels: backport-21.04

#5230 NAS-109739 / 12.0 / Add snapshot name to keyprops.
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
  src/assets/styles/material-reduction.css
Labels: backport-21.04

#5237 NAS-109677 / 21.04 / Update repo info
  README-egret.md
  README.md
  package.json
Labels: backport-12.0

#5233 NAS-109548 / 12.0 / Use progress bar for snapshot multi delete
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
Labels: backport-21.04

#5246 NAS-109548 / 12.0 / Fix snapshot multidelete progressbar percent format
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
Labels: backport-21.04

#5283 NAS-109974 / 21.04 / Fix entity-empty text color on light themes
  src/app/pages/common/entity/entity-empty/entity-empty.component.scss
Labels: jira
