Repository truenas/webui, pull requests merged in 2021-02, with the labels that each got.

#5093 NAS-109087 / 21.02 / Use optimized query call for root datasets
  src/app/pages/dashboard/dashboard.component.ts
Labels: backport-12.0

#5096 NAS-109160 / 12.0 / Fix password not set form
  src/app/views/sessions/signin/signin.component.html
Labels: backport-20.12

#5097 NAS-109215 / 12.0 / Fix hide logic
  src/app/views/sessions/signin/signin.component.html
  src/app/views/sessions/signin/signin.component.scss
Labels: backport-20.12

#5103 NAS-109135 / 12.0 / Fix export key for encrypted datasets
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-21.02

#5140 NAS-108990 / 12.0 / Handled job response case when state is ABORTED for disk import
  src/app/pages/common/entity/entity-job/entity-job.component.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
Labels: backport-21.02

#5121 NAS-109078 / 12.0 / Properly display additionally licensed hardware
  src/app/pages/system/support/support.component.ts
Labels: backport-21.02, backported

#5106 NAS-109233 / 21.02 / Fix lack of whitespace in dialog box
  src/app/helptext/storage/volumes/manager/manager.ts
Labels: backport-12.0, jira

#5153 NAS-109379 / 12.0 / display disks inline
  src/app/core/components/widgets/widgetpool/widgetpool.component.css
Labels: backport-21.02

#5081 NAS-108918 / 12.0 / Removed incorrect tooltip from smb-form component
  src/app/helptext/sharing/smb/smb.ts
Labels: backport-21.02, backported

#5163 NAS-109490 / 12.0 / Add HA detection and update message
  src/app/pages/system/update/update.component.ts
Labels: backport-21.02
