Repository truenas/webui, pull requests merged in 2021-06, with the labels that each got.

#5521 NAS-110843 / 21.08 / NAS-110843: Remove some any's
  angular.json
  src/app/components/common/layouts/admin-layout/admin-layout.component.ts
  src/app/components/common/layouts/auth-layout/auth-layout.component.ts
  src/app/core/classes/display-object.ts
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/classes/layout-object.ts
  src/app/core/components/card/card.component.ts
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/app/core/services/animation.service.ts
  src/app/core/services/interaction-manager.service.ts
  src/app/pages/account/users/user-form/user-form.component.ts
  src/app/pages/applications/applications.component.html
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/common/confirm-dialog/confirm-dialog.component.ts
  src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
  src/app/pages/common/entity/utils.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-acme-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-edit.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
  src/app/pages/sharing/iscsi/associated-target/associated-target-form/associated-target-form.component.ts
  src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/alert/alert.component.ts
  src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/vm/vm-form/vm-form.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
  src/app/services/theme/theme.service.ts
  src/app/services/ws.service.ts
Labels: skip jira status

#5543 NAS-110919 / 21.08 / Fix broken storage page
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: skip jira status

#5546 NAS-110953 / 21.08 / Removing ports folder
  ports/freenas/freenas-webui/Makefile
  ports/freenas/freenas-webui/pkg-descr
  ports/freenas/node9/Makefile
  ports/freenas/node9/distinfo
  ports/freenas/node9/files/patch-deps_v8_src_arm_cpu-arm.cc
  ports/freenas/node9/files/patch-deps_v8_src_base_atomicops__internals__arm__gcc.h
  ports/freenas/node9/files/patch-deps_v8_src_base_platform_platform-freebsd.cc
  ports/freenas/node9/files/patch-deps_v8_src_log-utils.h
  ports/freenas/node9/files/patch-deps_v8_src_profiler_sampler.cc
  ports/freenas/node9/pkg-descr
  ports/freenas/node9/pkg-message
  ports/freenas/node9/pkg-plist
  ports/freenas/npm5/Makefile
  ports/freenas/npm5/distinfo
  ports/freenas/npm5/files/extra-patch-bug-178881
  ports/freenas/npm5/pkg-descr
  ports/freenas/npm5/pkg-plist
Labels: jira

#5554 NAS-110917 / None / Fix [object Object] in dropdown menu
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
Labels: backport-21.08

#5559 NAS-110988 / 21.08 / Enabling additional linter rules
  .eslintrc.js
  src/app/core/classes/common-utils.ts
  src/app/core/classes/theme-utils.ts
  src/app/core/services/animation.service.ts
  src/app/core/services/api.service.ts
  src/app/core/services/chart-data-utils.service.ts
  src/app/core/services/core.service.ts
  src/app/directives/common/app-accordion.directive.ts
  src/app/directives/common/sidenav-accordion.directive.ts
  src/app/helpers/dom.helper.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
  src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
  src/app/pages/common/entity/entity-toolbar/components/toolbar-slider/toolbar-slider.component.ts
  src/app/pages/credentials/backup-credentials/backup-credentials.component.ts
  src/app/pages/network/forms/configuration.component.ts
  src/app/pages/shell/shell.component.ts
  src/app/pages/storage/volumes/manager/disk/disk.component.ts
  src/app/pages/system/alert/alert.component.ts
  src/app/pages/system/alertservice/alert-service/alert-service.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/systemprocesses/system-processes.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/app/services/cloudcredential.service.ts
  src/app/services/route-parts/route-parts.service.ts
  src/app/services/storage.service.ts
  src/app/services/system-general.service.ts
  src/app/services/tooltips.service.ts
  src/app/services/ws.service.ts
  src/environments/environment.ts.skel
  src/test.ts
  src/typings.d.ts
Labels: jira

#5558 NAS-110827 / 21.08 / NAS-110827 - Max-len linting
  .eslintrc.js
  src/app/components/common/navigation/navigation.component.ts
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/classes/hardware/vdev-labels-svg.ts
  src/app/core/components/view/view.component.ts
  src/app/core/services/core.service.ts
  src/app/pages/applications/catalog/catalog.component.ts
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/system/update/manualupdate/manualupdate.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
  src/app/services/job.service.ts
Labels: skip jira status

#5550 NAS-110916 / None / NAS-110916 - Injection error when unlocking dataset
  src/app/pages/common/entity/entity.module.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
Labels: backport-21.08

#5612 NAS-110967 / None / Renaming some ACL interfaces and adding new ones
  src/app/components/common/topbar/topbar.component.html
  src/app/components/common/topbar/topbar.component.ts
  src/app/directives/common/common-directives.module.ts
  src/app/directives/common/font-size.directive.ts
  src/app/enums/acl-type.enum.ts
  src/app/enums/ca-digest-algorithm.enum.ts
  src/app/enums/ca-key-type.enum.ts
  src/app/enums/smart-power.mode.ts
  src/app/enums/true-command-status.enum.ts
  src/app/helptext/storage/volumes/datasets/dataset-acl.ts
  src/app/interfaces/acl.interface.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/interfaces/api-event-directory.interface.ts
  src/app/interfaces/boot-pool-state.interface.ts
  src/app/interfaces/certificate-authority.interface.ts
  src/app/interfaces/certificate.interface.ts
  src/app/interfaces/cloudsync-credential.interface.ts
  src/app/interfaces/cloudsync-provider.interface.ts
  src/app/interfaces/smart-test.interface.ts
  src/app/interfaces/storage.interface.ts
  src/app/interfaces/true-command-config.interface.ts
  src/app/interfaces/virtual-machine.interface.ts
  src/app/pages/applications/applications.service.ts
  src/app/pages/credentials/backup-credentials/backup-credentials.component.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/services/components/service-smart/service-smart.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/services/cloudcredential.service.ts
Labels: skip jira status

#5620 NAS-111170 / 21.08 / NAS-111170 - Improving type safety
  src/app/enums/ups-mode.enum.ts
  src/app/helptext/services/components/service-ups.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/interfaces/choices.interface.ts
  src/app/interfaces/dynamic-dns.interface.ts
  src/app/interfaces/ftp-config.interface.ts
  src/app/interfaces/iscsi.interface.ts
  src/app/interfaces/lldp-config.interface.ts
  src/app/interfaces/openvpn-client-config.interface.ts
  src/app/interfaces/rsync-config.interface.ts
  src/app/interfaces/s3-config.interface.ts
  src/app/interfaces/ups-config.interface.ts
  src/app/pages/applications/applications.service.ts
  src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
  src/app/pages/common/entity/entity-toolbar/components/toolbar-slider/toolbar-slider.component.html
  src/app/pages/common/entity/entity-toolbar/components/toolbar-slider/toolbar-slider.component.ts
  src/app/pages/data-protection/smart/smart-form/smart-form.component.ts
  src/app/pages/directoryservice/ldap/ldap.component.ts
  src/app/pages/network/forms/interfaces-form.component.ts
  src/app/pages/network/forms/staticroute-form.component.ts
  src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
  src/app/pages/services/components/service-nfs/service-nfs.component.ts
  src/app/pages/services/components/service-rsync/rsyncconfiguration/configure_rsync/configure_rsync.component.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
  src/app/pages/services/components/service-ups/service-ups.component.ts
  src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/system/advanced/console-form/console-form.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/services/iscsi.service.ts
  src/app/services/network.service.ts
  src/app/services/services.service.ts
  src/app/services/shell.service.ts
  src/app/services/system-general.service.ts
  src/app/services/vm.service.ts
Labels: skip jira status
