Repository truenas/webui, pull requests merged in 2021-05, with the labels that each got.

#5389 NAS-110331 / 21.06 / NAS-110331 - Guard to wait for translations to simplify translation code
  scripts/extract_strings.js
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/common/layouts/admin-layout/admin-layout.component.html
  src/app/components/common/layouts/admin-layout/admin-layout.component.ts
  src/app/components/common/layouts/auth-layout/auth-layout.component.ts
  src/app/components/common/topbar/topbar.component.html
  src/app/components/common/topbar/topbar.component.ts
  src/app/core/guards/translations-loaded.guard.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/general-settings/localization-form/localization-form.component.ts
  src/app/services/language.service.ts
  src/app/services/locale.service.ts
Labels: backport-12.0

#5405 NAS-110328 / 21.06 / NAS-110328: Refactoring confirm action in DialogService to simplify it
  src/app/interfaces/dialog.interface.ts
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/services/dialog.service.ts
Labels: backport-12.0

#5410 NAS-109476 / 12.0 / Fix Full Filesystem Replication tooltip
  src/app/helptext/task-calendar/replication/replication.ts
Labels: skip jira status

#5402 NAS-110478 / 21.06 / NAS-110478 - Check to make sure build worked correctly
  config/electron/webpack.electron.common.js
  config/electron/webpack.electron.dev.js
  config/electron/webpack.electron.prod.js
  config/electron/webpack.renderer.common.js
  config/electron/webpack.renderer.dev.js
  config/electron/webpack.renderer.prod.js
  config/empty.js
  config/head-config.common.js
  config/helpers.js
  config/html-elements-plugin/index.js
  config/modules/angular2-hmr-prod.js
  config/resource-override.js
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  package.json
  scripts/verify_build.js
  tsconfig.json
Labels: backport-12.0, skip jira status

#5413 NAS-110048 / 12.0 / NAS-110048 - Fix for translations taking too long to load
  src/app/core/guards/translations-loaded.guard.ts
  src/app/services/language.service.ts
Labels: skip jira status

#5448 NAS-110628 / None / NAS-110628: Adding return types 3
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.ts
  src/app/pages/applications/forms/chart-form.component.ts
  src/app/pages/applications/forms/chart-release-add.component.ts
  src/app/pages/applications/forms/chart-release-edit.component.ts
  src/app/pages/applications/forms/chart-wizard.component.ts
  src/app/pages/common/confirm-dialog/confirm-dialog.component.ts
  src/app/pages/credentials/backup-credentials/backup-credentials.component.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-edit.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-edit.component.ts
  src/app/pages/dashboard/dashboard-note-edit.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/network/forms/configuration.component.ts
  src/app/pages/plugins/available-plugins/available-plugins.component.ts
  src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
  src/app/pages/system/advanced/console-form/console-form.component.ts
  src/app/pages/system/advanced/cron/cron-form/cron-form.component.ts
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/views/others/config-reset/config-reset.component.ts
Labels: skip jira status

#5449 NAS-110628 / 21.06 / NAS-110628: Adding return types 4
  src/app/directives/common/equal-validator.directive.ts
  src/app/pages/account/groups/group-form/group-form.component.ts
  src/app/pages/account/groups/group-list/group-list.component.ts
  src/app/pages/common/entity/entity-form/classes/field-sets.ts
  src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.ts
  src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
  src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.ts
  src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.ts
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity-form/services/field-relation.service.ts
  src/app/pages/common/entity/entity-form/validators/forbidden-values-validation.ts
  src/app/pages/common/entity/entity-job/entity-job.component.ts
  src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
  src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
  src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.ts
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/common/entity/entity-table/entity-table.service.ts
  src/app/pages/common/entity/entity-task/entity-task.component.ts
  src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.service.ts
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts
  src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.ts
  src/app/pages/common/error-dialog/error-dialog.component.ts
  src/app/pages/directoryservice/idmap/idmap-form.component.ts
  src/app/pages/preferences/page/forms/general-preferences-form.component.ts
  src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts
  src/app/pages/system/general-settings/general-settings.component.ts
Labels: skip jira status

#5450 NAS-110628 / 21.06 / NAS-110628: Adding return types 5
  src/app/core/classes/display-object.ts
  src/app/core/classes/hardware/drivetray.ts
  src/app/core/components/display/display.component.ts
  src/app/core/services/disk-state.service.ts
  src/app/helpers/dom.helper.ts
  src/app/pages/applications/docker-images/docker-images.component.ts
  src/app/pages/common/entity/entity-card/entity-card.component.ts
  src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-form/entity-form-configuration.component.ts
  src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts
  src/app/pages/directoryservice/directoryservices.component.ts
  src/app/pages/directoryservice/idmap/idmap-list.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list-component.ts
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/group-quota-form/group-quota-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
  src/app/pages/system/email/email.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
  src/app/pages/vm/devices/device-add2/device-add.component.ts
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
  src/app/pages/vm/devices/device-list/device-list.component.ts
  src/app/services/dialog.service.ts
  src/app/services/encryption.service.ts
  src/app/services/idmap.service.ts
Labels: skip jira status

#5451 NAS-110628 / None / NAS-110628: Adding return types 6
  src/app/components/common/dual-list/models.ts
  src/app/core/classes/hardware/label-factory.ts
  src/app/core/components/widgets/widgetchart/widgetchart.component.ts
  src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.ts
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
  src/app/core/components/widgets/widgetnic/widgetnic.component.ts
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/app/pages/account/groups/members/members.component.ts
  src/app/pages/applications/forms/kubernetes-settings.component.ts
  src/app/pages/applications/pod-logs/pod-logs.component.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-form/validators/password-validation.ts
  src/app/pages/directoryservice/kerberoskeytabs/kerberoskeytabs-list.component.ts
  src/app/pages/directoryservice/kerberosrealms/kerberosrealms-list.component.ts
  src/app/pages/directoryservice/ldap/ldap.component.ts
  src/app/pages/plugins/plugin-add/plugin-add.component.ts
  src/app/pages/plugins/plugins.component.ts
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/user-quota-form/user-quota-form.component.ts
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/advanced/kernel-form/kernel-form.component.ts
  src/app/pages/system/general-settings/localization-form/localization-form.component.ts
  src/app/pages/system/kmip/kmip.component.ts
  src/app/pages/system/update/manualupdate/manualupdate.component.ts
  src/app/services/locale.service.ts
  src/app/services/modal.service.ts
  src/app/services/network.service.ts
Labels: skip jira status

#5452 NAS-110628 / None / NAS-110628: Adding return types 7
  src/app/components/common/dual-list/dual-list.component.ts
  src/app/core/classes/display-object.ts
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/components/display/display.component.ts
  src/app/core/services/core.service.ts
  src/app/pages/account/groups/group-form/group-form.component.ts
  src/app/pages/common/entity/entity-card/entity-card.component.ts
  src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.ts
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity-form/services/field-relation.service.ts
  src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
  src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.ts
  src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts
  src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
  src/app/pages/directoryservice/directoryservices.component.ts
  src/app/pages/directoryservice/idmap/idmap-form.component.ts
  src/app/pages/preferences/page/forms/general-preferences-form.component.ts
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
  src/app/pages/system/email/email.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
  src/app/services/dialog.service.ts
Labels: skip jira status

#5453 NAS-110628 / None / NAS-110628: Adding return types 8
  src/app/core/classes/hardware/vdev-labels-svg.ts
  src/app/core/components/viewchart/viewchart.component.ts
  src/app/core/components/viewchartbar/viewchartbar.component.ts
  src/app/core/components/viewchartdonut/viewchartdonut.component.ts
  src/app/core/components/viewchartgauge/viewchartgauge.component.ts
  src/app/core/components/viewchartline/viewchartline.component.ts
  src/app/core/components/viewcontroller/viewcontroller.component.ts
  src/app/pages/account/users/change-password/change-password.component.ts
  src/app/pages/account/users/user-form/user-form.component.ts
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/common/entity/utils.ts
  src/app/pages/credentials/certificates-dash/forms/ca-edit.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-edit.component.ts
  src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/user-quota-form/user-quota-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.ts
  src/app/pages/system/alert/alert.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/pages/system/tunable/tunable-list/tunable-list.component.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
  src/app/pages/vm/vm-form/vm-form.component.ts
  src/app/pages/vm/vm-list/vm-list.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
  src/app/services/locale.service.ts
  src/app/services/rest.service.ts
  src/app/services/validation.service.ts
  src/app/services/vm.service.ts
Labels: skip jira status

#5464 NAS-110628 / 21.06 / NAS-110628: Adding return types to functions 9
  src/app/core/classes/hardware/chassis-view.ts
  src/app/pages/account/groups/group-list/group-list.component.ts
  src/app/pages/applications/docker-images/docker-images.component.ts
  src/app/pages/applications/forms/chart-form.component.ts
  src/app/pages/applications/forms/chart-release-add.component.ts
  src/app/pages/applications/forms/chart-release-edit.component.ts
  src/app/pages/applications/forms/chart-wizard.component.ts
  src/app/pages/common/entity/entity-card/entity-card.component.ts
  src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/entity-form/entity-form.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/common/entity/entity-table/entity-table.service.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.service.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
  src/app/pages/directoryservice/idmap/idmap-list.component.ts
  src/app/pages/network/forms/configuration.component.ts
  src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
  src/app/pages/system/advanced/console-form/console-form.component.ts
  src/app/pages/system/advanced/cron/cron-form/cron-form.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/services/cloudcredential.service.ts
Labels: skip jira status

#5470 NAS-110628 / None / NAS-110628: Adding return types 11
  src/app/core/classes/layout-object.ts
  src/app/core/classes/theme-utils.ts
  src/app/core/services/interaction-manager.service.ts
  src/app/directives/common/sidenav-accordion.directive.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-form/validators/ip-validation.ts
  src/app/pages/credentials/backup-credentials/backup-credentials.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
  src/app/pages/data-protection/snapshot/snapshot-form/snapshot-form.component.ts
  src/app/pages/jails/jail-form/jail-form.component.ts
  src/app/pages/jails/jail-form/jail-form.service.ts
  src/app/pages/jails/jail-list/jail-list.component.ts
  src/app/pages/jails/jail-shell/jail-shell.component.ts
  src/app/pages/network/forms/interfaces-form.component.ts
  src/app/pages/network/forms/ipmi-form.component.ts
  src/app/pages/network/network.component.ts
  src/app/pages/reportsdashboard/reports.service.ts
  src/app/pages/reportsdashboard/reportsdashboard.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
  src/app/pages/shell/shell.component.ts
  src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/general-settings/support/proactive/proactive.component.ts
  src/app/services/shell.service.ts
  src/app/services/theme/theme.service.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: skip jira status

#5481 NAS-110735 / 21.06 / Fix advanced settings
  src/app/pages/system/advanced/advanced-settings.component.ts
Labels: jira

#5475 NAS-110628 / 21.06 / NAS-110628 - Adding return types 12
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
  src/app/pages/common/entity/entity-table/table-utils.worker.ts
  src/app/pages/data-protection/rsync/rsync-form/rsync-form.component.ts
  src/app/pages/data-protection/rsync/rsync-list/rsync-list.component.ts
  src/app/pages/data-protection/scrub/scrub-form/scrub-form.component.ts
  src/app/pages/data-protection/smart/smart-form/smart-form.component.ts
  src/app/pages/data-protection/smart/smart-list/smart-list.component.ts
  src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
  src/app/pages/network/forms/service-openvpn-server.component.ts
  src/app/pages/reportsdashboard/components/report/report.component.ts
  src/app/pages/reportsdashboard/components/reports-config/reports-config.component.ts
  src/app/pages/services/components/service-afp/service-afp.component.ts
  src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
  src/app/pages/services/components/service-nfs/service-nfs.component.ts
  src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
  src/app/pages/services/components/service-smb/service-smb.component.ts
  src/app/pages/services/components/service-snmp/service-snmp.component.ts
  src/app/pages/services/components/service-tftp/service-tftp.component.ts
  src/app/pages/services/components/service-ups/service-ups.component.ts
  src/app/pages/services/components/service-webdav/service-webdav.component.ts
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/app/pages/storage/disks/smart-results/smart-results.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/services/user.service.ts
Labels: skip jira status

#5476 NAS-110628 / None / NAS-110628: Adding return types 13
  src/app/core/classes/thread.ts
  src/app/pages/applications/applications.service.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/utils.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/directoryservice/kerberosrealms/kerberosrealms-list.component.ts
  src/app/pages/directoryservice/ldap/ldap.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
  src/app/pages/plugins/plugins.component.ts
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/reportsdashboard/reports-utils.worker.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/system/advanced/isolated-gpu-pcis/isolated-gpu-pcis-form.component.ts
  src/app/pages/system/advanced/kernel-form/kernel-form.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/general-settings/localization-form/localization-form.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/example-data.ts
  src/app/services/iscsi.service.ts
  src/app/services/jail.service.ts
  src/app/services/keychaincredential.services.ts
  src/app/services/network.service.ts
  src/app/services/replication.service.ts
  src/app/services/rest.service.ts
  src/app/services/services.service.ts
  src/app/services/storage.service.ts
  src/app/services/system-general.service.ts
  src/app/services/ws.service.ts
Labels: skip jira status

#5492 NAS-110761 / 21.06 / NAS-110761: Removing unused variables 1
  .eslintrc.js
  package.json
  src/app/components/common/breadcrumb/breadcrumb.component.ts
  src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.ts
  src/app/components/common/layouts/admin-layout/admin-layout.component.ts
  src/app/components/common/layouts/auth-layout/auth-layout.component.ts
  src/app/core/classes/display-object.ts
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/components/display/display.component.ts
  src/app/core/services/animation.service.ts
  src/app/core/services/api.service.ts
  src/app/core/services/base.service.ts
  src/app/core/services/chart-data-utils.service.ts
  src/app/core/services/core.service.ts
  src/app/core/services/disk-state.service.ts
  src/app/core/services/disk-temperature.service.ts
  src/app/core/services/stats.service.ts
  src/app/core/services/system-profile.service.ts
  src/app/helpers/dom.helper.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/account/users/change-password/change-password.component.ts
  src/app/pages/applications/chart-releases/chart-releases.component.html
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-edit.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/dashboard/dashboard-note-edit.component.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
  src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
  src/app/pages/network/forms/ipmi-form.component.ts
  src/app/pages/network/network.component.ts
  src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts
  src/app/pages/sharing/iscsi/associated-target/associated-target-form/associated-target-form.component.ts
  src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/system/alertservice/alert-service/alert-service.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/pages/vm/devices/device-add2/device-add.component.html
  src/app/pages/vm/devices/device-add2/device-add.component.ts
  src/app/pages/vm/devices/device-edit/device-edit.component.html
  src/app/pages/vm/devices/device-edit/device-edit.component.ts
  src/app/pages/vm/devices/device-list/device-list.component.ts
  src/app/services/dialog.service.ts
  yarn.lock
Labels: skip jira status

#5496 NAS-110778 / 21.06 / Downgrade pixi to 4.7 and remove pixi-projection dependency
  angular.json
  package.json
  src/app/core/classes/hardware/chassis-view.ts
  src/app/core/classes/hardware/drivetray.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  yarn.lock
Labels: jira

#5493 NAS-110761 / None / NAS-110761: Removing unused variables 2
  src/app/core/services/interaction-manager.service.ts
  src/app/pages/common/entity/entity-card/entity-card.component.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.ts
  src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.ts
  src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.ts
  src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
  src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
  src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.ts
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
  src/app/pages/common/entity/entity-form/components/form-task/form-task.component.html
  src/app/pages/common/entity/entity-form/components/form-task/form-task.component.ts
  src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
  src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
  src/app/pages/common/entity/entity-form/entity-form.component.ts
  src/app/pages/common/entity/entity-form/services/entity-form.service.ts
  src/app/pages/common/entity/entity-form/services/field-relation.service.ts
  src/app/pages/common/entity/entity-form/validators/forbidden-values-validation.ts
  src/app/pages/common/entity/entity-form/validators/ip-validation.ts
  src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
  src/app/pages/common/entity/entity-table/entity-table.component.ts
  src/app/pages/common/entity/entity-table/entity-table.service.ts
  src/app/pages/common/entity/entity-task/entity-task.component.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
  src/app/pages/common/entity/entity-tree-table/entity-tree-table.service.ts
  src/app/pages/common/error-dialog/error-dialog.component.ts
  src/app/pages/jails/jail-form/jail-form.component.ts
  src/app/pages/jails/jail-wizard/jail-wizard.component.ts
  src/app/pages/network/forms/configuration.component.ts
  src/app/pages/network/forms/interfaces-form.component.ts
  src/app/pages/network/forms/ipmi-form.component.ts
  src/app/pages/network/forms/staticroute-form.component.ts
  src/app/pages/plugins/plugin-add/plugin-add.component.ts
  src/app/pages/preferences/page/forms/general-preferences-form.component.ts
  src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
  src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-port/fibre-channel-port.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
  src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/group-quota-form/group-quota-form.component.ts
  src/app/pages/system/email/email.component.ts
  src/app/pages/system/failover/failover.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/services/encryption.service.ts
  src/app/views/others/failover/failover.component.ts
Labels: skip jira status

#5495 NAS-110761 / None / NAS-110761: Removing unused variables 3
  src/app/components/common/dialog/task-manager/task-manager.component.ts
  src/app/core/classes/hardware/vdev-labels-svg.ts
  src/app/core/classes/system-profiler.ts
  src/app/core/classes/theme-utils.ts
  src/app/core/classes/thread.ts
  src/app/core/components/viewchart/viewchart.component.ts
  src/app/core/components/viewchartbar/viewchartbar.component.ts
  src/app/core/components/viewchartgauge/viewchartgauge.component.ts
  src/app/core/components/viewchartline/viewchartline.component.ts
  src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.ts
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
  src/app/core/components/widgets/widgetnic/widgetnic.component.ts
  src/app/core/components/widgets/widgetpool/widgetpool.component.ts
  src/app/core/guards/translations-loaded.guard.ts
  src/app/core/services/chart-data-utils.service.ts
  src/app/core/services/system-profile.service.ts
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/pages/common/entity/entity-table/table-utils.worker.ts
  src/app/pages/common/entity/table/table.service.ts
  src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
  src/app/pages/storage/VMware-snapshot/VMware-snapshot-list/VMware-snapshot-list.component.ts
  src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/user-quota-form/user-quota-form.component.ts
  src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
  src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/tunable/tunable-list/tunable-list.component.ts
  src/app/pages/system/two-factor/two-factor.component.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
  src/app/pages/systemprocesses/system-processes.component.ts
  src/app/pages/vm/vm-form/vm-form.component.ts
  src/app/pages/vm/vm-list/vm-list.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.ts
  src/app/services/theme/theme.service.ts
  src/app/services/tour.service.ts
  src/app/services/ws.service.ts
Labels: skip jira status
