Repository truenas/webui, pull requests merged in 2021-08, with the labels that each got.

#5731 NAS-111668 / 21.08 / Fix free space on storage widget
  src/app/core/components/widgets/widget-storage/widget-storage.component.ts
Labels: jira

#5747 NAS-111431 / 12.0 / Enclosures should listen for global resilver events
  src/app/components/common/topbar/topbar.component.ts
  src/app/core/services/disk-state.service.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
Labels: backport-21.08

#5741 NAS-111466 / 21.08 / NAS-111466 - View permissions sidebar tests
  package.json
  src/app/core/classes/icu-missing-translation-handler.ts
  src/app/core/testing/classes/fake-translate.service.ts
  src/app/core/testing/classes/mock-websocket.service.ts
  src/app/core/testing/interfaces/mock-websocket-responses.interface.ts
  src/app/core/testing/utils/mock-websocket.utils.ts
  src/app/pages/storage/volumes/permissions/components/permissions-item/permissions-item.component.spec.ts
  src/app/pages/storage/volumes/permissions/components/view-posix-permissions/posix-permissions.component.spec.ts
  src/app/pages/storage/volumes/permissions/components/view-trivial-permissions/trivial-permissions.component.spec.ts
  src/app/pages/storage/volumes/permissions/containers/permissions-sidebar/permissions-sidebar.component.spec.ts
  src/app/pages/storage/volumes/permissions/utils/get-ace-who-string.utils.spec.ts
  src/app/pages/storage/volumes/permissions/utils/permissions-to-description.utils.spec.ts
  src/app/pages/storage/volumes/permissions/utils/posix-ace-to-permission-item.utils.spec.ts
  src/app/pages/storage/volumes/permissions/utils/posix-ace-to-permission-item.utils.ts
  src/setup-jest.ts
  yarn.lock
Labels: skip jira status

#5763 NAS-111828 / 21.08 / Fix regressions on network chart
  src/app/core/components/widgets/widget-network/widget-network.component.html
  src/app/core/components/widgets/widget-network/widget-network.component.scss
  src/app/core/components/widgets/widget-network/widget-network.component.ts
Labels: jira

#5766 NAS-111832 / 21.08 / Ban ViewEncapsulation.None
  .eslintrc.js
  src/app/interfaces/user.interface.ts
  src/app/pages/applications/applications.component.ts
  src/app/pages/applications/dialogs/catalog-summary/catalog-summary-dialog.component.ts
  src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.ts
  src/app/pages/applications/dialogs/manage-catalog-summary/manage-catalog-summary-dialog.component.ts
  src/app/pages/applications/pod-logs/pod-logs.component.ts
  src/app/pages/applications/pod-shell/pod-shell.component.ts
  src/app/pages/common/entity/entity-toolbar/components/toolbar-input/toolbar-input.component.ts
  src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.ts
  src/app/pages/shell/shell.component.ts
  src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts
  src/assets/i18n/zh-hans.json
Labels: jira

#5789 NAS-111922 / 21.10 / Fix displaying percent value
  src/app/components/common/dialog/jobs-manager/components/job-item/job-item.component.html
  src/assets/i18n/zh-hans.json
Labels: jira

#5800 NAS-111940 / 21.08-BETA.1 / NAS-111940: Apply Permissions Recursively checkbox is not getting che…
  src/app/pages/storage/volumes/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts
Labels: backport-21.10

#5805 NAS-111877 / 21.10 / NAS-111877: Closing loader after navigating to Rsync Module form.
  src/app/pages/common/entity/entity-form/entity-form.component.ts
Labels: backport-21.08
