Repository truenas/webui, pull requests merged in 2021-04, with the labels that each got.

#5300 NAS-110058 / 21.04 / Cleanup subscriptions to modalService.refreshTable$
  src/app/pages/account/groups/group-list/group-list.component.ts
  src/app/pages/account/users/user-list/user-list.component.ts
  src/app/pages/applications/applications.component.ts
  src/app/pages/applications/docker-images/docker-images.component.ts
  src/app/pages/applications/manage-catalogs/manage-catalogs.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Labels: backport-12.0

#5302 NAS-109799 / 12.0 / Allow translate labels for ACL
  src/app/helptext/storage/volumes/datasets/dataset-acl.ts
Labels: backport-21.04

#5279 NAS-109689 / 12.0 / Add warning message for Log vdev
  src/app/helptext/storage/volumes/manager/manager.ts
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/manager.component.ts
Labels: backport-21.04

#5270 NAS-109860 / 12.0 / Fix "Continue" button on password dialog
  src/app/pages/common/password-dialog/password-dialog.component.html
  src/app/pages/common/password-dialog/password-dialog.component.ts
Labels: backport-21.04

#5258 NAS-108293 / 12.0 / Show slot number in disk view. Make sure disk details are cleared
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
Labels: backport-21.04

#5305 NAS-109672 / 12.0 / Scheduler preview not handling daylight savings time correctly
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
  src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
Labels: backport-21.04

#5188 NAS-109450 / 12.0 / Enclosure UI and disk page should listen for disk.query events
  src/app/core/classes/system-profiler.ts
  src/app/core/services/disk-state.service.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.html
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
  src/app/services/ws.service.ts
Labels: backport-21.04

#5325 NAS-110054 / 12.0 / Install Husky and eslint
  .eslintrc.js
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .vscode/settings.json
  angular.json
  config/webpack.dev.js
  config/webpack.prod.js
  e2e/app.e2e-spec.ts
  e2e/app.po.ts
  e2e/tsconfig.e2e.json
  package.json
  src/app/pages/services/components/service-tftp/service-tftp.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/services/rest.service.ts
  tslint.json
  yarn.lock
Labels: backport-21.04

#5318 NAS-109971 / 12.0 / Fix replication error inconsistent display
  src/app/pages/common/error-dialog/error-dialog.component.html
  src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts
  src/assets/styles/themes/ix-blue.scss
Labels: backport-21.04

#5343 Split docker builts out into two seperate workflows, add conditional
  .github/workflows/docker_external.yml
  .github/workflows/docker_internal.yml
Labels: in progress

#5336 NAS-109664 / 12.0 / Use global service for disk.query events
  src/app/core/services/disk-temperature.service.ts
  src/app/core/services/stats.service.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
  yarn.lock
Labels: backport-21.04

#5360 NAS-110289 / 21.06 / Use absolute path for imports in VSCode
  .vscode/settings.json
Labels: backport-12.0

#5368 NAS-110195 / None / NAS-110195 - Preparing for --no-implicit-any. Season Finale
  package.json
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-form/components/form-array/form-array.component.ts
  src/app/pages/common/entity/entity-table/table-utils.worker.ts
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/reportsdashboard/reports-utils.worker.ts
  src/app/types/dygraphs.d.ts
  tsconfig.json
  yarn.lock
Labels: skip jira status

#5364 NAS-110195 / None / NAS-110195 - Preparing for --no-implicit-any. Part 10
  package.json
  src/app/core/classes/hardware/vdev-labels-svg.ts
  src/app/core/classes/system-profiler.ts
  src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
  src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
  src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
  src/app/pages/common/entity/entity-form/components/form-array/form-array.component.ts
  src/app/pages/common/entity/entity-table/table-utils.worker.ts
  src/app/pages/common/entity/utils.ts
  src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
  src/app/pages/reportsdashboard/reports-utils.worker.ts
  src/app/pages/system/alert/alert.component.ts
  src/app/pages/system/alertservice/alert-service/alert-service.component.ts
  src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
  src/app/pages/system/email/email.component.ts
  src/app/pages/system/failover/failover.component.ts
  src/app/pages/system/general-settings/general-settings.component.ts
  src/app/pages/system/general-settings/gui-form/gui-form.component.ts
  src/app/pages/system/general-settings/localization-form/localization-form.component.ts
  src/app/pages/system/general-settings/support/proactive/proactive.component.ts
  src/app/pages/system/general-settings/support/support.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/system/viewenclosure/view-enclosure.component.ts
  src/app/pages/vm/devices/device-list/device-list.component.ts
  src/app/pages/vm/vm-list/vm-list.component.ts
  src/app/types/dygraphs.d.ts
  tsconfig.json
  yarn.lock
Labels: skip jira status

#5321 NAS-109689 / 21.06 / Add warning message for Log vdev (by denysbutenko)
  src/app/helptext/storage/volumes/manager/manager.ts
  src/app/pages/storage/volumes/manager/manager.component.css
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.html
Labels: backport-12.0

#5285 NAS-109993 / 21.06 / Fix spacing and border color on dark themes
  src/app/components/common/dual-list/dual-list.component.css
  src/app/pages/account/groups/members/members.component.css
Labels: backport-12.0, jira

#5326 NAS-110134 / 12.0 / Link to enclosure page from product image on dashboard
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
  src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
  src/app/pages/dashboard/dashboard.html
Labels: backport-21.06

#5373 NAS-110247 / 12.0 / Added field removed by PR# 3619
  src/app/helptext/services/components/service-smart.ts
  src/app/pages/services/components/service-smart/service-smart.component.ts
Labels: backport-21.06
