Repository truenas/webui, pull requests merged in 2022-01, with the labels that each got.

#6254 NAS-114028 / 13.0 / Added the new field
  src/app/helptext/services/components/service-s3.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
Labels: backport-12.0

#6266 NAS-112371 / 13.0 / Fixed wrong text
  src/app/helptext/storage/volumes/download-key.ts
  src/app/helptext/storage/volumes/manager/manager.ts
Labels: backport-12.0

#6269 NAS-114137 / 13.0 / Added new field
  src/app/helptext/services/components/service-s3.ts
  src/app/pages/services/components/service-s3/service-s3.component.ts
Labels: backport-12.0

#6285 NAS-114052 / 13.0 / Fixed checkbox clicks by adding unique ids
  src/app/pages/common/entity/entity-table/entity-table.component.html
Labels: backport-12.0

#6291 NAS-112307 / 22.02 / NAS-112307: Fix CPU Reports in Dashboard broken, when using a proxy host
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/reports-dashboard/reports.service.ts
Labels: backport-12.0

#6296 NAS-114297 / 12.0 / NAS-114297: Add link to docs from Update page
  src/app/helptext/system/update.ts
  src/app/pages/system/update/update.component.css
  src/app/pages/system/update/update.component.html
  src/app/pages/system/update/update.component.ts
Labels: backport-22.02

#6297 NAS-114329 / None / NAS-114329: Reducing usages of ApiService
  src/app/interfaces/events/enclosure-events.interface.ts
  src/app/interfaces/events/index.ts
  src/app/interfaces/events/nic-info-event.interface.ts
  src/app/interfaces/events/reporting-graphs-event.interface.ts
  src/app/interfaces/events/sensor-data-event.interface.ts
  src/app/interfaces/events/update-checked-event.interface.ts
  src/app/interfaces/events/user-data-event.interface.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.ts
  src/app/services/api.service.ts
Labels: skip jira status

#6326 NAS-114284 / None / NAS-114284: Replace simple instances of == with ===
  .gitignore
  src/app/components/common/topbar/topbar.component.ts
  src/app/core/classes/theme-utils/theme-utils.ts
  src/app/modules/charts/components/view-chart-line/view-chart-line.component.ts
  src/app/modules/charts/components/view-chart/view-chart.component.ts
  src/app/modules/entity/entity-form/components/form-toggle-button/form-toggle-button.component.ts
  src/app/modules/entity/entity-table/table-utils.worker.ts
  src/app/modules/entity/entity-tree-table/entity-tree-table.service.ts
  src/app/modules/entity/entity-wizard/components/wizard-summary/wizard-summary.component.ts
  src/app/modules/terminal/terminal.component.ts
  src/app/pages/applications/manage-catalogs/manage-catalogs.component.ts
  src/app/pages/applications/pod-logs/pod-logs.component.ts
  src/app/pages/dashboard/components/widget-controller/widget-controller.component.ts
  src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
  src/app/pages/dashboard/components/widget-help/widget-help.component.ts
  src/app/pages/dashboard/components/widget-memory/widget-memory.component.ts
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/dashboard/components/widget/widget.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/data-protection/scrub/scrub-form/scrub-form.component.ts
  src/app/pages/data-protection/snapshot/snapshot-form/snapshot-form.component.ts
  src/app/pages/jobs/jobs-list/jobs-list.component.ts
  src/app/pages/preferences/page/preferences.component.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
  src/app/pages/reports-dashboard/reports-utils.worker.ts
  src/app/pages/reports-dashboard/reports.service.ts
  src/app/pages/services/services.component.ts
Labels: skip jira status

#6343 NAS-114284 / None / NAS-114284: replace simple instances of == with ===
  src/app/modules/entity/entity-form/components/form-explorer/form-explorer.component.ts
  src/app/modules/entity/entity-form/entity-form.component.ts
  src/app/modules/entity/entity-form/validators/forbidden-values-validation.ts
  src/app/modules/entity/entity-form/validators/ip-validation.ts
  src/app/modules/entity/entity-form/validators/regex-validation.ts
  src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.ts
  src/app/modules/ix-forms/services/ix-validators.service.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
  src/app/services/theme/theme.service.ts
Labels: skip jira status

#6336 NAS-114284 / None / NAS-114284: Replace simple instances of == with ===
  .gitignore
  src/app/core/classes/theme-utils/theme-utils.ts
  src/app/modules/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/modules/entity/entity-form/entity-form.component.ts
  src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.ts
  src/app/modules/entity/entity-tree-table/entity-tree-table.service.ts
  src/app/modules/entity/entity-wizard/components/wizard-summary/wizard-summary.component.ts
  src/app/pages/applications/applications.component.ts
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.ts
  src/app/pages/directory-service/components/ldap/ldap.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/storage/vmware-snapshot/vmware-snapshot-list/vmware-snapshot-list.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/advanced/advanced-settings.component.ts
  src/app/pages/system/view-enclosure/classes/system-profiler.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/app/services/system-profile.service.ts
  src/app/services/theme/theme.service.ts
  src/app/services/ws.service.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: skip jira status

#6347 NAS-114284 / None / NAS-114284: Replace simple instances of == with ===
  src/app/app.component.ts
  src/app/core/classes/theme-utils/theme-utils.ts
  src/app/modules/charts/components/view-chart/view-chart.component.ts
  src/app/modules/entity/entity-empty/entity-empty.component.ts
  src/app/modules/entity/entity-form/components/form-explorer/form-explorer.component.ts
  src/app/modules/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
  src/app/modules/entity/entity-form/services/entity-form.service.ts
  src/app/modules/entity/entity-form/validators/forbidden-values-validation.ts
  src/app/modules/entity/entity-form/validators/ip-validation.ts
  src/app/modules/entity/entity-form/validators/regex-validation.ts
  src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.ts
  src/app/modules/entity/entity-table/table-utils.worker.ts
  src/app/modules/ix-forms/services/ix-validators.service.ts
  src/app/pages/applications/applications.component.ts
  src/app/pages/applications/catalog/catalog.component.ts
  src/app/pages/applications/chart-releases/chart-releases.component.ts
  src/app/pages/applications/forms/chart-form.component.ts
  src/app/pages/applications/forms/chart-wizard.component.ts
  src/app/pages/applications/manage-catalogs/manage-catalogs.component.ts
  src/app/pages/credentials/backup-credentials/backup-credentials.component.ts
  src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/acmedns-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/dashboard/components/dashboard-form/dashboard-form.component.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/directory-service/directory-services.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/services/components/service-ftp/service-ftp.component.ts
  src/app/pages/services/services.component.ts
  src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
  src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-port/fibre-channel-port.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.ts
  src/app/pages/vm/devices/device-add/device-add.component.ts
  src/app/services/theme/theme.service.ts
  src/app/services/ws.service.ts
Labels: skip jira status
