Repository truenas/webui, pull requests merged in 2022-06, with the labels that each got.

#6747 NAS-116552 / 22.12 / Fix translations
  src/assets/i18n/es-ar.json
Labels: jira

#6753 NAS-115796 / 22.12 / NAS-115796: Deleting 'textLimiter' attribute
  src/app/pages/applications/catalog/catalog.component.html
Labels: backport-22.02.2

#6756 NAS-116609 / 22.02.2 / add proper strings so enclosure mapping works
  src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks-mini.component.ts
Labels: backport-22.12

#6806 NAS-116768 / 22.12 / Update dataset properties
  src/app/interfaces/dataset.interface.ts
  src/assets/i18n/fr.json
Labels: jira

#6823 NAS-116871 / 22.12 / Toggle tree nodes recursively on alt+click
  src/app/modules/ix-tree/directives/ix-tree-node-toggle.directive.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.html
Labels: jira
