Repository truenas/webui, pull requests merged in 2022-12, with the labels that each got.

#7404 NAS-119210 / 23.10 / It's truenas.com, not truenas.org
  src/app/pages/system/email/email.component.spec.ts
  src/app/pages/system/email/email.component.ts
Labels: backport-22.12.1, backport-22.12

#7397 NAS-119125 / 23.10 / Add support for external share paths
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-22.12.1

#7415 NAS-119205 / 23.10 / VM UI not accessible after VM creation
  src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.scss
  src/app/modules/entity/entity-table/entity-table.component.ts
Labels: backport-22.12.1, backport-22.12

#7411 NAS-119191 / 23.10 / Fix breadcrumb url
  src/app/modules/page-header/breadcrumb/breadcrumb.component.html
Labels: backport-22.12.1, backport-22.12

#7421 NAS-119212 / 23.10 / Do not show "Checking HA status" on single node systems
  src/app/views/sessions/signin/signin.component.html
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-22.12.1, backport-22.12

#7439 NAS-118870 / 23.10 / Update `Name` field after first folder click
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backported

#7448 NAS-119297 / 23.10 / Enabling no-interpolation-in-attributes 1
  src/app/modules/charts/components/view-chart-gauge/view-chart-gauge.component.html
  src/app/modules/common/dialog/confirm-dialog/confirm-dialog.component.html
  src/app/modules/common/dialog/directory-services-monitor/directory-services-monitor.component.html
  src/app/modules/common/dialog/redirect-dialog/redirect-dialog.component.html
  src/app/modules/entity/entity-empty/entity-empty.component.html
  src/app/modules/entity/entity-form/components/form-array/form-array.component.html
  src/app/modules/entity/entity-form/components/form-button/form-button.component.html
  src/app/modules/entity/entity-form/components/form-checkbox/form-checkbox.component.html
  src/app/modules/entity/entity-form/components/form-chip/form-chip.component.html
  src/app/modules/entity/entity-form/components/form-colorpicker/form-colorpicker.component.html
  src/app/modules/entity/entity-form/components/form-combobox/form-combobox.component.html
  src/app/modules/entity/entity-form/components/form-datepicker/form-datepicker.component.html
  src/app/modules/entity/entity-form/components/form-explorer/form-explorer.component.html
  src/app/modules/entity/entity-form/components/form-input/form-input.component.html
  src/app/modules/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html
  src/app/modules/entity/entity-form/components/form-list/form-list.component.html
  src/app/modules/entity/entity-form/components/form-permissions/form-permissions.component.html
  src/app/modules/entity/entity-form/components/form-radio/form-radio.component.html
  src/app/modules/entity/entity-form/components/form-select/form-select.component.html
  src/app/modules/entity/entity-form/components/form-slider/form-slider.component.html
  src/app/modules/entity/entity-form/components/form-task/form-task.component.html
  src/app/modules/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
  src/app/modules/entity/entity-form/components/form-textarea/form-textarea.component.html
  src/app/modules/entity/entity-form/components/form-toggle-button/form-toggle-button.component.html
  src/app/modules/entity/entity-form/components/form-upload/form-upload.component.html
  src/app/modules/entity/entity-form/entity-form.component.html
  src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
  src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
  src/app/modules/entity/entity-table/entity-table.component.html
  src/app/modules/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html
  src/app/modules/entity/entity-wizard/entity-wizard.component.html
  src/app/modules/entity/table/expandable-table/expandable-table.component.html
  src/app/modules/entity/table/table.component.html
  src/app/modules/ix-tables/components/ix-empty-row/ix-empty-row.component.html
  src/app/modules/layout/components/navigation/navigation.component.html
  src/app/modules/page-header/breadcrumb/breadcrumb.component.html
  src/app/modules/tooltip/tooltip.component.html
  src/app/modules/truecommand/components/truecommand-connect-modal/truecommand-connect-modal.component.html
  src/app/pages/applications/catalog/catalog.component.html
  src/app/pages/applications/chart-releases/chart-releases.component.html
  src/app/pages/applications/dialogs/catalog-summary/catalog-summary-dialog.component.html
  src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.html
  src/app/pages/applications/dialogs/manage-catalog-summary/manage-catalog-summary-dialog.component.html
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/widget-network/widget-network.component.html
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.html
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.html
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/datasets/modules/encryption/components/unlock-dialog/unlock-dialog.component.html
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/services/components/service-rsync/service-rsync.component.html
  src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list.component.html
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/storage/components/manager/manager.component.html
  src/app/pages/storage/components/manager/vdev/vdev.component.html
  src/app/pages/system/general-settings/support/support.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
Labels: skip jira status

#7454 NAS-119297 / 23.10 / Enable no-interpolation-in-attributes
  src/app/modules/alerts/components/alert/alert.component.html
  src/app/modules/common/dual-list/dual-list.component.html
  src/app/modules/entity/entity-empty/entity-empty.component.html
  src/app/modules/entity/entity-form/components/form-checkbox/form-checkbox.component.html
  src/app/modules/entity/entity-form/components/form-input/form-input.component.html
  src/app/modules/entity/entity-form/components/form-list/form-list.component.html
  src/app/modules/entity/entity-form/components/form-radio/form-radio.component.html
  src/app/modules/entity/entity-form/components/form-select/form-select.component.html
  src/app/modules/entity/entity-form/components/form-selection-list/form-selection-list.component.html
  src/app/modules/entity/entity-form/entity-form.component.html
  src/app/modules/entity/entity-form/entity-form.component.ts
  src/app/modules/entity/entity-table/entity-row-details/entity-row-details.component.html
  src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.html
  src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
  src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
  src/app/modules/entity/entity-table/entity-table.component.html
  src/app/modules/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html
  src/app/modules/entity/entity-wizard/entity-wizard.component.html
  src/app/modules/entity/entity-wizard/entity-wizard.component.ts
  src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.html
  src/app/modules/ix-tables/components/ix-empty-row/ix-empty-row.component.html
  src/app/modules/layout/components/admin-layout/admin-layout.component.html
  src/app/modules/layout/components/modal/modal.component.html
  src/app/modules/layout/components/topbar/topbar.component.html
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.html
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
  src/app/pages/datasets/components/dataset-node/dataset-encryption-cell/dataset-encryption-cell.component.html
  src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-port/fibre-channel-port.component.html
  src/app/pages/storage/components/manager/manager.component.html
  src/app/pages/storage/components/manager/vdev/vdev.component.html
  src/app/pages/system/general-settings/general-settings.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.html
Labels: skip jira status

#7251 AUTO-289 / Changed LDAP UI test to verify it still work after failover
  tests/bdd/conftest.py
  tests/bdd/ha-bhyve02/test_NAS_T0932.py
  tests/bdd/ha-bhyve02/test_NAS_T0933.py
  tests/bdd/ha-bhyve02/test_NAS_T0939.py
  tests/bdd/ha-bhyve02/test_NAS_T0940.py
  tests/bdd/ha-bhyve02/test_NAS_T1117.py
  tests/bdd/ha-bhyve02/xpaths.py
Labels: Work in Progress

#7476 NAS-119236 / 22.12.1 / Fixed create ACME certificate
  src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.spec.ts
  src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.ts
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
Labels: backport-23.10

#7475 NAS-119438 / 22.12.1 / Showing errors in rsync form
  src/app/modules/ix-forms/services/form-error-handler.service.ts
  src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
Labels: backport-23.10

#7474 NAS-119437 / 23.10 / Use `ErrnoMixin.ENOTAUTHENTICATED` to redirect to the login page, not…
  src/app/services/ws.service.ts
Labels: backport-22.12.1

#7492 PD-18: (CORE 13.0) Fix typo in SMB Hosts Allow and Hosts Deny helptext
  src/app/helptext/sharing/smb/smb.ts
Labels: Help Text

#7508 NAS-119579 / 23.10 / Unnecessary scrollbar in dataset header
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
Labels: backport-22.12.1

#7483 NAS-119049 / 22.12.1 / Nas-119049 - Fixed LDAP slide-in is sometimes blank
  src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
Labels: backport-23.10

#7511 NAS-119385 / 23.10 / Adding support for tooltips in selects.
  src/app/interfaces/option.interface.ts
  src/app/modules/ix-forms/components/ix-select/ix-select.component.html
  src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
  src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
  src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
  src/app/modules/tooltip/tooltip.component.html
Labels: skip jira status

#7513 NAS-119607 / 23.10 / Storage -> Disks if one disk details toggled, all the disks are toggled as well
  src/app/modules/entity/entity-table/entity-table.component.html
  src/app/modules/entity/entity-table/entity-table.component.ts
Labels: backport-22.12.1
