Repository truenas/webui, pull requests merged in 2022-10, with the labels that each got.

#7177 NAS-117028 / 22.12 / Nas 117028 - Fixed errored out pools on new storage pages
  src/app/enums/vdev-status.enum.ts
  src/app/pages/storage/components/dashboard-pool/disk-health-card/disk-health-card.component.ts
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
Labels: backport-22.12-BETA.2

#7171 NAS-118471 / 22.12 / delete odd label
  src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.html
  src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.spec.ts
  src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html
Labels: backport-22.12-BETA.2

#7172 NAS-118443 / 22.12 / Filter disks when 'disk' or 'device' is null
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
Labels: backport-22.12-BETA.2

#7162 NAS-118423 / 22.12 / Better error handling for Reports
  src/app/modules/entity/entity-empty/entity-empty.component.html
  src/app/modules/entity/entity-empty/entity-empty.component.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
Labels: backport-22.12-BETA.2

#7198 NAS-118454 / 22.12-BETA.2 / Go To ACL Manager After Adding SMB Type Dataset of an SMB Dataset Goes to Main Dashboard Not ACL Manager
  src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
  src/app/modules/layout/components/breadcrumb/breadcrumb.component.html
  src/app/modules/layout/components/breadcrumb/breadcrumb.component.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/datasets/modules/permissions/components/acl-editor-list/acl-editor-list.component.html
  src/app/pages/datasets/modules/permissions/components/acl-editor-list/acl-editor-list.component.ts
  src/app/pages/datasets/modules/permissions/components/view-nfs-permissions/view-nfs-permissions.component.ts
  src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.html
  src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts
  src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.ts
  src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.ts
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/app/services/route-parts/route-parts.service.ts
Labels: backport-22.12

#7216 NAS-118443 / 22.12 / display removed disks in Storage Devices; restore 'Replace' menu item for every disk shown
  src/app/pages/storage/modules/devices/components/devices/devices.component.html
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
  src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.html
  src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.scss
  src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.spec.ts
  src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.ts
  src/app/pages/storage/modules/devices/devices.module.ts
Labels: backport-22.12-BETA.2

#7224 NAS-118465 / 22.12 / Fixed config upload job progress presentation
  src/app/core/testing/utils/mock-entity-job-component-ref.utils.ts
  src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.spec.ts
  src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.ts
Labels: backport-22.12-BETA.1, backport-22.12-BETA.2

#7209 NAS-118505 / 13.0 / Added r50bm
  src/app/core/classes/hardware/r50bm.ts
  src/app/core/classes/system-profiler.ts
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
  src/assets/images/hardware/r50/r50bm_rear.png
Labels: backport-20.12, backport-22.02

#7255 NAS-115669 / 22.12 / After upgrade the Standby controller card didn't update until Screen refresh/relog in
  src/app/enums/ha-status-text.enum.ts
  src/app/interfaces/events/ha-status-event.interface.ts
  src/app/modules/layout/components/topbar/topbar.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/store/system-info/system-info.effects.ts
  src/assets/i18n/uk.json
Labels: backport-13.0
