Repository truenas/webui, pull requests merged in 2022-05, with the labels that each got.

#6655 NAS-115713 / 22.12 / NAS-115713: New api endpoint to be used for recordsize choices for webUI
  src/app/enums/dataset.enum.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/vm/vm.module.ts
Labels: skip jira status

#6664 NAS-116057 / 13.0 / NAS-116057: Fix IPMI light
  src/app/pages/common/select-dialog/select-dialog.component.html
Labels: skip jira status

#6675 NAS-115951 / Add linter for component selectors
  .eslintrc.js
  src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
  src/app/pages/credentials/certificates-dash/forms/acmedns-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
  src/app/pages/dashboard/components/dashboard-form/dashboard-form.component.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
  src/app/pages/dashboard/components/widget-help/widget-help.component.ts
  src/app/pages/dashboard/components/widget-memory/widget-memory.component.ts
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.ts
  src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.ts
  src/app/pages/directory-service/components/idmap/idmap-form.component.ts
  src/app/pages/directory-service/components/idmap/idmap-list.component.ts
  src/app/pages/directory-service/directory-services.component.ts
  src/app/pages/jobs/components/job-logs-sidebar/job-logs-sidebar.component.ts
  src/app/pages/jobs/jobs-list/jobs-list.component.html
  src/app/pages/network/components/forms/ipmi-form.component.ts
  src/app/pages/network/network.component.ts
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
  src/app/pages/services/components/service-smb/service-smb.component.ts
  src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/sharing/iscsi/iscsi.component.ts
  src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
  src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
  src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
  src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts
  src/app/pages/shell/shell.component.ts
  src/app/pages/storage/disks/disk-bulk-edit/disk-bulk-edit.component.ts
  src/app/pages/storage/disks/disk-form/disk-form.component.ts
  src/app/pages/storage/disks/disk-list/disk-list.component.ts
  src/app/pages/storage/disks/smart-results/smart-results.component.ts
  src/app/pages/storage/import-disk/import-disk.component.ts
  src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
  src/app/pages/storage/volumes/manager/manager.component.html
  src/app/pages/storage/volumes/manager/manager.component.ts
  src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
  src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
  src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts
  src/app/pages/system/advanced/advanced-settings.component.ts
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
  src/app/pages/system/alert-service/alert-service/alert-service.component.ts
  src/assets/styles/other/_tn-styles.scss
Labels: skip jira status

#6679 NAS-115951 / None / Nas 115951-2 Add linter for component selectors
  .eslintrc.js
  src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/widget-controller/widget-controller.component.ts
  src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
  src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
  src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
  src/app/pages/data-protection/smart-task/smart-task-list/smart-task-list.component.ts
  src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
  src/app/pages/services/components/service-rsync/rsync-configure/rsync-configure.component.ts
  src/app/pages/services/components/service-rsync/rsync-module-list/rsync-module-list.component.ts
  src/app/pages/services/components/service-rsync/service-rsync.component.html
  src/app/pages/services/components/service-rsync/service-rsync.component.ts
  src/app/pages/services/components/service-webdav/service-webdav.component.ts
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
  src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts
  src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
  src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-ports.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.html
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/storage/snapshots/snapshot-rollback-dialog/snapshot-rollback-dialog.component.ts
  src/app/pages/storage/vmware-snapshot/vmware-snapshot-list/vmware-snapshot-list.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/group-quota-form/group-quota-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
  src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/user-quota-form/user-quota-form.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
  src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts
  src/app/pages/storage/volumes/permissions/components/acl-editor-list/acl-editor-list.component.ts
  src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.html
  src/app/pages/storage/volumes/permissions/containers/permissions-sidebar/permissions-sidebar.component.ts
  src/app/pages/storage/volumes/volume-list-controls/volumes-list-controls.component.ts
  src/app/pages/storage/volumes/volumes-list/components/export-disconnect-modal.component.ts
  src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
  src/app/pages/system/advanced/initshutdown/initshutdown-list/initshutdown-list.component.ts
  src/app/pages/system/alert-service/alert-service-list/alert-service-list.component.ts
  src/assets/styles/other/_tn-styles.scss
Labels: skip jira status

#6680 NAS-115787 / 22.02.2 / NAS-115787: Keep dashboard safe
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
Labels: backport-22.12

#6725 NAS-114924 / 13.0 / NAS-114924: Import CSR errors out on passphrase
  src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
Labels: backport-22.02.2
