Repository truenas/webui, pull requests merged in 2022-08, with the labels that each got.

#6928 NAS-117476 / 22.12 / NAS-117476: Remove 'bucket_policy_only' attribute from 'cloudsync.list_directory' call
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: backport-22.02.4

#6956 NAS-112995 / 13.0 / Rename 'allow_from_scratch' checkbox
  src/app/helptext/task-calendar/replication/replication.ts
Labels: backport-22.12, backport-22.02.4

#6962 NAS-117596 / 22.12 / Redirect to Disks Reports with pre-selected disks
  src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.html
  src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.spec.ts
  src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.ts
Labels: jira

#7001 NAS-117719 / 22.12 / Nas-117719 Do not run CI checks when only RE tests were changed
  .github/workflows/docker_internal.yml
  .github/workflows/docker_latest.yml
  .github/workflows/main.yml
Labels: skip jira status

#7003 NAS-117795 / 22.12 / Move replace-disk-dialog to storage2
  src/app/pages/storage/storage.module.ts
  src/app/pages/storage/volumes/volume-status/volume-status.component.ts
  src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.spec.ts
  src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.ts
  src/app/pages/storage2/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.html
  src/app/pages/storage2/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.scss
  src/app/pages/storage2/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.spec.ts
  src/app/pages/storage2/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
  src/app/pages/storage2/modules/disks/disks.module.ts
Labels: jira

#7027 NAS-117897 / 13.0 / NAS-117897: Showing controller in alerts
  src/app/components/common/notifications/notifications.component.css
  src/app/components/common/notifications/notifications.component.html
  src/app/components/common/notifications/notifications.component.ts
  src/app/services/notifications.service.ts
Labels: skip jira status
