Repository truenas/webui, pull requests merged in 2023-11, with the labels that each got.

#9138 NAS-124895 / 24.04 / Selecting Custom retention policy once, keeps Save button disabled even after choosing other retention option
  src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.ts
Labels: backport-23.10.1

#9172 NAS-124947 / 24.04 / [Apps/UI]: Immutable fields in an item, leaks in other items too
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
  src/app/services/schema/app-schema.transformer.ts
  src/assets/i18n/fr.json
Labels: backport-23.10.1

#9174 NAS-124947 / 23.10.1 / [Apps/UI]: Immutable fields in an item, leaks in other items too (by AlexKarpov98)
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
  src/app/services/schema/app-schema.transformer.ts
Labels: no-time-tracked

#9199 NAS-125147 / 24.04 / Dragonfish: Generate debug dialog triggered multiple times and comes back after canceled
  src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
Labels: backport-23.10.1

#9195 NAS-124826 / 23.10.1 / Using rawvalue instead of value
  src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.spec.ts
  src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
Labels: backport-24.04

#9201 NAS-125213 / 24.04 / From wizard to Advanced options in card/list are not updating on new items creation (switching from wizard to form)
  src/app/enums/from-wizard-to-advanced.enum.ts
  src/app/modules/ix-icon/ix-icon.component.scss
  src/app/modules/ix-table2/components/ix-table2/ix-table2.component.scss
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
  src/app/pages/data-protection/replication/replication-task-card/replication-task-card.component.ts
  src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts
  src/app/store/admin-panel/admin.actions.ts
Labels: backport-23.10.1

#9207 NAS-125209 / 24.04 / Pools missing in GUI after manually initiating scrub tasks on some pools
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
Labels: backport-23.10.1

#9198 NAS-125008 / 24.04 / Apps: When a `show_if` tries to evaluate a field that is defined after it, results in both fields being hidden in the UI
  src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
  src/app/services/schema/app-schema.service.ts
Labels: backport-23.10.1

#9137 NAS-124802 / 24.04 / Add Metadata or Dedup VDEV types
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/add-vdev-to-pool.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
Labels: backport-23.10.1

#9218 NAS-124897 / 24.04 / Fix verify credentials in Cloud Credentials form
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
Labels: backport-23.10.1

#9225 NAS-124951 / 23.10.1 / Remove required for periodic_snapshot_tasks, Disable ssh_credentials when transport is local
  src/app/pages/data-protection/replication/replication-form/sections/source-section/source-section.component.html
  src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts
Labels: backport-24.04

#9238 NAS-125343 / 24.04 / Fix network send/receive rate
  src/app/interfaces/reporting.interface.ts
  src/app/modules/common/interface-status-icon/interface-status-icon.component.spec.ts
  src/app/modules/common/interface-status-icon/interface-status-icon.component.ts
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Labels: jira, backport-23.10.2

#9241 NAS-125347 / 24.04 / Bugs detected in console
  src/app/modules/common/interface-status-icon/interface-status-icon.component.ts
  src/app/pages/apps/apps.module.ts
Labels: backport-23.10.1

#9236 NAS-124602 / 23.10.1 / Reload UI during updates
  src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/services/update.service.ts
  src/app/views/sessions/signin/store/signin.store.spec.ts
  src/app/views/sessions/signin/store/signin.store.ts
Labels: backport-13.0, backport-24.04

#9204 NAS-125191 / 24.04 / SCALE Certificates UI does not show saved "Renew Certificate Days Before Expiry" values
  src/app/interfaces/certificate.interface.ts
  src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.ts
Labels: backport-23.10.2

#9259 NAS-125122 / 23.10.2 / Only accept events with truenas.com origin
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
Labels: backport-24.04
