Repository truenas/webui, pull requests merged in 2023-06, with the labels that each got.

#8262 NAS-122267 / 23.10 / Manual s.m.a.r.t test modal UI
  src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.html
  src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.scss
Labels: backport-22.12.4

#8232 NAS-121123 / 22.12.3 / Reordered dashboard reversts to initial order (by AlexKarpov98)
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/store/preferences/preferences.actions.ts
  src/app/store/preferences/preferences.reducer.ts
Labels: blocked

#8270 NAS-122272 / 22.12.3 / Unable to install apps with lists in schema
  src/app/services/app-schema.service.spec.ts
  src/app/services/app-schema.service.ts
  src/app/services/app-shema.transformer.ts
Labels: backport-23.10, backport-22.12.4

#8291 NAS-122407 / 23.10 / Impossible to terminate other specific sessions
  src/app/modules/entity/table/table.component.html
Labels: backport-22.12.4

#8304 NAS-122282 / 23.10 / "Failed to export RRD data: ERROR" appear when navigate to the furthest position/time, left, in Reporting graphs
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
Labels: backport-22.12.4

#8253 NAS-120187 / 23.10 / Unable to set static IP address on secondary interface
  src/app/pages/network/components/interface-form/interface-form.component.html
  src/app/pages/network/components/interface-form/interface-form.component.scss
Labels: backport-22.12.4
