Repository truenas/webui, pull requests merged in 2023-01, with the labels that each got.

#7536 NAS-119293 / 23.10 / Better sorting for datasets and devices
  src/app/modules/ix-tree/flat-tree-datasource.ts
  src/app/modules/ix-tree/nested-tree-datasource.ts
  src/app/modules/ix-tree/tree-datasource.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
Labels: backport-22.12.1

#7541 NAS-119670 / 23.10 / IPMI is missing when page is reloaded
  src/app/pages/network/network.component.ts
Labels: backport-22.12.1

#7544 NAS-119604 / 23.10 / Design flaw: If the error log is too large, it will be displayed beyond the log window
  src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.scss
Labels: backport-22.12.1

#7555 NAS-119330 / 23.10 / Add check for the readonly property
  src/app/interfaces/dataset.interface.ts
  src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
Labels: backport-22.12.1

#7378 NAS-118993 / 23.10 / Update WebUI for quota API changes
  src/app/enums/dataset.enum.ts
  src/app/interfaces/dataset-quota.interface.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quota-edit-form/dataset-quota-edit-form.component.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.spec.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.spec.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
Labels: backport-22.12.1

#7558 NAS-119743 / 23.10 / System -> General -> Support -> Production system checkbox and modal bug
  src/app/pages/system/general-settings/support/support.component.ts
Labels: backport-22.12.1

#7559 NAS-119793 / 23.10 / Sidebar menu closes if I hit ESC button
  src/app/modules/layout/components/admin-layout/admin-layout.component.html
Labels: backport-22.12.1

#7499 NAS-119180 / 23.10 / Designs for allowing users to manage ACL presets + Improvements
  src/app/interfaces/acl.interface.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.spec.ts
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.ts
Labels: backport-22.12.1

#7577 NAS-119701 / 23.10 / Minor text change
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Labels: backport-22.12.1

#7574 NAS-119512 / 23.10 / Fixed theme is lost when session times out
  src/app/modules/layout/components/admin-layout/admin-layout.component.ts
  src/app/modules/layout/components/auth-layout/auth-layout.component.ts
  src/app/services/theme/theme.service.ts
  src/app/store/preferences/preferences.reducer.ts
Labels: backport-22.12.1

#7567 NAS-119716 / 23.10 / Switching a drop down selection, does not "drop" values that are now hidden
  src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
  src/app/pages/apps/components/chart-form/chart-form.component.ts
Labels: backport-22.12.1

#7573 NAS-119591 / 23.10 / [SCALE/Apps]: `default` does not work in `list` types
  src/app/interfaces/chart-release.interface.ts
  src/app/interfaces/dynamic-form-schema.interface.ts
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.html
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.ts
  src/app/modules/ix-forms/components/ix-list/ix-list.component.ts
  src/app/pages/apps-old/forms/chart-form/chart-form.component.html
  src/app/services/schema/app-schema.service.spec.ts
  src/app/services/schema/app-shema.transformer.ts
Labels: backport-22.12.1

#7599 NAS-119879 / 23.10 / Unable to set or delete an ACL preset
  src/app/interfaces/acl.interface.ts
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.html
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.scss
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.spec.ts
  src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.ts
Labels: backport-22.12.1

#7562 NAS-119698 / 23.10 / Unsupported type = cron and uri when trying to Launch a docker image
  src/app/enums/chart-schema-type.enum.ts
  src/app/enums/dynamic-form-schema-type.enum.ts
  src/app/interfaces/app-schema.interface.ts
  src/app/interfaces/dynamic-form-schema.interface.ts
  src/app/modules/common/app-common.module.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/classes/custom-untped-form-array.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/classes/custom-untped-form-control.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/classes/custom-untyped-form-field.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/classes/custom-untyped-form-group.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.scss
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.spec.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form.component.html
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form.component.scss
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form.component.spec.ts
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form.component.ts
  src/app/modules/ix-dynamic-form/ix-dynamic-form.module.ts
  src/app/modules/ix-forms/components/ix-dynamic-form/classes/custom-untyped-form-field.ts
  src/app/modules/ix-forms/components/ix-list/ix-list.component.ts
  src/app/modules/ix-forms/ix-forms.module.ts
  src/app/pages/apps-old/common-apps-toolbar-buttons/common-apps-toolbar-buttons.component.ts
  src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
  src/app/pages/apps-old/old-apps.module.ts
  src/app/pages/apps/apps.module.ts
  src/app/pages/apps/components/chart-form/chart-form.component.ts
  src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.spec.ts
  src/app/pages/credentials/credentials.module.ts
  src/app/services/schema/app-schema.service.spec.ts
  src/app/services/schema/app-schema.service.ts
  src/app/services/schema/app-shema.transformer.ts
Labels: backport-22.12.1

#7531 NAS-119668: Correctly report vdev width
  src/app/core/testing/utils/mock-storage-generator.utils.ts
  src/app/enums/v-dev-type.enum.ts
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
  src/app/services/storage.service.spec.ts
  src/app/services/storage.service.ts
Labels: backport-22.12.1

#7583 NAS-119844 / 23.10 / NVMe drives show "Enable S.M.A.R.T." checkbox unchecked even if `togglesmart` API field is true
  src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.ts
Labels: backport-22.12.1

#7554 NAS-119632 / 22.12.1 / Nas 119632 Fixed tooltip
  src/app/interfaces/dynamic-form-schema.interface.ts
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.scss
  src/app/services/app-schema.service.spec.ts
  src/app/services/app-schema.service.ts
Labels: backport-23.10

#7589 NAS-119616 / 22.12.1 / Changing from method to subject
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/azure-provider-form/azure-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/azure-provider-form/azure-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/backblaze-b2-provider-form/backblaze-b2-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/backblaze-b2-provider-form/backblaze-b2-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/ftp-provider-form/ftp-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/ftp-provider-form/ftp-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-cloud-provider-form/google-cloud-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-cloud-provider-form/google-cloud-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-drive-provider-form/google-drive-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-drive-provider-form/google-drive-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/http-provider-form/http-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/http-provider-form/http-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/mega-provider-form/mega-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/mega-provider-form/mega-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/one-drive-provider-form/one-drive-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/one-drive-provider-form/one-drive-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/openstack-swift-provider-form/openstack-swift-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/openstack-swift-provider-form/openstack-swift-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/pcloud-provider-form/pcloud-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/pcloud-provider-form/pcloud-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/s3-provider-form/s3-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/s3-provider-form/s3-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/token-provider-form/token-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/token-provider-form/token-provider-form.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/webdav-provider-form/webdav-provider-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/webdav-provider-form/webdav-provider-form.component.ts
Labels: backport-23.10

#7592 NAS-119792 / 23.10 / Changing user password doesn't work on non-root users
  src/app/interfaces/api-directory.interface.ts
  src/app/interfaces/ds-cache.interface.ts
  src/app/modules/layout/components/change-password-dialog/change-password-dialog.component.spec.ts
  src/app/modules/layout/components/change-password-dialog/change-password-dialog.component.ts
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
  src/app/services/ws.service.ts
Labels: backport-22.12.1

#7356 NAS-119081 / 23.10 / Do not disallow failover when system versions mismatch
  src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
  src/app/modules/layout/components/topbar/topbar.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/network/components/forms/ipmi-form.component.spec.ts
  src/app/pages/network/components/interface-form/interface-form.component.spec.ts
  src/app/store/ha-info/ha-info.actions.ts
  src/app/store/ha-info/ha-info.effects.ts
  src/app/store/ha-info/ha-info.reducer.ts
  src/app/store/ha-info/ha-info.selectors.ts
Labels: backport-22.12.1

#7611 NAS-119211 / 22.12.2 / DisksUpdateService also returns a list of updated disks
  src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.ts
  src/app/services/disk-temperature.service.ts
  src/app/services/disks-update.service.ts
Labels: backport-23.10

#7625 NAS-119980 / 23.10 / Missing icon in dataset details header
  src/app/modules/ix-icon/ix-icon.component.ts
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
  src/app/pages/storage/modules/devices/components/devices/devices.component.html
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
Labels: backport-22.12.2

#7657 NAS-120047 / 22.12-BETA.2 / UI issue on login window with 2FA enabled
  src/app/views/sessions/signin/signin.component.html
  src/app/views/sessions/signin/signin.component.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-22.12.1
