Repository truenas/webui, pull requests merged in 2023-09, with the labels that each got.

#8701 NAS-123813 / 24.04 / Enclosure page A symbol
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.html
Labels: backport-23.10, backport-22.12.4

#8711 NAS-123711 / 24.04 / ix-table2 toggle collapse UI issue
  src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html
Labels: backport-23.10

#8720 NAS-123742 / 24.04 / Spares not properly identified on Storage Dashboard for dRAID pools
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
Labels: backport-23.10

#8703 NAS-123811 / 24.04 / Layout fixes for Datasets and Apps
  src/app/core/components/directives/details-height/details-height.directive.ts
  src/app/modules/layout/components/admin-layout/admin-layout.component.scss
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.scss
  src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
  src/assets/styles/mixins/cards.scss
Labels: backport-23.10

#8723 NAS-123818 / 24.04 / Add explicit flag to allow/disallow new entries in ix-chips
  src/app/modules/ix-forms/components/ix-chips/ix-chips.component.html
  src/app/modules/ix-forms/components/ix-chips/ix-chips.component.spec.ts
  src/app/modules/ix-forms/components/ix-chips/ix-chips.component.ts
  src/app/modules/ix-forms/components/ix-chips/ix-chips.harness.ts
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/1-general-wizard-step/general-wizard-step.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
Labels: backport-23.10

#8732 NAS-123802 / 23.10 / Fix position of children in dataset tree
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
Labels: backport-23.10-BETA.1

#8718 NAS-123762 / 24.04 / Fix JIRA token in File Ticket form
  src/app/pages/system/file-ticket/file-ticket-form/components/jira-oauth/jira-oauth.component.ts
  src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.spec.ts
Labels: backport-23.10

#8719 NAS-123852 / 24.04 / Remove horizontal scroll from entity job dialogs
  src/app/modules/entity/entity-job/entity-job.component.scss
Labels: backport-23.10

#8747 NAS-123834 / 24.04 / Fix disabling `Sign In` button
  src/app/views/sessions/signin/set-admin-password-form/set-admin-password-form.component.html
Labels: backport-23.10

#8766 NAS-123902 / 24.04 / Show error message
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
Labels: backport-23.10

#8773 NAS-123911 / 23.10 / Remove Number of VDEVs dropdown for cache and log (by AlexKarpov98)
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/layout-step.component.ts
Labels: backport-23.10-RC.1

#8764 NAS-123723 / 23.10 / View Enclosure Elements contain empty Descriptor column
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-22.12.4

#8782 NAS-123932 / 24.04 / Pool creation shows type for spares
  src/app/helpers/storage.helper.ts
  src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.html
  src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
  src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.html
  src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.ts
  src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.html
  src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
  src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.spec.ts
  src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.ts
Labels: backport-23.10, backport-23.10-RC.1

#8787 NAS-123781 / 24.04 / Mock Utility: Complete R series support
  scripts/ui/models.json
  src/app/core/testing/utils/enclosure-templates/mock-r10.ts
  src/app/core/testing/utils/enclosure-templates/mock-r30.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
Labels: backport-23.10-RC.1

#8790 NAS-124004 / 24.04 / Do not show success message when snapshot form is closed
  src/app/pages/datasets/components/data-protection-card/data-protection-card.component.ts
Labels: backport-23.10, backport-23.10-RC.1

#8707 NAS-123749 / 24.04 / "Spares" category from pool creation "Configuration Preview" inaccurate/unneeded
  src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
Labels: backport-23.10, backport-23.10-RC.1

#8804 NAS-122258 / 24.04 / Showing extent disk on edit
  src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
Labels: backport-23.10, backport-22.12.4

#8788 NAS-123931 / 24.04 / Time axis on the reporting charts values incorrect on zooms
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
Labels: backport-23.10, backport-22.12.4, backport-23.10-RC.1

#8813 NAS-123987 / 24.04 / Do not wait for `failover.get_ips` and `failover.disabled reasons` before enabling signin form
  src/app/views/sessions/sessions.module.ts
  src/app/views/sessions/signin/failover-status/failover-status.component.html
  src/app/views/sessions/signin/failover-status/failover-status.component.scss
  src/app/views/sessions/signin/store/signin.store.ts
Labels: backport-23.10

#8819 NAS-123985 / 24.04 / Misaligned warning icon in standby card
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
Labels: backport-23.10

#8820 NAS-123994 / 24.04 / Investigate delay on comboboxes
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
Labels: backport-23.10, backport-22.12.4

#8812 NAS-123859 / 24.04 / Fix hostname for HA System on widget-sys-info
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
Labels: backport-23.10

#8842 NAS-124085 / 24.04 / Fix feedback dialog when attachment upload is failed
  src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts
  src/assets/i18n/fr.json
Labels: backport-23.10, backport-23.10-RC.1

#8849 NAS-124098 / 23.10-RC.1 / Fixes dataset order
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/pages/datasets/utils/dataset.utils.spec.ts
  src/app/pages/datasets/utils/dataset.utils.ts
Labels: backport-23.10, backport-22.12.4, backport-24.04

#8858 NAS-124080 / 23.10 / Fix max number of concurrent calls and empty ws connection
  src/app/views/sessions/signin/signin.component.ts
  src/app/views/sessions/signin/store/signin.store.spec.ts
  src/app/views/sessions/signin/store/signin.store.ts
Labels: backport-24.04

#8881 NAS-124133 / 24.04 / Ensure iSCSI Wizard creates Initiator Group
  src/app/interfaces/iscsi.interface.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
Labels: backport-23.10

#8844 NAS-123780 / 24.04 / Mock Utility: support more expansion shelves
  scripts/ui/models.json
  src/app/core/testing/utils/enclosure-templates/mock-e16.ts
  src/app/core/testing/utils/enclosure-templates/mock-e24.ts
  src/app/core/testing/utils/enclosure-templates/mock-es12.ts
  src/app/core/testing/utils/enclosure-templates/mock-es60.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
Labels: backport-23.10

#8874 NAS-124075 / 23.10 / Fix uploading screenshots multiple times
  src/app/services/ix-file-upload.service.ts
Labels: backport-24.04

#8900 NAS-122712: ES102S
  scripts/ui/models.json
  src/app/core/testing/utils/enclosure-templates/mock-es102s.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
  src/app/pages/system/view-enclosure/classes/hardware/es102s.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/assets/images/hardware/es102s/es102s_960w.png
  src/assets/images/hardware/es102s/es102s_960w_drivetray.png
  src/assets/images/hardware/es102s/es102s_960w_drivetray_bg.png
  src/assets/images/hardware/es102s/es102s_960w_drivetray_handle.png
Labels: backport-24.04

#8899 NAS-123287 / 23.10 / ES60G2
  src/app/core/testing/utils/enclosure-templates/mock-es60g2.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
  src/app/pages/system/view-enclosure/classes/hardware/es60g2.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-24.04

#8886 NAS-123945 / 24.04 / NAS-124077: Removing of(undefined)
  src/app/pages/apps/store/apps-filter-store.service.ts
  src/app/pages/apps/store/apps-store.service.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
  src/app/pages/apps/store/kubernetes-store.service.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
  src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
  src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.ts
  src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/pages/vm/utils/vm-gpu.service.ts
  src/app/services/gpu/gpu-service.spec.ts
  src/app/services/gpu/gpu.service.ts
  src/app/services/ws.service.ts
Labels: backport-23.10

#8896 NAS-124164 / 24.04 / Fix layout for directory services dialog
  src/app/modules/common/dialog/directory-services-monitor/directory-services-monitor.component.scss
Labels: backport-23.10

#8892 NAS-124152 / 24.04 / Show fallback image when product image loading has failure
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/dashboard/dashboard.module.ts
Labels: backport-23.10

#8905 NAS-124235 / 24.04 / Fix layout when pool has long name on Pool Creation Wizard
  src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.scss
  src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss
Labels: backport-23.10

#8913 NAS-123287 / 23.10 / NAS-123287-cobia Assets Update
  src/app/pages/system/view-enclosure/classes/hardware/es60g2.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/assets/images/hardware/es60g2/es60g2_960w.png
  src/assets/images/hardware/es60g2/es60g2_960w_drivetray.png
  src/assets/images/hardware/es60g2/es60g2_960w_drivetray_handle.png
Labels: backport-24.04

#8904 NAS-124237 / 24.04 / Fix password icon in ix-input
  src/app/modules/ix-forms/components/ix-input/ix-input.component.scss
Labels: backport-23.10

#8925 NAS-124161 / 24.04 / During pool creation on Cobia nightlies, if dRAID is selected as a layout other options are not available
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html
Labels: backport-23.10

#8927 NAS-124123 / 24.04 / Removing vdevs from the manual disk selection dialog doesn't update the automated dropdowns
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
Labels: backport-23.10

#8941 NAS-124048 / 24.04 / Fix dataset layout on mobile devices
  src/app/core/components/directives/details-height/details-height.directive.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
Labels: backport-23.10

#8958 NAS-124339 / 24.04 / Sorting on installed applications screen
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
  src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.html
  src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.spec.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.scss
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.scss
Labels: backport-23.10
