Repository truenas/webui, pull requests merged in 2023-05, with the labels that each got.

#8126 NAS-121324 / 23.10 / Test plan fails for contributor PRs
  .github/workflows/main.yml
Labels: skip jira status

#8118 NAS-121706 / 23.10 / Hide not implemented elements
  src/app/pages/apps/TODO
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.ts
  src/app/pages/apps/components/available-apps/apps-toolbar-buttons/apps-toolbar-buttons.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: skip jira status

#8102 NAS-121612 / 23.10 / Import Data Button Appears on Data Protection Header
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
Labels: backport-22.12.3

#8154 NAS-121738 / 23.10 / Snapshot Lifetime Unit Would Be Hidden If Custom ScheduleIs Too Long
  src/app/modules/scheduler/components/scheduler/scheduler.component.scss
Labels: backport-22.12.3

#8151 NAS-121721 / 23.10 / SCALE dashboard doesn't show actual serial numbers; uses license serials instead
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/system/general-settings/support/support-card/support-card.component.ts
Labels: backport-22.12.3

#8187 NAS-121914 / 13.0 / Fixed Expect Enter an option instead of https:// in boot.exp
  tests/boot.exp
Labels: jira

#8186 NAS-121884 / 23.10 / Sudo Dialog appears 3x after Replication Task Created for remote non root user
  src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts
  src/app/services/dialog.service.ts
Labels: backport-22.12.3

#8217 NAS-122057 / 23.10 / Rename official catalog
  src/app/constants/catalog.constants.ts
  src/app/pages/apps-old/dialogs/chart-bulk-upgrade/chart-bulk-upgrade.component.spec.ts
  src/app/pages/apps-old/forms/catalog-edit-form/catalog-edit-form.component.spec.ts
  src/app/pages/apps-old/forms/chart-form/chart-form.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
  src/app/pages/apps/components/available-apps/app-card/app-card.component.spec.ts
  src/app/pages/apps/components/available-apps/apps-toolbar-buttons/apps-toolbar-buttons.component.spec.ts
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
  src/app/pages/apps/components/catalogs/catalog-edit-form/catalog-edit-form.component.spec.ts
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
Labels: backport-22.12.3

#8169 NAS-121123 / 23.10 / Reordered dashboard reversts to initial order
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/store/preferences/preferences.actions.ts
  src/app/store/preferences/preferences.reducer.ts
Labels: backport-22.12.3

#8231 NAS-120108 / 22.12.3 / Extract enclosure visualizations on new disk info
  src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.ts
Labels: skip jira status

#8241 NAS-122137 / 23.10 / Fix reporting dropdown menu
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
Labels: backport-22.12.3
