Repository truenas/webui, pull requests merged in 2023-10, with the labels that each got.

#8969 NAS-123907 / 24.04 / Do not show New & Updated in search results
  src/app/pages/apps/store/apps-filter-store.service.ts
Labels: backport-23.10

#8971 NAS-124250 / 24.04 / Details panel does not always properly populate when clicking apps
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
Labels: backport-23.10

#8972 NAS-124301 / 24.04 / Traceback received When creating New iSCSI Share/Suggested Improvement
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.spec.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.html
  src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.ts
Labels: backport-23.10

#8976 NAS-124397 / 24.04 / Notes card in apps UI does not show full text
  src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss
Labels: backport-23.10

#8970 NAS-124222 / 24.04 / Login page error mesage Username is required
  src/app/views/sessions/signin/signin-form/signin-form.component.html
  src/app/views/sessions/signin/signin-form/signin-form.component.ts
Labels: backport-23.10

#8950 NAS-124044 / 23.10 / Adapt to 0 values
  src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html
  src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
Labels: backport-24.04

#8978 NAS-124360 / 24.04 / Fixed dataset form
  src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.spec.ts
  src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.ts
Labels: backport-23.10

#8998 NAS-124340 / 24.04 / NAS-124340 Stopped cron jobs shown as tasks
  src/app/modules/jobs/components/job-item/job-item.component.html
Labels: backport-23.10

#9004 NAS-124291 / 24.04 / Minio Host Path cannot be selected
  src/app/services/schema/app-schema.service.ts
Labels: backport-23.10

#9009 NAS-124442 / 24.04 / Errors is not shown - Cannot use 'in' operator to search …
  src/app/services/ws.service.ts
Labels: backport-23.10

#8956 NAS-124232 / 23.10 / Added query param to fetch `display_available` attribute
  src/app/interfaces/virtual-machine.interface.ts
  src/app/pages/vm/vm-list/vm-list.component.ts
Labels: backport-24.04

#8993 NAS-124325 / 24.04 / An Internally Signed Certificate Requires a Page Reload To Display After Creation On The Certificates Page
  src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
Labels: backport-23.10.0

#9022 NAS-124480 / 24.04 / "Switched to new dataset" does not work anymore
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9025 NAS-124555 / 24.04 / Unexpected symbol in Allowed IP Addresses Card
  src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.html
Labels: backport-23.10.0, backport-23.10.1

#9039 NAS-124606 / 24.04 / Duplicate name error is not shown in SMB shares
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9038 NAS-124600 / 24.04 / Webui path selector for home dirs presents non-directory files
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9023 NAS-124481 / 24.04 / undefined in search filter when installing an app
  src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9033 NAS-124569 / 24.04 / Rename ES102S to ES102G2 (UI)
  scripts/ui/models.json
  src/app/core/testing/utils/enclosure-templates/mock-es102g2.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
  src/app/pages/system/view-enclosure/classes/hardware/es102g2.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/assets/images/hardware/es102g2/es102g2/es102g2_960w.png
  src/assets/images/hardware/es102g2/es102g2/es102g2_960w_drivetray.png
  src/assets/images/hardware/es102g2/es102g2/es102g2_960w_drivetray_bg.png
  src/assets/images/hardware/es102g2/es102g2/es102g2_960w_drivetray_handle.png
  src/assets/images/hardware/es102g2/es102g2_960w.png
  src/assets/images/hardware/es102g2/es102g2_960w_drivetray.png
  src/assets/images/hardware/es102g2/es102g2_960w_drivetray_bg.png
  src/assets/images/hardware/es102g2/es102g2_960w_drivetray_handle.png
Labels: backport-23.10.0, backport-13.0, backport-23.10.1

#9046 NAS-124609 / 24.04 / Do not open Task Manager when using Upgrade All
  src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9065 NAS-124681 / 24.04 / Race condition in interface form
  src/app/pages/network/components/interface-form/interface-form.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9064 NAS-124680 / 24.04 / Notes section on Apps page has issues showing full contents - scrolling/expanding data not always available
  src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.scss
  src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
  src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.html
  src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9078 NAS-124707 / 24.04 / UI Adjustments for Reporting Exporters
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-form/reporting-exporters-form.component.ts
  src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.html
  src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.scss
  src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.ts
Labels: backport-23.10.0, backport-23.10.1

#9077 NAS-124685 / 24.04 / Apps "Search" text field, for Installed and Discover pages, do not have a character string limit
  src/app/modules/common/search-input/search-input.component.html
  src/app/modules/common/search-input/search-input.component.ts
  src/app/modules/ix-forms/components/ix-input/ix-input.component.html
  src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
Labels: backport-23.10.0, backport-23.10.1

#9109 NAS-124727 / 24.04 / Show disks assigned to configured DRAID
  src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts
Labels: backport-23.10.1

#9104 NAS-124763 / 24.04 / Incorrect indentation in dataset tree
  src/app/modules/ix-tree/components/nested-tree-node/nested-tree-node.component.scss
  src/app/modules/ix-tree/components/tree-view/tree-view.component.scss
  src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss
Labels: backport-23.10.0, backport-23.10.1

#9076 NAS-124670 / 24.04 / Reporting disks view improvements for large disk systems
  src/app/modules/ix-forms/components/ix-select/ix-select.component.html
  src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
  src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
  src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.html
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
  src/assets/styles/other/_tn-styles.scss
Labels: backport-23.10.0, backport-23.10.1

#9114 NAS-124731 / 24.04 / Remove the "Remove" and "Extend" buttons for the DRAID pool
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
Labels: backport-23.10.1

#9111 NAS-124732 / 24.04 / Request: Improve sorting for Replace Disk Search for DRAIDs
  src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.html
  src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.spec.ts
  src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts
  src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.html
  src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
  src/assets/styles/other/_tn-styles.scss
Labels: backport-23.10.0, backport-23.10.1
