Repository truenas/webui, pull requests merged in 2023-02, with the labels that each got.

#7681 NAS-120123 / 23.10 / System Settings > Services > S.M.A.R.T > UI flags fields as required on tab through
  src/app/modules/ix-forms/components/ix-input/ix-input.component.spec.ts
  src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
Labels: backport-22.12.1

#7686 NAS-120045 / 23.10 / One Controller's System Serial Number is listed twice and the other is missing in System Settings/General/Support
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/system/general-settings/support/support.component.ts
Labels: backport-22.12.1

#7688 NAS-120123 / 22.12.1 / System Settings > Services > S.M.A.R.T > UI flags fields as required on tab through (by AlexKarpov98)
  src/app/modules/ix-forms/components/ix-input/ix-input.component.spec.ts
  src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
Labels: backport-22.12.2

#7689 NAS-120045 / 22.12.1 / One Controller's System Serial Number is listed twice and the other is missing in System Settings/General/Support (by AlexKarpov98)
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/system/general-settings/support/support.component.ts
Labels: backport-22.12.2

#7674 NAS-120130 / 23.10 / Missing arrows from main menu
  src/app/modules/ix-icon/ix-icon.component.ts
Labels: backport-22.12.2

#7683 NAS-120076 / 23.10 / Unable to edit an App
  src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
  src/app/pages/apps/components/chart-form/chart-form.component.ts
  src/app/services/schema/app-schema.service.ts
Labels: backport-22.12.1

#7700 NAS-120121 / 22.12.1 / Hiding time diff warning
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/reports-dashboard/reports-dashboard.component.html
Labels: backport-22.12.2

#7709 NAS-120213 / 13.0 / Refresh UI after an update
  src/app/app.module.ts
  src/app/helpers/window.helper.ts
  src/app/pages/system/update/manualupdate/manualupdate.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/services/update.service.ts
  src/app/views/sessions/signin/signin.component.ts
  yarn.lock
Labels: backport-23.10, backport-22.12.2, backport-22.12.1

#7711 NAS-120213 / 22.12.1 / Refresh UI after an update (by undsoft)
  src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/services/update.service.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-23.10, backport-22.12.2

#7715 NAS-120126 / 22.12.1 / Reinit SigninComponent after connect (by bvasilenko)
  src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.spec.ts
  src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.ts
  src/app/services/ws.service.ts
  src/app/views/sessions/signin/signin.component.ts
Labels: backport-22.12.2

#7717 NAS-119431 / 22.12.2 / No special treatment for dictionary list items
  src/app/services/app-shema.transformer.ts
Labels: backport-23.10

#7727 NAS-119886 / 23.10 / iSCSI Wizard - Add Listen should be a required field
  src/app/modules/entity/entity-form/components/form-list/form-list.component.html
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
Labels: backport-22.12.1

#7728 NAS-120173 / 23.10 / Expose new `APPS` share_type during dataset creation
  src/app/enums/dataset.enum.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
Labels: backport-22.12.1

#7729 NAS-119687 / 22.12.2 / Adding force flags in Kubernetes settings
  src/app/interfaces/kubernetes-config.interface.ts
  src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.html
  src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.spec.ts
  src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.ts
Labels: backport-23.10

#7739 NAS-120264 / 23.10 / Dataset names don't have to begin with an alphanumeric character.
  src/app/modules/entity/entity-form/entity-form.component.scss
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/system/bootenv/bootenv-form/bootenv-form.component.ts
  src/app/services/boot-env.service.ts
  src/app/services/index.ts
  src/app/services/name-validation.service.ts
Labels: backport-22.12.1

#7732 NAS-120137 / 22.12.2 / Fixing Enable ACL warning in SMB share form
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-23.10

#7756 NAS-120326 / 23.10 / Snapshots -> Show Extra columns slide-toggle is not showing correct status
  src/app/modules/ix-forms/ix-forms.module.ts
  src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html
  src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.ts
Labels: backport-22.12.1

#7726 NAS-120181 / 23.10 / Scale branding in bottom left and copyright are too small to be readable.
  src/app/modules/layout/components/admin-layout/admin-layout.component.scss
Labels: backport-22.12.1

#7753 NAS-120298 / 22.12.2 / NAS-120298
  src/app/pages/system/view-enclosure/classes/chassis-view.ts
  src/app/pages/system/view-enclosure/classes/system-profiler.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-23.10, backport-22.12.1

#7746 NAS-120136 / 22.12.2 / Clarification of the `checkIsValidCronTab` method
  src/app/services/app-schema.service.ts
Labels: backported, backport-23.10

#7772 NAS-120136 / 23.10 / Clarification of the `checkIsValidCronTab` method
  src/app/services/schema/app-schema.service.ts
Labels: backported

#7750 NAS-117906 / 23.10 / Cannot clear optional integer value - nodePort
  src/app/interfaces/chart-release.interface.ts
  src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
  src/app/pages/apps/components/chart-form/chart-form.component.ts
  src/app/services/schema/app-schema.service.spec.ts
  src/app/services/schema/app-schema.service.ts
Labels: backport-22.12.2

#7779 NAS-120349 / 23.10 / Fix stdout tooltip in cron form
  src/app/pages/system/advanced/cron/cron-form/cron-form.component.html
Labels: backport-22.12.2

#7747 NAS-120310 / 23.10 / Fix long description on jobs panel
  src/app/modules/jobs/components/job-item/job-item.component.html
  src/app/modules/jobs/components/job-item/job-item.component.scss
  src/app/modules/jobs/components/job-item/job-item.component.spec.ts
  src/app/modules/jobs/components/jobs-panel/jobs-panel.component.scss
  src/assets/styles/other/_tn-styles.scss
Labels: backport-22.12.2

#7748 NAS-119955 / 23.10 / Network speed mismatch between Key-Max-Mean-Min values
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/utils/report.utils.ts
Labels: backport-22.12.2

#7801 NAS-120422 / 23.10 / Fix tooltip in active directory form
  src/app/helptext/directory-service/active-directory.ts
  src/app/pages/directory-service/components/active-directory/active-directory.component.html
Labels: backport-22.12.2

#7803 NAS-120266 / 23.10 / Dont unsub when dialog is destroyed
  src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.html
  src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.spec.ts
  src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.ts
  src/app/pages/vm/vm-list/vm-list.component.ts
Labels: backport-22.12.2

#7808 NAS-120432 / 22.12.2 / Replication tasks cannot be edited
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
Labels: backport-23.10

#7804 NAS-120260 / 22.12.2 / Dont use data of disk that doesn't exist
  src/app/services/storage.service.ts
Labels: backport-23.10

#7820 NAS-120387 / 23.10 / When loading currently running jobs for task manager, exclude the ones that have `transient: true`
  src/app/interfaces/job.interface.ts
  src/app/modules/jobs/store/job.selectors.ts
  src/app/pages/jobs/job-logs-row/job-logs-row.component.spec.ts
Labels: backport-22.12.2

#7834 NAS-119831 / 23.10 / Hide import disk functionality on enterprise systems
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.html
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/store/system-info/system-info.actions.ts
  src/app/store/system-info/system-info.effects.ts
  src/app/store/system-info/system-info.reducer.ts
  src/app/store/system-info/system-info.selectors.ts
Labels: backport-22.12.2

#7821 NAS-120148 / 23.10 / Add missing es24f image assets
  src/assets/images/hardware/es24f/es24f_960w.png
  src/assets/images/hardware/es24f/es24f_960w_drivetray.png
  src/assets/images/hardware/es24f/es24f_960w_drivetray_bg.png
  src/assets/images/hardware/es24f/es24f_960w_drivetray_handle.png
Labels: backport-22.12.2

#7833 NAS-120376 / 23.10 / Storage - Manage Devices incorrectly presents the "EXTEND button for member disks in RAIDZ VDEVs"
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
Labels: backport-22.12.2

#7832 NAS-120403 / 22.12.2 / Fixed validator
  src/app/services/gpu/isolated-gpu-validator.service.spec.ts
  src/app/services/gpu/isolated-gpu-validator.service.ts
Labels: backport-23.10
