Repository truenas/webui, pull requests merged in 2023-03, with the labels that each got.

#7847 NAS-120469 / 23.10 / Kerberos Realms Screen Action Dropdown has Two Add Options
  src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
  src/app/modules/layout/components/admin-layout/admin-layout.component.ts
  src/app/modules/layout/components/navigation/navigation.component.html
  src/app/modules/layout/components/navigation/navigation.component.ts
  src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
  src/app/services/navigation/navigation.service.ts
Labels: backport-22.12.2

#7843 NAS-120489 / 23.10 / [SCALE/Apps]: Setting on a causes it to be locked even at install time.
  src/app/services/schema/app-shema.transformer.ts
Labels: backport-22.12.2

#7849 NAS-120510 / 23.10 / Nextcloud cron settings were not recognized during installation.
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/services/schema/app-schema.helpers.ts
  src/app/services/schema/app-schema.service.spec.ts
  src/app/services/schema/app-schema.service.ts
  src/app/services/schema/app-shema.transformer.ts
Labels: backport-22.12.2

#7839 NAS-120381 / 22.12.2 / Calculate slot when no disk is present
  src/app/pages/system/view-enclosure/classes/chassis-view.ts
Labels: backport-23.10

#7817 NAS-120444 / 13.0 / Passwords don't match error when they do
  src/app/pages/common/entity/entity-form/validators/at-least-one-validation.ts
  src/app/pages/common/entity/entity-form/validators/compare-validation.ts
  src/app/pages/common/entity/entity-form/validators/password-validation.ts
  src/app/services/validation.service.ts
Labels: backport-23.10

#7855 NAS-120493 / 23.10 / [SCALE/Apps]: Weird behaviour with show_if under subquestions
  src/app/services/schema/app-schema.service.ts
Labels: backport-22.12.2

#7859 NAS-120492 / 23.10 / [SCALE/Apps]: Initial value of a dropdown is null, but after picking something and reverting to empty is no longer null
  src/app/services/schema/app-schema.service.ts
Labels: backport-22.12.2

#7875 NAS-120361 / 22.12.2 / Mini R Enclosure View should not have Identify Drive button
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-23.10

#7882 NAS-120469 / 23.10 / Add actions fix
  src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
Labels: backport-22.12.3

#7886 NAS-120621 / 23.10 / Leading whitespaces lost when displaying logs
  src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.html
  src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.scss
  src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
Labels: backport-22.12.2, backport-22.12.3

#7852 NAS-120268 / 23.10 / Show description for PCI passthrough devices choices
  src/app/interfaces/option.interface.ts
  src/app/interfaces/vm-device.interface.ts
  src/app/modules/ix-forms/classes/simple-async-combobox-provider.ts
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox-provider.ts
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.html
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.scss
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
  src/app/pages/vm/devices/device-form/device-form.component.ts
Labels: backport-22.12.2

#7883 NAS-120533 / 23.10 / UI does not allow for EXTEND operations on single-device special VDEVs
  src/app/modules/common/dialog/info-dialog/info-dialog.component.scss
  src/app/pages/storage/components/manager/manager.component.html
  src/app/pages/storage/modules/devices/components/devices/devices.component.html
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
Labels: backport-22.12.3

#7919 NAS-121066 / 23.10 / add to LOC_FAILOVER_ONGOING HA disabled reasons
  src/app/enums/failover-disabled-reason.enum.ts
  src/app/helptext/topbar.ts
Labels: backport-22.12.3

#7934 NAS-121054 / 22.12.2 / Hide identify button for R30
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-23.10, backport-22.12.3

#7917 NAS-121043 / 23.10 / webUI is showing incorrect warning
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-22.12.3

#7941 NAS-121043 / 22.12.3 / webUI is showing incorrect warning (by AlexKarpov98)
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-22.12.2

#7903 NAS-121010 / 23.10 / Attempting to enable samba authentication on user blocked on UI
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-22.12.2, backport-22.12.3

#7918 NAS-120268 / 23.10 / NAS-120268 - Show description for PCI passthrough devices choices
  src/app/interfaces/option.interface.ts
  src/app/modules/ix-forms/classes/simple-async-combobox-provider.ts
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox-provider.ts
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.html
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.scss
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
  src/app/pages/vm/devices/device-form/device-form.component.ts
Labels: backport-22.12.2

#7960 NAS-121116 / 23.10 / Advanced Options on Replication Page dumps user back to Replication Page
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
Labels: backport-22.12.2, backport-22.12.3

#7999 NAS-121183 / 23.10 / Hide `Enable Atime` for Zvol
  src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
  src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.spec.ts
Labels: backport-22.12.3

#8001 NAS-121150 / 23.10 / Update R50 dashboard picture in webui
  src/assets/images/servers/R50.png
Labels: backport-22.12.3

#7997 NAS-119556 / 22.12.3 / Hidden button when not needed
  src/app/pages/network/components/open-vpn-client-config/open-vpn-client-config.component.html
  src/app/pages/network/components/open-vpn-client-config/open-vpn-client-config.component.ts
  src/app/pages/network/components/open-vpn-server-config/open-vpn-server-config.component.html
  src/app/pages/network/components/open-vpn-server-config/open-vpn-server-config.component.ts
Labels: backport-23.10

#7990 NAS-120508 / 23.10 / WebUI validation of VDEV redundancy across VDEV types
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
  src/app/services/storage.service.spec.ts
  src/app/services/storage.service.ts
Labels: backport-22.12.3
