Repository truenas/webui, pull requests merged in 2023-08, with the labels that each got.

#8513 NAS-123311 / 24.04 / Update link to Disk reports
  src/app/pages/reports-dashboard/reports-dashboard.routing.ts
  src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.html
  src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts
Labels: backport-23.10, backport-23.10-beta.1

#8509 NAS-123101 / 24.04 / MinIO Enterprise Configured for SNMD Stuck in Deploying
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/services/schema/app-schema.service.ts
  src/app/services/schema/app-schema.transformer.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8510 NAS-123321 / 24.04 / Updating options when inventory changes
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8507 NAS-122920 / 24.04 / Don't refresh table until the job has concluded
  src/app/pages/data-protection/data-protection-dashboard.component.ts
Labels: backport-23.10

#8511 NAS-123319 / 24.04 / The Layout Selection Field is Missing When Creating a New Pool Using The New Pool Creation Wizard After Adding a Disk to an Existing Pool Using The New Pool Creation Wizard
  src/app/pages/storage/modules/pool-manager/components/add-vdevs/store/add-vdevs-store.service.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8506 NAS-122401 / 24.04 / Correct capitalization in TrueNAS on apps views
  src/app/pages/apps/apps.module.ts
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.scss
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-helm-chart-card/app-helm-chart-card.component.html
  src/app/pages/apps/components/app-detail-view/app-helm-chart-card/app-helm-chart-card.component.spec.ts
  src/app/pages/apps/components/available-apps/app-card/app-card.component.html
  src/app/pages/apps/components/available-apps/app-card/app-card.component.spec.ts
  src/app/pages/apps/components/catalogs/catalog-edit-form/catalog-edit-form.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
  src/app/pages/apps/utils/app-catalog.pipe.spec.ts
  src/app/pages/apps/utils/app-catalog.pipe.ts
  src/assets/i18n/uk.json
Labels: backport-23.10

#8523 NAS-123306 / 23.10 / Returning observable instead of array
  src/app/pages/dashboard/store/dashboard-storage-store.service.ts
Labels: backport-23.10-BETA.1, backport-24.04

#8533 NAS-123055 / 24.04 / Missing focus states for checkboxes
  src/assets/styles/other/_root-variables.scss
Labels: backport-23.10, backport-22.12.4

#8534 NAS-123366 / 23.10 / Getting status from localStorage
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
Labels: backport-24.04

#8512 NAS-122296 / 24.04 / Update time interval when manual zoom on Reports
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/reports-dashboard/reports-dashboard.module.ts
Labels: backport-23.10

#8548 NAS-123432 / 24.04 / Link to learn more about Host Allow in SMB, points to 404
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8532 NAS-122993 / 24.04 / No tooltip appeared when hovering the mouse on the icons on tables
  src/app/modules/entity/table/table.component.html
Labels: backport-23.10, backport-22.12.4

#8560 NAS-123415 / 24.04 / "Mixing vdev layouts not allowed" error appears when creating a new pool
  src/app/pages/storage/modules/pool-manager/components/add-vdevs/store/add-vdevs-store.service.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8537 NAS-123351 / 24.04 / Takeout `checkForUpdate`
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/services/error-handler.service.spec.ts
  src/app/services/error-handler.service.ts
Labels: backport-23.10

#8566 NAS-123450 / 24.04 / New Pool Creation wizard - multiple enclosures button states incorrect
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8574 NAS-123480 / 24.04 / WebDAV Install missing "Add Share" button. produces error unable to resolve
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/assets/i18n/fr.json
Labels: backport-23.10, backport-23.10-BETA.1

#8527 NAS-123336 / 24.04 / WebUI tooltips are malfunctioning in chrome
  src/app/app.module.ts
  src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
  src/assets/styles/other/_material-reduction.scss
Labels: backport-23.10, backport-22.12.4

#8584 NAS-123362 / 23.10 / Removed calls interval when component has closed
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Labels: backport-24.04

#8593 NAS-123526 / 24.04 / Extend session may appear when there is no active connection
  src/app/services/token-lifetime.service.ts
Labels: backport-23.10, backport-22.12.4

#8602 NAS-123391 / 24.04 / Cannot Stop App Stuck In Deploying from New Apps UI
  src/app/modules/page-header/page-title-header/page-title-header.component.scss
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-23.10

#8623 NAS-123577 / 24.04 / CVE-2023-3481 identified against component critters in Wambui repo
  package.json
  yarn.lock
Labels: backport-23.10

#8582 NAS-123151 / 24.04 / HA: Alert is duplicated
  src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
  src/app/modules/alerts/store/alert.actions.ts
  src/app/modules/alerts/store/alert.effects.ts
  src/app/modules/alerts/store/alert.reducer.ts
Labels: backport-23.10, backport-22.12.4

#8617 NAS-123536 / 24.04 / The Storage Widget Continues to Display After a Pool has Been Exported On The Dashboard
  src/app/pages/dashboard/store/dashboard-storage-store.service.ts
  src/app/pages/dashboard/store/dashboard-store.service.ts
Labels: backport-23.10

#8634 NAS-122843 / 24.04 / Don't show dict form section if no attributes to show
  src/app/services/schema/app-schema.service.ts
Labels: backport-23.10, backport-23.10-BETA.1

#8633 NAS-123358 / 24.04 / Don't initialize observable so loading is shown on select
  src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
Labels: backport-23.10, backport-22.12.3

#8637 NAS-123284 / 23.10 / Unable to add spares in new Pool Creation Wizard
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
Labels: backported

#8647 NAS-121466 / 24.04 / Topology overview hides VDEV information if there is a warning for redundancy mismatch
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
Labels: backport-23.10, backport-22.12.4

#8646 NAS-123647 / 24.04 / Add Replication Task Advanced Form [SAVE] button - is always active
  src/app/pages/data-protection/replication/replication-form/properties-override-validator/properties-override-validator.service.ts
  src/app/pages/data-protection/replication/replication-form/replication-form.component.html
  src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
Labels: backport-23.10

#8604 NAS-122287 / 24.04 / Reporting: Graph resets from a past date/time to current date/time when change the zoom increment
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
Labels: backport-23.10

#8652 NAS-115255 / 24.04 / Persist theme choice in localstorage
  src/app/modules/layout/components/auth-layout/auth-layout.component.ts
  src/app/pages/system/general-settings/gui/gui-form/gui-form.component.ts
  src/app/services/theme/theme.service.ts
  src/app/views/sessions/signin/signin.component.scss
  src/index.html
Labels: backport-23.10, backport-22.12.4

#8654 NAS-122287 / 23.10 / Reporting: Graph resets from a past date/time to current date/time when change the zoom increment (by AlexKarpov98)
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
Labels: backport-22.12.4

#8653 NAS-122321 / 23.10 / Text field unreadable (by AlexKarpov98)
  src/app/pages/data-protection/data-protection-dashboard.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
Labels: backport-22.12.4

#8626 NAS-123151 / 23.10 / HA: Alert is duplicated (by AlexKarpov98)
  src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
  src/app/modules/alerts/store/alert.actions.ts
  src/app/modules/alerts/store/alert.effects.ts
  src/app/modules/alerts/store/alert.reducer.ts
Labels: backport-22.12.4

#8643 NAS-123634 / 24.04 / Logs/Shell button is missing for apps that are in "Deploying" state
  src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html
Labels: backport-23.10

#8621 NAS-123426 / 24.04 / Fix default home path
  src/app/pages/account/users/user-form/user-form.component.spec.ts
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-23.10

#8644 NAS-123405 / 24.04 / Basic Options Cannot Save Due to Hidden Advanced Options Error On The Active Directory Setup Screen
  src/app/pages/directory-service/components/active-directory/active-directory.component.html
  src/app/pages/directory-service/components/active-directory/active-directory.component.spec.ts
Labels: backport-23.10

#8676 NAS-123521 / 24.04 / Show readonly layout field for Data VDEVs when adding disks to existing pool
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
Labels: backport-23.10

#8661 NAS-123642 / 24.04 / Fix reordering on dashboard
  src/app/pages/dashboard/components/dashboard/dashboard.component.html
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.scss
  src/app/pages/dashboard/components/widget-pool-wrapper/widget-pool-wrapper.component.html
  src/app/pages/dashboard/components/widget-pool/widget-pool.component.scss
  src/app/pages/dashboard/store/dashboard-store.service.ts
Labels: backport-23.10

#8681 NAS-123675 / 24.04 / Fixes for app info card
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: backport-23.10

#8690 NAS-123695 / 24.04 / Bug – fast clicking user can click on Data, but end up on Enclosure Options
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
  src/app/pages/storage/modules/pool-manager/enums/pool-creation-wizard-step.enum.ts
Labels: backport-23.10

#8689 NAS-123633 / 24.04 / Sync app status across tabs and other fixes to Apps
  src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.scss
  src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.scss
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/apps/services/applications.service.ts
  src/app/pages/apps/store/installed-apps-store.service.spec.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-23.10

#8702 NAS-123812 / 24.04 / Fix logo mobile safari and removed duplicate Pool word
  src/app/modules/layout/components/topbar/topbar.component.scss
  src/app/pages/dashboard/components/widget-controller/widget-controller.component.html
  src/app/pages/dashboard/components/widget-controller/widget-controller.component.ts
Labels: backport-23.10

#8692 NAS-123312 / 24.04 / The Text “2 warnings” is Displayed Without Any Description When a Pool Contains Stripe VDev’s of Differing Sizes On the Storage Dashboard
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
Labels: backport-23.10
