Repository truenas/webui, pull requests merged in 2023-04, with the labels that each got.

#8022 NAS-121215 / 22.12.3 / Reduce memory leak in `ix-entity-table` component
  src/app/modules/entity/entity-table/entity-table.component.ts
  src/app/modules/entity/entity-table/entity-table.interface.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
  src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
  src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
  src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
  src/app/pages/data-protection/snapshot/snapshot-task/snapshot-task.component.ts
Labels: backport-23.10

#8029 NAS-121308: Resolve issues with old-style timeFormat
  src/app/core/pipes/format-datetime.pipe.spec.ts
  src/app/core/pipes/format-datetime.pipe.ts
Labels: backport-22.12.3

#8024 NAS-121244 / 23.10 / The Custom Schedule window displays partially off screen When viewing the Periodic Snapshots Custom Schedule window on the Data Protection Page.
  src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-22.12.3

#8034 NAS-121342 / 22.12.3 / Fix rear NVME drives on M Series
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-22.12.2

#8023 NAS-121222 / 23.10 / Update `shell` field
  src/app/interfaces/api-directory.interface.ts
  src/app/pages/account/users/user-form/user-form.component.html
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-22.12.3

#8051 NAS-121274 / 23.10 / Prevent empty value in Wipe Disk dialog
  src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.html
  src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts
Labels: backport-22.12.3

#8052 NAS-121247 / 23.10 / TrueNAS SCALE - RangeError: Invalid time value on UI
  src/app/core/pipes/format-datetime.pipe.ts
  src/app/pages/system/general-settings/localization/localization-form/localization-form.component.ts
  src/app/services/locale.service.ts
Labels: backport-22.12.3

#8059 NAS-121384 / 23.10 / Telegram alerts can't be setup due to negative chat ID
  src/app/pages/system/alert-service/alert-service/alert-services/telegram-service/telegram-service.component.ts
Labels: backport-22.12.3

#8072 NAS-121445 / 23.10 / Trivial: Waiting to renew Kerberos ticket. Current ticketexpires
  src/app/modules/jobs/components/jobs-panel/jobs-panel.component.spec.ts
  src/app/modules/jobs/components/jobs-panel/jobs-panel.component.ts
  src/app/modules/jobs/store/job.selectors.ts
Labels: backport-22.12.3

#8083 NAS-121470 / 23.10 / Figure out a solution to the two apps installation bugs
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/services/schema/app-schema.service.spec.ts
  src/app/services/schema/app-schema.service.ts
Labels: backport-22.12.3

#8085 NAS-121557 / 23.10 / Disk information is not updated after editing in the disk table
  src/app/modules/entity/entity-table/entity-table.component.ts
Labels: backport-22.12.3

#7857 Validate iSCSI Target Name field
  src/app/helptext/sharing/iscsi/iscsi.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
Labels: backport-23.10

#8107 NAS-121547 / 23.10 / Fix Pool named "Storage" toggles Storage widget
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
Labels: backport-22.12.3
