Repository truenas/webui, pull requests merged in 2024-02, with the labels that each got.

#9568 NAS-127051 / 24.10 / Read only user : SMB Share > Edit Share ACL > Save button enabled
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.spec.ts
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
Labels: backport-24.04-RC.1

#9557 NAS-126983 / 24.10 / Share Page: iSCSI Service Status Label and Configure button UI overlap in different browser window sizes
  src/app/modules/entity/entity-table/entity-table.component.scss
  src/app/pages/credentials/backup-credentials/backup-credentials.component.scss
  src/app/pages/data-protection/data-protection-dashboard.component.scss
  src/app/pages/directory-service/directory-services.component.scss
  src/app/pages/network/components/network-configuration-card/network-configuration-card.component.scss
  src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.html
  src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.html
  src/app/pages/sharing/components/shares-dashboard/service-state-button/service-state-button.component.scss
  src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.html
  src/assets/styles/other/_material-reduction.scss
  src/assets/styles/other/_root-variables.scss
Labels: backport-24.04-RC.1

#9576 NAS-126976 / 24.10 / Slide In When Closed Is Not Setting Focus On The Button Which Triggered Slide In To Open
  src/app/app.module.ts
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.ts
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.ts
  src/app/services/focus.service.ts
  src/app/services/ix-chained-slide-in.service.ts
  src/app/services/ix-slide-in.service.ts
Labels: backport-24.04-RC.1

#9597 NAS-126976 / 24.10 / Focus service updates to correctly handle table reloading and loosing html ref & other improvements
  src/app/pages/directory-service/components/idmap-form/idmap-form.component.ts
  src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
  src/app/pages/directory-service/components/kerberos-settings/kerberos-settings.component.ts
  src/app/pages/directory-service/directory-services.component.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
  src/app/services/focus.service.ts
  src/app/services/ix-slide-in.service.ts
Labels: backport-24.04-RC.1

#9598 NAS-127170 / 24.10 / ix-table2 jumps when something is updated because of data hiding and spinner
  src/app/modules/ix-table2/classes/async-data-provider/async-data-provider.ts
  src/app/pages/system/alert-service/alert-service-list/alert-service-list.component.ts
Labels: backport-24.04-RC.1

#9592 NAS-127071 / 24.04-RC.1 / Add additional check for dialog display
  src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.html
  src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.ts
Labels: backport-24.10

#9580 NAS-127062 / 24.04-RC.1 / Dragonfish: Fix Enclosure pool/disk UI info incorrect when disk is pulled
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.scss
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-24.10

#9615 NAS-127009 / 24.10 / Add role support for Bulk Edit Disks form
  src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.html
  src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.spec.ts
  src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.ts
Labels: backport-24.04-RC.1

#9617 NAS-127107 / 24.10 / Log every EACCESS error
  src/app/services/websocket-connection.service.ts
  src/assets/i18n/fr.json
Labels: backport-24.04-RC.1

#9613 NAS-126977 / 24.10 / QA Mobile & Tablet (Forms / App UI) To Make It Look Better
  src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.scss
  src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.ts
  src/app/modules/page-header/page-title-header/page-title-header.component.scss
  src/app/pages/account/users/user-form/user-form.component.scss
  src/app/pages/api-keys/components/key-created-dialog/key-created-dialog.component.scss
  src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
  src/app/pages/credentials/certificates-dash/csr-list/csr-list.component.ts
  src/app/pages/dashboard/components/widget-backup/widget-backup.component.scss
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.scss
  src/app/pages/data-protection/replication/replication-form/replication-form.component.scss
  src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.scss
  src/app/pages/data-protection/snapshot-task/snapshot-task-form/snapshot-task-form.component.scss
  src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-settings/dataset-capacity-settings.component.scss
  src/app/pages/datasets/components/dataset-form/sections/quotas-section/quotas-section.component.scss
  src/app/pages/datasets/modules/encryption/components/encyption-options-dialog/encryption-options-dialog.component.ts
  src/app/pages/datasets/modules/permissions/components/strip-acl-modal/strip-acl-modal.component.scss
  src/app/pages/directory-service/components/active-directory/active-directory.component.scss
  src/app/pages/directory-service/components/ldap/ldap.component.scss
  src/app/pages/network/components/configuration/configuration.component.scss
  src/app/pages/network/components/ipmi-card/ipmi-events-dialog/ipmi-events-dialog.component.scss
  src/app/pages/network/components/network-configuration-card/network-configuration-card.component.scss
  src/app/pages/reports-dashboard/components/report/report.component.scss
  src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.scss
  src/app/pages/services/components/service-ftp/service-ftp.component.scss
  src/app/pages/services/components/service-nfs/service-nfs.component.scss
  src/app/pages/services/components/service-snmp/service-snmp.component.scss
  src/app/pages/services/components/service-ups/service-ups.component.scss
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-lock-list/smb-lock-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-lock-list/smb-lock-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.ts
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.ts
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.ts
  src/app/pages/storage/components/dashboard-pool/export-disconnect-modal/export-disconnect-modal.component.scss
  src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.scss
  src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.scss
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/manual-disk-selection.component.scss
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/manual-disk-selection.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.scss
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.scss
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/custom-layout-applied/custom-layout-applied.component.scss
  src/app/pages/system/advanced/sysctl/tunable-list/tunable-list.component.ts
  src/app/pages/system/alert-config-form/alert-config-form.component.scss
  src/app/pages/system/general-settings/support/proactive/proactive.component.scss
  src/app/pages/system/general-settings/support/support-card/support-card.component.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.04-RC.1

#9450 NAS-126020 / 24.04 / Adapt IPMI changes for UI
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/interfaces/failover.interface.ts
  src/app/interfaces/ipmi.interface.ts
  src/app/pages/network/components/ipmi-card/ipmi-form/ipmi-form.component.html
  src/app/pages/network/components/ipmi-card/ipmi-form/ipmi-form.component.spec.ts
  src/app/pages/network/components/ipmi-card/ipmi-form/ipmi-form.component.ts
Labels: blocked, backport-24.04-RC.1

#9643 NAS-127110 / 24.10 / ix-table-columns-selector columns -> reset to default hides all columns/rows values & Select/Unselect all works with glitches
  src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.html
  src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.spec.ts
  src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.ts
Labels: backport-24.04-RC.1

#9665 NAS-127010 / 24.10 / Readonly user > Reporting exporters enabled/disabled controls active
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.html
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.spec.ts
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.ts
Labels: backport-24.04-RC.1

#9652 NAS-127273 / 24.10 / Data Protection → Next Run shows value for disabled tasks miss-match between card and list
  src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-relative-date/ix-cell-relative-date.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.spec.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
  src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
  src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.spec.ts
  src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.ts
  src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.spec.ts
  src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
  src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.spec.ts
  src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.ts
  src/app/pages/data-protection/scrub-task/scrub-task-card/scrub-task-card.component.spec.ts
  src/app/pages/data-protection/scrub-task/scrub-task-card/scrub-task-card.component.ts
  src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.spec.ts
  src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.ts
  src/app/pages/data-protection/snapshot-task/snapshot-task-list/snapshot-task-list.component.ts
  src/app/pages/system/advanced/cron/cron-card/cron-card.component.ts
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.spec.ts
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
Labels: backport-24.04-RC.1

#9666 NAS-127011 / 24.10 / Readonly user > Storage > ZFS Health - Edit Auto Trim > Save button enabled
  src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.html
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
Labels: backport-24.04-RC.1

#9675 NAS-127297 / 23.10.3 / Fix Folder does not show up when editing already created cloud sync tasks (Pull/copy)
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
Labels: backport-23.10.2, backport-24.04-RC.1, backport-24.10

#9684 NAS-127177 / 24.10 / System Audit > Event Data, "Copy JSON" option is not in JSON format
  src/app/core/components/copy-btn/copy-btn.component.ts
Labels: backport-24.04-RC.1

#9693 NAS-127049 / 24.10 / Read only user > SMB shares table > Delete - confirmationbox Unshare is not disabled
  src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Labels: backport-24.04-RC.1

#9701 NAS-127356 / 24.10 / Dragonfish: data-test tag missing from Local Groups page size select and options
  src/app/modules/ix-table2/components/ix-table-pager/ix-table-pager.component.html
  src/app/modules/ix-tables/components/ix-table-paginator/ix-table-paginator-test-attributes.directive.ts
  src/app/modules/ix-tables/components/ix-table-paginator/ix-table-paginator.component.html
  src/app/modules/ix-tables/ix-table.module.ts
Labels: backport-24.04-RC.1

#9704 NAS-121641 / 24.10 / Fix container image update dialog
  src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.spec.ts
  src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.ts
  src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
Labels: backport-24.04-RC.1

#9708 NAS-127417 / 24.04-RC.1 / Lock icon for restricted elements
  src/app/directives/common/common-directives.module.ts
  src/app/directives/common/requires-roles/requires-roles-wrapper.component.html
  src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
  src/app/directives/common/requires-roles/requires-roles-wrapper.component.ts
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.html
  src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
  src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
  src/app/pages/datasets/modules/encryption/components/zfs-encryption-card/zfs-encryption-card.component.html
  src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.html
  src/app/pages/services/components/service-ftp/service-ftp.component.html
  src/app/pages/services/components/service-ftp/service-ftp.component.scss
  src/app/pages/services/components/service-nfs/service-nfs.component.html
  src/app/pages/services/components/service-nfs/service-nfs.component.scss
  src/app/pages/services/components/service-smart/service-smart.component.html
  src/app/pages/services/components/service-smb/service-smb.component.html
  src/app/pages/services/components/service-smb/service-smb.component.scss
  src/app/pages/services/components/service-snmp/service-snmp.component.html
  src/app/pages/services/components/service-snmp/service-snmp.component.scss
  src/app/pages/services/components/service-ssh/service-ssh.component.html
  src/app/pages/services/components/service-ups/service-ups.component.html
  src/app/pages/services/services.component.html
  src/app/pages/services/services.component.scss
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
  src/app/pages/system/update/update.component.scss
Labels: backport-24.10

#9712 NAS-127435 / 24.10 / Fix layout width on mobile screens
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.scss
Labels: backport-24.04-RC.1

#9700 NAS-127377 / 24.10 / The Add button on the Certificates and Certificate Signing Requests has the same data-test tag.
  src/app/pages/credentials/certificates-dash/csr-list/csr-list.component.html
Labels: backport-24.04-RC.1

#9720 NAS-127424 / 24.10 / Add role checks for failover
  src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.html
  src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.ts
  src/app/pages/system/failover-settings/failover-settings.component.html
  src/app/pages/system/failover-settings/failover-settings.component.spec.ts
  src/app/pages/system/failover-settings/failover-settings.component.ts
Labels: backport-24.04-RC.1

#9731 NAS-127507 / 24.10 / Shell UI under System Settings is missing for restricted …
  src/app/directives/common/common-directives.module.ts
  src/app/directives/common/has-access/has-access.directive.spec.ts
  src/app/directives/common/has-access/has-access.directive.ts
  src/app/directives/common/has-access/missing-access-wrapper.component.html
  src/app/directives/common/has-access/missing-access-wrapper.component.scss
  src/app/directives/common/has-access/missing-access-wrapper.component.ts
  src/app/directives/common/requires-roles/requires-roles.directive.ts
  src/app/interfaces/menu-item.interface.ts
  src/app/modules/layout/components/secondary-menu/secondary-menu.component.html
  src/app/modules/layout/components/secondary-menu/secondary-menu.component.ts
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.html
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.spec.ts
  src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
  src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
  src/app/services/navigation/navigation.service.ts
Labels: backport-24.04-RC.1

#9736 NAS-127515 / 24.10 / Add codename to system info widget
  src/app/enums/codename.enum.ts
  src/app/interfaces/system-info.interface.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
Labels: backport-24.04-RC.1

#9744 NAS-127400 / 24.10 / Cloud Sync Tasks: State does not refresh after stopping
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
Labels: backport-24.04-RC.1

#9737 NAS-127505 / 24.04-RC.1 / UI submitting duplicate issue reports
  src/app/modules/oauth-button/components/oauth-button/oauth-button.component.ts
  src/app/pages/system/general-settings/support/support-card/support-card.component.ts
  src/app/services/error-handler.service.spec.ts
  src/app/services/error-handler.service.ts
Labels: backport-24.10
