Repository truenas/webui, pull requests merged in 2024-06, with the labels that each got.

#10139 NAS-129397 / 24.10 / Reworded MismatchNics
  src/app/helptext/topbar.ts
Labels: jira

#10168 NAS-129334 / 24.04.2 / Fix Dashboard is not loading
  src/app/pages/dashboard/components/widget-network/widget-network.component.scss
  src/app/pages/dashboard/store/resources-usage-store.service.ts
Labels: backport-24.10

#10178 NAS-129528 / 24.04.2 / ACL forms are broken when directory services cache is dis…
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.harness.ts
  src/app/pages/datasets/modules/permissions/components/edit-nfs-ace/edit-nfs-ace.component.html
  src/app/pages/datasets/modules/permissions/components/edit-nfs-ace/edit-nfs-ace.component.spec.ts
  src/app/pages/datasets/modules/permissions/components/edit-posix-ace/edit-posix-ace.component.html
  src/app/pages/datasets/modules/permissions/components/edit-posix-ace/edit-posix-ace.component.spec.ts
Labels: backport-24.10

#10205 NAS-129391 / 24.04.2 / Can't edit iSCSI Target on SCALE
  src/app/pages/sharing/iscsi/target/target-form/target-form.component.html
  src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.html
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: backport-24.10

#10218 NAS-129198 / 24.10 / Update enabled field after change
  src/app/helpers/operators/accumulate-loading-state.helper.ts
  src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
Labels: backport-24.04.1
