Repository truenas/webui, pull requests merged in 2024-11, with the labels that each got.

#10973 NAS-132245 / 25.04 / Apps without ixVolumes cannot be removed
  src/app/modules/dialog/components/confirm-dialog/confirm-dialog.component.spec.ts
  src/app/modules/dialog/components/confirm-dialog/confirm-dialog.component.ts
Labels: backport-24.10.1

#10961 NAS-132190 / 25.04 / Update wording for Storj Description and links
  src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.html
  src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.ts
Labels: backport-24.10.1

#10965 NAS-131761 / 25.04 / Enabled toggle in Shares>NFS does not work
  src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
Labels: backport-24.10.1

#10981 NAS-132076 / 25.04 / Interface to start / stop a container/app is hidden at default zoom level
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
  src/app/pages/apps/components/installed-apps/app-state-cell/app-state-cell.component.scss
  src/app/pages/apps/components/installed-apps/installed-apps.component.scss
Labels: backport-24.10.1

#10995 NAS-132159 / 25.04 / Remove workaround for custom_app
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10.1

#11001 NAS-132227 / 25.04 / Fix enable change in SMB table
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Labels: backport-24.10.1

#11024 NAS-132328 / 25.04 / Apps - Lists do not show `description` (tooltip)
  src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
Labels: backport-24.10.1

#11026 NAS-132230 / 25.04 / UI issue with DEPRECATED: Old Storage Structure in Nextcloud Install Wizard
  src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.scss
  src/assets/i18n/fr.json
Labels: backport-24.10.1

#11056 NAS-132526 / 25.04 / Line wrap "Log Excerpt" text on jobs page
  src/app/pages/jobs/job-logs-row/job-logs-row.component.scss
Labels: backport-24.10.1

#11057 NAS-132581 / 25.04 / NAS-132550: Restricted admin - cloud sync task details not loaded
  src/app/modules/forms/ix-forms/components/readonly-badge/readonly-badge.component.scss
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
Labels: backport-24.10.1

#11055 NAS-132517 / 25.04 / Cloud credentials storJ text does not render link correctly
  src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.component.html
  src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.component.spec.ts
Labels: backport-24.10.1

#11082 NAS-132485 / 25.04 / Search is always lowercase on Users page
  src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
  src/app/pages/credentials/groups/group-list/group-list.component.ts
  src/app/pages/credentials/users/user-list/user-list.component.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.spec.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
  src/app/pages/data-protection/smart-task/smart-task-list/smart-task-list.component.ts
  src/app/pages/data-protection/vmware-snapshot/vmware-snapshot-list/vmware-snapshot-list.component.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-list/dataset-quotas-list.component.ts
  src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
  src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.ts
  src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.ts
  src/app/pages/services/services.component.ts
  src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts
  src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
  src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
  src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
  src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
  src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
  src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.ts
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
  src/app/pages/system/advanced/sysctl/tunable-list/tunable-list.component.ts
  src/app/pages/system/enclosure/components/jbof-list/jbof-list.component.ts
  src/app/pages/vm/devices/device-list/device-list/device-list.component.ts
  src/app/pages/vm/vm-list.component.ts
Labels: backport-24.10.1

#11076 NAS-132108 / 24.10.1 / Add support for name selection from old pool widgets
  src/app/pages/dashboard/services/widget-resources.service.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.definition.ts
Labels: backport-25.04

#11081 NAS-131245 / 25.04 / UI obscures error messages
  src/app/interfaces/api-error.interface.ts
  src/app/services/websocket/api.service.ts
Labels: backport-24.10.1

#11101 NAS-131841 / 25.04 / ACL Editor Group/User Search Bug
  src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.html
  src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.ts
Labels: backport-24.10.2

#11013 NAS-131595 / 25.04 / Prepare redirect URL for IPv6
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: backport-24.10.1

#11115 NAS-128390 / 25.04 / Adjust min child count when creating draid pools
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.ts
Labels: backport-24.10.2
