Repository truenas/webui, pull requests merged in 2024-05, with the labels that each got.

#10020 NAS-128515 / 24.04.1 / Fixes stats logic on Installed apps page
  src/app/interfaces/api/api-event-directory.interface.ts
  src/app/interfaces/chart-release.interface.ts
  src/app/pages/apps/components/apps-scope-wrapper.component.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/apps/services/applications.service.ts
  src/app/pages/apps/store/apps-statistics.service.spec.ts
  src/app/pages/apps/store/apps-statistics.service.ts
  src/app/pages/apps/store/apps-store.service.ts
  src/app/pages/apps/store/installed-apps-store.service.spec.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10

#10033 NAS-128395 / 24.04.1 / Rebooting on FIPS changes
  src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
Labels: backport-24.10

#10037 NAS-128703 / 24.04.1 / Only 11 Cloud sync tasks are shown, "items per page" is missing
  src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.html
  src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.html
  src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.html
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
Labels: backport-24.10

#10043 NAS-128453 / 24.10 / More support for new enclosure UI
  src/app/core/testing/utils/mock-enclosure.utils.ts
  src/app/core/testing/utils/mock-storage-generator.utils.ts
  src/app/enums/enclosure-slot-status.enum.ts
  src/app/interfaces/enclosure.interface.ts
  src/app/pages/dashboard-old/components/widget-pool/widget-pool.component.ts
  src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
  src/app/pages/system/enclosure/components/enclosures/drive-tray/drive-tray.component.scss
  src/app/pages/system/enclosure/components/enclosures/drive-tray/drive-tray.component.svg
  src/app/pages/system/enclosure/components/enclosures/drive-tray/drive-tray.component.ts
  src/app/pages/system/enclosure/components/enclosures/m50-enclosure/m50-enclosure.component.ts
  src/app/pages/system/enclosure/tests/mocks/README
  src/app/pages/system/enclosure/tests/mocks/m40.ts
  src/app/pages/system/enclosure/tests/mocks/m60-with-12-es102.ts
  src/app/pages/system/old-view-enclosure/components/enclosure-disks/enclosure-disks.component.html
  src/app/pages/system/old-view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: skip jira status

#10030 NAS-128488 / 24.10 / Cleanup `initialOptions` after adding
  src/app/modules/ix-forms/classes/group-combobox-provider.ts
  src/app/modules/ix-forms/classes/smb-group-combobox-provider.ts
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
Labels: backport-24.04.2

#10053 NAS-128881 / 24.04.1 / Removes suggestions from feedback form
  src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.spec.ts
  src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.ts
Labels: backport-24.10, backport-24.04.2

#10081 NAS-129063 / 24.04.1 / Initiate Failover button is inactive but HA is up
  src/app/store/ha-info/ha-info.selectors.ts
Labels: backport-24.10, backport-24.04.2

#10118 NAS-129244 / 24.10 / Revert "NAS-129212 / 24.10 / Upgrade to Angular 18 (#10108)"
  angular.json
  package.json
  src/app/app.module.ts
  src/app/core/testing/utils/suppress-jsdom-css-errors.utils.ts
  src/app/modules/scheduler/components/scheduler-modal/scheduler-preview-column/scheduler-preview-column.component.spec.ts
  src/app/modules/scheduler/scheduler.module.ts
  src/app/modules/truecommand/truecommand.module.ts
  src/app/pages/account/groups/group-members/group-members.component.spec.ts
  src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.spec.ts
  src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.spec.ts
  src/app/services/ix-file-upload.service.ts
  src/app/store/ha-info/ha-info.selectors.ts
  src/assets/styles/other/_material-overrides.scss
  src/assets/styles/other/_tn-styles.scss
  src/index.html
  tsconfig.json
  yarn.lock
Labels: jira

#10120 NAS-129253 / 24.10 / Add script to fetch prebuilt nodejs
  debian/fetch_node.sh
Labels: jira
