Repository truenas/webui, pull requests merged in 2024-04, with the labels that each got.

#9904 NAS-127913 / 24.10 / Network Graph does not update with live results unless refresh browser
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Labels: backport-24.04.0

#9897 NAS-127926 / 24.10 / Apps/UI - "Install" button remains disabled even if the form does not have validation errors (Only when selecting non-default version)
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
Labels: backport-24.04.0

#9909 NAS-127948 / 24.10 / Dragonfish: Restore Snapshot dialog rendering not consistent with other dialogs
  src/app/pages/datasets/modules/snapshots/snapshot-rollback-dialog/snapshot-rollback-dialog.component.html
Labels: backport-24.04.0

#9954 NAS-128303 / 24.04.0 / Fixing enclosure view for m50 systems
  src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts
Labels: backport-24.04.1

#9929 NAS-128045 / 24.10 / Apps Install UI Dropdown field show "x" instead of dropdown indicator
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.html
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.scss
  src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.04.1

#9956 NAS-128334 / 24.04.1 / Fix chassis for ES24N
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-24.10, backport-24.04.0

#9952 NAS-127893 / 24.10 / Fix `hasMultipleEnclosuresAfterFirstStep$` selector
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
Labels: backport-24.04.1

#9972 NAS-128397 / 24.04.0 / Restore change password form for limited users
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
Labels: backport-24.10, backport-24.04.1

#9987 Ensure multiline App "Section help" can be rendered
  src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.html
  src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.scss
Labels: backport-24.04.1

#9994 NAS-128442 / 24.04.1 / Fix enclosure finding bug
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-24.04.1

#9999 NAS-128343 / 24.10 / Checking Autoconfigure IPv6 hides IPv4 Aliases
  src/app/pages/network/components/interface-form/interface-form.component.spec.ts
  src/app/pages/network/components/interface-form/interface-form.component.ts
Labels: backport-24.04.1
