Repository truenas/webui, pull requests merged in 2024-03, with the labels that each got.

#9757 NAS-127582 / 24.10 / Performing advanced query in webui audit form appears to submit query payload twice
  src/app/modules/ix-table2/classes/api-data-provider/api-data-provider.ts
  src/app/pages/account/groups/privilege/privilege-list/privilege-list.component.ts
  src/app/pages/audit/components/audit/audit.component.ts
Labels: backport-24.04.0

#9751 NAS-127546 / 24.10 / App Install Page Layout is incorrect
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.html
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.scss
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.04.0

#9788 NAS-127670 / 24.10 / Save debug is disabled but debug can still be downloaded
  src/app/pages/system/advanced/save-debug-button/save-debug-button.component.html
  src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
Labels: backport-24.04.0

#9793 NAS-127719 / 24.04.0 / Do not offer service dialogs if user does not have access
  src/app/helpers/operators/filter-async.operator.ts
  src/app/modules/common/dialog/start-service-dialog/start-service-dialog.component.html
  src/app/modules/common/dialog/start-service-dialog/start-service-dialog.component.ts
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/pages/services/services.component.html
  src/app/pages/services/services.component.ts
  src/app/pages/system/update/update.component.ts
  src/app/services/services.service.ts
  src/app/store/eula/eula.effects.ts
  src/app/store/network-interfaces/network-interfaces.effects.ts
  src/app/store/services/services.effects.spec.ts
  src/app/store/services/services.effects.ts
Labels: backport-24.04-RC.1, backport-24.10

#9797 NAS-127703 / 24.04.0 / Tick icon and Pop out icon are displayed overlapping on Dashboard Backup Tasks Widget
  src/app/pages/dashboard/components/widget-backup/widget-backup.component.scss
  src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
Labels: backport-24.04-RC.1, backport-24.10

#9792 NAS-126935 / 24.04.0 / Remove new prompts
  src/app/pages/account/groups/groups.routing.ts
  src/app/pages/audit/audit.routing.ts
  src/app/pages/sharing/sharing.routing.ts
Labels: backport-24.10

#9787 NAS-127615 / 24.10 / Do not re-request count during shifts in pagination (do request recount if someone shifts to last offset)
  src/app/modules/ix-table2/classes/api-data-provider/audit-api-data-provider.ts
Labels: backport-24.04.0

#9773 NAS-127589 / 24.10 / Use new download VM logs endpoint in WebUI
  src/app/pages/vm/vm-list/vm-details-row/vm-details-row.component.html
  src/app/pages/vm/vm-list/vm-details-row/vm-details-row.component.ts
  src/app/services/vm.service.spec.ts
  src/app/services/vm.service.ts
Labels: backport-24.04.0

#9818 NAS-127589 / 24.04.0 / Use new download VM logs endpoint in WebUI (by denysbutenko)
  src/app/pages/vm/vm-list/vm-list.component.ts
Labels: backport-24.04-RC.1

#9808 NAS-127720 / 24.10 / Webui does not handle validation errors properly when creating SMB shares via "Add Dataset"
  src/app/pages/datasets/components/dataset-form/dataset-form.component.html
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/datasets/components/dataset-form/sections/encryption-section/encryption-section.component.ts
  src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.spec.ts
  src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.ts
  src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
  src/app/pages/datasets/components/dataset-form/sections/quotas-section/quotas-section.component.ts
  src/app/pages/sharing/smb/smb-form/smb-validator.service.ts
Labels: backport-24.04.0

#9825 NAS-127824 / 24.10 / Added `'/s'` to the graph tooltip and legend for Network widget on the dashboard
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/utils/report.utils.ts
Labels: backport-24.04-RC.1, backport-24.04.0

#9817 NAS-127782 / 24.10 / Fix WebUI fails to remove IP address from iSCSI portal
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.spec.ts
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
Labels: backported, backport-24.04.0

#9805 NAS-127736 / 24.04.0 / Fix failed and success states on backup tasks widget
  src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
Labels: backport-24.10

#9843 NAS-127022: Revert drive identification condition
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Labels: backport-24.04.0

#9840 NAS-127778 / 24.04.0 / Added check to open Advanced Options on error
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Labels: no-time-tracked

#9850 NAS-127796 / 24.04.0 / On Dragonfish nightly and RC.1 the reordering of the dashboard changes when going somewhere else and going to the dashboard.
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/store/dashboard-store.service.ts
Labels: backport-24.10

#9846 NAS-127854 / 24.04.0 / Show value only for selected report
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.html
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/reports-dashboard/interfaces/report.interface.ts
Labels: backport-24.10, backport-24.04.0

#9854 NAS-127603 / 24.04.0 / Added remove button for Spares for RaidZ pool
  src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
Labels: backport-24.10

#9851 NAS-127829 / 24.04.0 / Disks are displayed in a random order on the Disk I/O Reporting Page
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
  src/app/pages/reports-dashboard/reports.service.ts
Labels: backport-24.10

#9873 NAS-127844 / 24.04.0 / HA Support ticket: Open Ticket windows closes before I can click the button
  src/app/modules/feedback/services/feedback.service.spec.ts
  src/app/modules/feedback/services/feedback.service.ts
Labels: backport-24.10

#9891 NAS-128057 / 24.10 / Only open netdata once
  src/app/core/testing/utils/mock-window.utils.ts
  src/app/pages/reports-dashboard/reports.service.spec.ts
  src/app/pages/reports-dashboard/reports.service.ts
Labels: backport-24.04.0

#9893 NAS-127966 / 24.10 / Doing actions colapses the Dataset Tree
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
Labels: backport-24.04.0
