Repository truenas/webui, pull requests merged in 2024-10, with the labels that each got.

#10778 NAS-131437 / 25.04 / Restarting Plex container breaks migration mounts
  src/app/pages/apps/components/app-wizard/app-wizard.component.spec.ts
  src/app/services/schema/app-schema.service.ts
Labels: backport-24.10-RC.1, backport-24.10.0

#10773 NAS-130978 / 25.04 / Sort disks by size when Treat Disk Size As Minimum is selected
  src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs-treat-as-minimum.spec.ts
  src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
Labels: backport-24.10.0

#10769 NAS-131308 / 25.04 / First time accessing a Minio deployment the webui button launches portal is 0.0.0.0:30001
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: backport-24.10.0

#10787 NAS-126907 / 25.04 / `ix-explorer` accessibility improvements
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.scss
Labels: backport-24.10.0

#10793 NAS-130834 / 25.04 / App version vs Version is confusing
  src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
  src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
Labels: backport-24.10.0

#10797 NAS-131460 / 25.04 / UI should use `webui.crypto.csr_profiles` endpoint for CSR
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/pages/credentials/certificates-dash/csr-add/csr-add.component.spec.ts
  src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.spec.ts
  src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.ts
Labels: backport-24.10.0

#10791 NAS-131461 / 25.04 / Listen for apps stats only when have installed apps
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10

#10794 NAS-131020 / 25.04 / Network Widget doesn't show autoconfigured IPv6 address
  src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.spec.ts
  src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.ts
Labels: backport-24.10.0

#10823 NAS-131641 / 25.04 / Directory Services Cards -> Different card for Kerberos Settings
  src/app/pages/directory-service/directory-services.component.scss
Labels: backport-24.10.0

#10832 NAS-131667 / 25.04 / App Notes card does not show View More button until I resize window
  src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
Labels: backport-24.10.0

#10802 NAS-131266 / 25.04 / Cancel button takes back to apps page
  src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.spec.ts
  src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.ts
  src/app/pages/apps/components/logs-details-dialog/logs-details-dialog.component.html
Labels: backport-24.10.0

#10855 NAS-131712 / 25.04 / Apps | shell button is missing when application "Starting"
  src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html
Labels: backport-24.10.1

#10863 NAS-131746 / 25.04 / RAIDZ Expansion Dialog cannot be minimized or "backgrounded" preventing further UI operations
  src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts
Labels: backport-24.10.1

#10860 NAS-131713 / 25.04 / Apps | when an app is in crashed state all buttons for the container is missing
  src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html
Labels: backport-24.10.1

#10874 NAS-131824 / 25.04 / Add border to CPU widgets
  src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
Labels: jira, backport-24.10.1

#10888 NAS-131787 / 25.04 / Improper payload on re-saving the form
  src/app/pages/network/components/configuration/configuration.component.ts
Labels: backport-24.10.0, backport-24.10.1

#10897 NAS-131802 / 25.04 / Error with some dataset paths in pool creation
  src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.html
  src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.spec.ts
  src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.ts
  src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.html
Labels: backport-24.10.1

#10903 NAS-131800 / 25.04 / App details page does not scale / cropped on mobile
  src/assets/styles/mixins/cards.scss
Labels: backport-24.10.1

#10920 NAS-131848 / 25.04 / Remove the "current password" field from UI for FULL_ADMIN
  src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.html
  src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.spec.ts
  src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.ts
Labels: backport-24.10.0, backport-24.10.1

#10930 NAS-131984 / 25.04 / Apps Settings / Address Pools -> on save extra address pool added
  src/app/pages/apps/components/catalog-settings/apps-settings.component.ts
Labels: backport-24.10.1

#10918 NAS-131722 / 25.04 / Storj Bucket is created before `Add TrueCloud Backup Task` form successful submit
  src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
Labels: backport-24.10.1

#10938 NAS-127607 / 25.04 / Fix out of sync docker config between tabs
  src/app/pages/apps/components/apps-scope-wrapper.component.ts
  src/app/pages/apps/store/docker.store.ts
Labels: backport-24.10.1
