Repository truenas/webui, pull requests merged in 2024-01, with the labels that each got.

#9384 NAS-125832 / 23.10.2 / Removed unnecessary multiplication with KiB
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
  src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts
Labels: backport-23.10.1.1

#9387 NAS-125421 / 23.10.2 / Add check for undefined before concatenating values
  src/app/pages/dashboard/store/resources-usage-store.service.ts
Labels: backport-24.04

#9395 NAS-125832 / 23.10.2 / Reverting changes
  src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Labels: backport-23.10.1.1

#9400 NAS-125488 / 24.04 / Datasets: Dataset space management does not show the exact number, it shows the number as a rounded number.
  src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.html
Labels: backport-23.10.2

#9403 NAS-125777 / 23.10.2 / Added null check
  src/app/services/task.service.ts
Labels: backport-24.04

#9396 NAS-124814 / 23.10.2 / Handling case for no disks for a specific pool
  src/app/pages/storage/components/pools-dashboard/pools-dashboard.component.ts
Labels: backport-24.04

#9428 NAS-126723 / 24.04 / ix-explorer bug with comma once I clear input and select something
  src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
Labels: backport-23.10.2

#9445 NAS-125082 / 24.04 / Selected item are misaligned in dual list
  src/app/modules/common/dual-list/dual-list.component.scss
Labels: backport-23.10.2

#9459 NAS-126753 / 24.04 / Wrong seconds calculation in WebUI Sessions Settings Widget
  src/app/pages/system/advanced/access/access-card/access-card.component.spec.ts
  src/app/pages/system/advanced/access/access-card/access-card.component.ts
  src/app/pages/system/advanced/access/access-form/access-form.component.ts
Labels: backport-23.10.2

#9449 NAS-125762 / 23.10.2 / Installed apps sorting unsorts itself
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Labels: backport-24.04

#9472 NAS-126801 / 24.10 / Accessing the email set up a second time requires a screen refresh when accessed and also the UI reverts to the General page
  src/app/pages/system/general-settings/general-settings.component.ts
Labels: backport-24.04

#9466 NAS-125604 / 24.04 / Poor error handling in apps
  scripts/ui/ui.ts
  src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.html
  src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
  src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.ts
  src/app/pages/apps/components/catalogs/catalogs.component.ts
  src/app/pages/apps/components/catalogs/manage-catalog-summary/manage-catalog-summary-dialog.component.scss
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
  src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.ts
  src/app/pages/apps/components/pod-select-logs/pod-select-logs-dialog.component.ts
  src/app/pages/apps/components/select-pool-dialog/select-pool-dialog.component.ts
  src/app/pages/apps/services/applications.service.ts
  src/app/pages/apps/store/apps-filter-store.service.ts
  src/app/pages/apps/store/apps-store.service.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
  src/app/pages/apps/store/kubernetes-store.service.spec.ts
  src/app/pages/apps/store/kubernetes-store.service.ts
  src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.html
  src/app/services/error-handler.service.ts
Labels: backport-24.04-RC.1

#9491 NAS-126933 / 24.10 / Apps sorting breaks after viewing details and closing panel (smaller devices) & selection via Enter is not working
  src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Labels: backport-24.04-RC.1

#9494 NAS-125699 / 24.10 / Remove system birthday
  src/app/interfaces/system-config.interface.ts
  src/app/interfaces/system-info.interface.ts
Labels: backport-24.04-RC.1

#9486 NAS-126920 / 24.10 / Roles for KMIP
  src/app/pages/credentials/kmip/kmip.component.html
  src/app/pages/credentials/kmip/kmip.component.spec.ts
  src/app/pages/credentials/kmip/kmip.component.ts
Labels: backport-24.04-RC.1

#9468 NAS-126815 / 24.10 / Fix invalid group values in ix-chips and user form
  src/app/modules/ix-forms/components/ix-chips/ix-chips.component.spec.ts
  src/app/modules/ix-forms/components/ix-chips/ix-chips.component.ts
  src/app/pages/account/groups/group-form/group-form.component.html
  src/app/pages/account/users/user-form/user-form.component.html
Labels: backport-24.04-RC.1

#9473 NAS-125605 / 24.10 / Do not reload system.info every 30 seconds
  src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
  src/app/store/system-info/system-info.effects.ts
Labels: backport-24.04-RC.1

#9495 NAS-126919 / 24.10 / On Dragonfish BETA.1 the licence agreement appears multiple times.
  src/app/store/eula/eula.effects.ts
Labels: backport-24.04-RC.1

#9492 NAS-126906 / 24.10 / Focus is lost on the opened Slide In & non trapped
  src/app/modules/common/dual-list/dual-list.component.scss
  src/app/modules/common/ordered-list/ordered-list.component.scss
  src/app/modules/common/search-input/search-input.component.scss
  src/app/modules/entity/entity-table/entity-table.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.html
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.ts
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header2/ix-modal-header2.component.html
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header2/ix-modal-header2.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.html
  src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.html
  src/app/modules/ix-forms/ix-forms.module.ts
  src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.scss
  src/app/modules/layout/components/admin-layout/admin-layout.component.html
  src/app/modules/layout/components/admin-layout/admin-layout.component.scss
  src/app/modules/layout/components/navigation/navigation.component.scss
  src/app/modules/layout/components/topbar/ix-logo/ix-logo.component.scss
  src/app/modules/layout/components/topbar/topbar.component.scss
  src/app/modules/search-input/components/advanced-search/advanced-search.component.scss
  src/app/modules/search-input/components/basic-search/basic-search.component.scss
  src/app/pages/dashboard/components/widget-storage/widget-storage.component.scss
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.scss
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.scss
  src/app/services/ix-chained-slide-in.service.ts
  src/assets/styles/components/_mat-card.scss
  src/assets/styles/other/_fn-styles.scss
  src/assets/styles/other/_material-reduction.scss
  src/assets/styles/other/_tn-styles.scss
Labels: backport-24.04-RC.1

#9509 NAS-126826 / 24.10 / On the latest Dragonfish nightly build Pool Wizard all mat-option data-test are missing the option text.
  src/app/modules/test-id/test-override/test-override.directive.ts
  src/app/modules/test-id/test/test.directive.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.spec.ts
Labels: backport-24.04-RC.1

#9522 NAS-126851 / 24.10 / QA responsive layout for dragonfish features
  src/app/modules/common/dialog/confirm-dialog/confirm-dialog.component.scss
  src/app/modules/common/dialog/info-dialog/info-dialog.component.scss
  src/app/modules/common/dialog/session-expiring-dialog/session-expiring-dialog.component.scss
  src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.scss
  src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.scss
  src/app/modules/ix-table2/components/ix-table-head/ix-table-head.component.scss
  src/app/modules/ix-table2/components/ix-table-pager/ix-table-pager.component.scss
  src/app/modules/ix-tables/components/ix-table/ix-table.component.scss
  src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.ts
  src/app/modules/layout/components/admin-layout/admin-layout.component.scss
  src/app/modules/layout/components/topbar/topbar.component.scss
  src/app/modules/search-input/components/advanced-search/advanced-search.component.ts
  src/app/modules/search-input/services/advanced-search-autocomplete.service.ts
  src/app/modules/search-input/services/query-parser/query-parsing-result.interface.ts
  src/app/modules/search-input/services/query-to-api/query-to-api.service.ts
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.scss
  src/app/pages/audit/components/audit/audit.component.html
  src/app/pages/audit/components/audit/audit.component.scss
  src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.scss
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.scss
  src/app/pages/datasets/modules/encryption/components/export-all-keys-dialog/export-all-keys-dialog.component.scss
  src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.scss
  src/app/pages/datasets/modules/encryption/components/lock-dataset-dialog/lock-dataset-dialog.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-lock-list/smb-lock-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-lock-list/smb-lock-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.ts
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.ts
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.html
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.scss
  src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.ts
  src/app/pages/storage/modules/devices/components/hardware-disk-encryption/manage-disk-sed-dialog/manage-disk-sed-dialog.component.scss
  src/app/pages/vm/devices/device-list/device-details/device-details.component.scss
  src/assets/i18n/fr.json
  src/assets/styles/mixins/layout.scss
  src/assets/styles/other/_material-reduction.scss
  yarn.lock
Labels: backport-24.04-RC.1

#9541 NAS-123855 / 24.10 / Sublight (H-series) Enclosure Support - UI
  src/app/core/testing/utils/enclosure-templates/mock-m60.ts
  src/app/pages/system/view-enclosure/classes/hardware/h10.ts
  src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
  src/app/services/product-image.service.ts
  src/assets/images/hardware/h10/h10_960w.png
  src/assets/images/hardware/h10/h10_960w_drivetray.png
  src/assets/images/hardware/h10/h10_960w_drivetray_bg.png
  src/assets/images/hardware/h10/h10_960w_drivetray_handle.png
  src/assets/images/servers/H10.png
Labels: backport-24.04-RC.1

#9547 NAS-127050 / 24.10 / Audit header on load time is partially invisible
  src/app/pages/audit/components/audit/audit.component.scss
Labels: backport-24.04-RC.1

#9555 NAS-127037 / 24.10 / Add maxlength validation for feedback and tickets
  src/app/modules/feedback/components/file-review/file-review.component.ts
  src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.ts
  src/app/modules/feedback/components/file-ticket/file-ticket.component.ts
Labels: backport-24.04-RC.1

#9560 NAS-127086 / 24.10 / Missing permission checks in Apps
  src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.ts
  src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.html
  src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.spec.ts
  src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.ts
  src/app/pages/apps/components/catalogs/catalog-edit-form/catalog-edit-form.component.html
  src/app/pages/apps/components/catalogs/catalog-edit-form/catalog-edit-form.component.spec.ts
  src/app/pages/apps/components/catalogs/catalog-edit-form/catalog-edit-form.component.ts
  src/app/pages/apps/components/catalogs/catalogs.component.html
  src/app/pages/apps/components/catalogs/catalogs.component.ts
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.html
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
  src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
  src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.html
  src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
  src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.html
  src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.spec.ts
  src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.ts
  src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.html
  src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
  src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html
  src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
  src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.html
  src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.html
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
  src/app/pages/apps/components/installed-apps/app-upgrade-dialog/app-upgrade-dialog.component.html
  src/app/pages/apps/components/installed-apps/app-upgrade-dialog/app-upgrade-dialog.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
  src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.html
  src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.spec.ts
  src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.ts
Labels: backport-24.04-RC.1

#9559 NAS-126987 / 24.10 / The Services Toggles are not working correctly, HA is Disabled, and the WebUI disconnects
  src/app/pages/services/services.component.ts
Labels: backport-24.04-RC.1
