Repository truenas/webui, pull requests merged in 2024-09, with the labels that each got.

#10570 NAS-130758 / 25.04 / Update disk list after wipe
  src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.spec.ts
  src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
  src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts
Labels: backport-24.10-RC.1

#10602 NAS-130874 / 25.04 / snapshot batch delete button is deleting ALL snapshots, not just selected
  src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
  src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.ts
  src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
  src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
Labels: backport-24.10-RC.1

#10624 NAS-131015 / 25.04 / Sanitize audit logs
  src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
  src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.ts
Labels: backport-24.10-RC.1, backport-24.04.2.1

#10625 NAS-130994 / 25.04 / Fix interface name in the widget
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts
Labels: backport-24.10-RC.1

#10595 NAS-130859 / 25.04 / UI provides incorrect information about dataset ACL mode and does not provide a mechanism to fix it when incorrect
  src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.spec.ts
  src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
  src/assets/styles/mixins/cards.scss
Labels: backport-24.10-RC.1

#10626 NAS-130879 / 25.04 / Fix netdata URL
  src/app/pages/reports-dashboard/components/reports-global-controls/netdata-dialog/netdata-dialog.component.html
Labels: backport-24.10-RC.1

#10569 NAS-130767 / 25.04 / Optimize app.query calls
  src/app/enums/docker-config.interface.ts
  src/app/interfaces/api/api-call-and-subscribe-directory.interface.ts
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/interfaces/api/api-event-directory.interface.ts
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
  src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.html
  src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.ts
  src/app/pages/apps/services/applications.service.ts
  src/app/pages/apps/store/docker.store.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10-RC.1

#10640 NAS-130980 / 25.04 / ElectricEel HA Dashboard is missing the Standby System Information card.
  src/app/pages/dashboard/components/dashboard/dashboard.component.spec.ts
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/app/pages/dashboard/services/dashboard.store.spec.ts
  src/app/pages/dashboard/services/dashboard.store.ts
  src/app/pages/dashboard/services/get-default-widgets.spec.ts
  src/app/pages/dashboard/services/get-default-widgets.ts
Labels: backport-24.10-RC.1

#10649 NAS-131016 / 25.04 / Uptime on Dashboard runs too fast
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
  src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.html
  src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts
Labels: backport-24.10-RC.1

#10652 NAS-131098 / 25.04 / Custom App Issue | error modal & close
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10-RC.1

#10657 NAS-131112 / 25.04 / Install App after setting pool up - warning confirm dialo…
  src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.html
  src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.ts
Labels: backport-24.10-RC.1

#10668 NAS-131149 / 25.04 / Remove `new` indicators
  src/app/pages/dashboard/dashboard.routing.ts
  src/app/pages/data-protection/data-protection.routing.ts
  src/app/pages/system/enclosure/enclosure.routing.ts
  src/assets/i18n/fr.json
Labels: backport-24.10.0

#10673 NAS-130884 / 25.04 / Apps | App metadata like `Run As Context` and `Capabilities` should be visible before installation
  src/app/pages/apps/apps.module.ts
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
  src/app/pages/apps/components/app-detail-view/app-detail-view.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.html
  src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.scss
  src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.spec.ts
  src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.ts
  src/assets/styles/other/_fn-styles.scss
Labels: blocked, backport-24.10.0

#10689 NAS-131153 / 25.04 / H-Series Enclosure Image missing from Dashboard
  src/assets/i18n/it.json
  src/assets/images/servers/H20.png
Labels: backport-24.10.0

#10688 NAS-131134 / 25.04 / Multiple Cloud backup has started messages
  src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.ts
Labels: backport-24.10.0

#10685 NAS-131101 / 25.04 / Help button in the Active Directory menu is not clickable if the translation is too long.
  src/app/modules/forms/ix-forms/components/ix-checkbox/ix-checkbox.component.scss
Labels: backport-24.10.0

#10684 NAS-131123 / 25.04 / Buttons overlap on upgrade page / mobile
  src/app/pages/system/update/components/update-actions-card/update-actions-card.component.scss
Labels: backport-24.10.0

#10690 NAS-131214 / 25.04 / Do not show keys from `update.get_trains`
  src/app/pages/signin/store/signin.store.ts
  src/app/pages/system/update/components/train-card/train-card.component.ts
Labels: backport-24.10-RC.1, backport-24.10.0

#10709 NAS-131276 / 25.04 / Wrap long text on the login banner
  src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.scss
  src/app/pages/signin/signin.component.ts
Labels: backport-24.10.0

#10704 NAS-131231 / 25.04 / if you enter an invalid AUTH key, tailscale goes into a tight restart loop
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Labels: backport-24.10.0

#10713 NAS-131286 / 25.04 / No application installed blink before showing installed apps
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10.0

#10711 NAS-131246 / 25.04 / Apps Bulk Actions are not showing correct options for selected app(s)
  src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Labels: backport-24.10.0

#10717 NAS-131290 / 25.04 / Add `debounceTime` to `disk.query` subscription update in `enclosure.store.ts`
  src/app/pages/system/enclosure/services/enclosure.store.spec.ts
  src/app/pages/system/enclosure/services/enclosure.store.ts
Labels: backport-24.10.0

#10703 NAS-131222 / 25.04 / FT: Local Groups create new GID errors with red text: Input should be a valid integer
  src/app/pages/account/groups/group-form/group-form.component.html
Labels: backport-24.10.0

#10720 NAS-131271 / 25.04 / Check for updates daily-button not working
  src/app/pages/system/update/components/train-card/train-card.component.spec.ts
  src/app/pages/system/update/components/train-card/train-card.component.ts
  src/app/pages/system/update/services/train.service.ts
Labels: backport-24.10.0

#10727 NAS-131323 / 25.04 / ddns-updater does not show the IP version value if set to “IPv4 and IPv6” when editing the configuration of the docker
  src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.scss
  src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.ts
Labels: backport-24.10.0

#10718 NAS-130993 / 25.04 / Make use of a 1/4 size widget in defaults, if possible.
  src/app/pages/dashboard/services/get-default-widgets.spec.ts
  src/app/pages/dashboard/services/get-default-widgets.ts
Labels: backport-24.10.0

#10738 NAS-131372 / 25.04 / Cannot edit `link` user
  src/app/pages/account/groups/group-form/group-form.component.ts
  src/app/pages/account/users/user-form/user-form.component.ts
Labels: backport-24.10.0

#10739 NAS-131343 / 25.04 / UI is not showing new and updated apps properly
  src/app/pages/apps/store/apps-filter-store.service.ts
Labels: backport-24.10.0

#10745 NAS-131100 / 25.04 / Fix installed apps is empty on app install
  src/app/pages/apps/services/applications.service.ts
  src/app/pages/apps/store/installed-apps-store.service.ts
Labels: backport-24.10.0

#10740 NAS-131272 / 25.04 / App name issue in UI
  src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
  src/app/modules/ix-table/components/ix-table/ix-table.component.scss
  src/app/modules/layout/topbar/user-menu/user-menu.component.scss
  src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
  src/app/pages/dashboard/components/dashboard/dashboard.component.scss
  src/assets/styles/mixins/text.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.10.0

#10750 NAS-131295 / 25.04 / System Support page is reporting incorrect Model information
  src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
  src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
Labels: backport-24.10.0

#10751 NAS-131307 / 25.04 / Text does not fit in network widget
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss
  src/assets/i18n/fr.json
Labels: backport-24.10.0

#10762 NAS-131378 / 25.04 / Fangtooth iSCSI service data-test tag of the Running toggle is inconsistent with the other iSCSI toggle.
  src/app/modules/ix-table/utils.ts
  src/app/pages/services/components/service-state-column/service-state-column.component.html
  src/app/pages/services/components/service-state-column/service-state-column.component.ts
Labels: backport-24.10.0

#10764 NAS-131421 / 25.04 / Improve webui professionalism
  src/app/pages/system/enclosure/components/jbof-list/jbof-list.component.html
Labels: backport-24.10.0

#10771 NAS-131443 / 25.04 / App Info Card -> App Version Overlap
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
Labels: backport-24.10.0
