Repository truenas/webui, pull requests merged in 2024-08, with the labels that each got.

#10390 NAS-128526 / 24.10 / Fix network axis labels
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
Labels: backport-24.04

#10397 NAS-130412 / 24.10 / Check smart supports before showing Run Manual Test button
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/interfaces/disk.interface.ts
  src/app/pages/storage/modules/devices/components/devices/devices.component.html
  src/app/pages/storage/modules/devices/components/devices/devices.component.ts
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
  src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.html
  src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.spec.ts
  src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.ts
  src/app/pages/storage/modules/devices/stores/devices-store.service.spec.ts
  src/app/pages/storage/modules/devices/stores/devices-store.service.ts
Labels: jira

#10408 NAS-129590 / 24.10 / Read Only Admin User App Edit screen is blank
  src/app/pages/apps/components/app-wizard/app-wizard.component.html
  src/app/pages/apps/components/app-wizard/app-wizard.component.scss
  src/app/pages/apps/components/app-wizard/app-wizard.component.ts
  src/app/pages/apps/components/catalog-settings/catalog-settings.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
Labels: skip jira status, blocked

#10440 NAS-130572 / 25.04 / Fix EULA condition to display
  src/app/store/eula/eula.effects.spec.ts
  src/app/store/eula/eula.effects.ts
Labels: backport-24.04-RC.1

#10441 NAS-130419 / 25.04 / Remove unused isRackMount function
  src/app/constants/server-series.constant.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.ts
Labels: skip jira status

#10443 NAS-130386 / 25.04 / Theme is too persistent
  src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts
  src/app/services/theme/theme.service.ts
Labels: backport-24.10-RC.1

#10456 NAS-130419 / 25.04 / Fix dashboard crashing when update.check failed
  src/app/pages/dashboard/services/widget-resources.service.ts
Labels: backport-24.10-BETA.1, backport-24.10-RC.1

#10464 NAS-130586 / 25.04 / Unround corners in main menu
  src/assets/styles/other/_tn-styles.scss
Labels: backport-24.10-RC.1

#10459 NAS-130049 / 25.04 / Consider removing blue plus overlay from feedback icon.
  src/app/modules/layout/components/topbar/topbar.component.html
Labels: backport-24.10-RC.1

#10446 NAS-130551 / 25.04 / Improve backward compatibility for pool widget
  src/app/pages/dashboard/services/dashboard.store.spec.ts
  src/app/pages/dashboard/services/dashboard.store.ts
  src/app/pages/dashboard/services/default-widgets.constant.ts
  src/app/pages/dashboard/services/demo-widgets.constant.ts
  src/app/pages/dashboard/services/widget-resources.service.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.definition.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.definition.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-scan-errors.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.definition.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.definition.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.definition.ts
Labels: skip jira status

#10466 NAS-130371 / 25.04 / Resizing a textarea doesn't work correctly
  src/app/modules/forms/ix-forms/components/ix-textarea/ix-textarea.component.scss
Labels: backport-24.10-RC.1

#10470 NAS-130604 / 25.04 / CPU model widget
  src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.spec.ts
  src/app/pages/dashboard/services/widget-resources.service.ts
  src/app/pages/dashboard/types/widget.interface.ts
  src/app/pages/dashboard/widgets/all-widgets.constant.ts
  src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.component.html
  src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.component.spec.ts
  src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.component.ts
  src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.definition.ts
Labels: backport-24.10-RC.1

#10465 NAS-130254 / 25.04 / Setting UK/GB date results in error in Reporting graphs
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
  src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/services/locale.service.spec.ts
  src/app/services/locale.service.ts
Labels: backport-24.10-RC.1

#10492 NAS-130666 / 25.04 / Custom cron schedule is too small to be rendered properly
  src/app/modules/ix-drop-grid/ix-drop-grid.directive.ts
  src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.scss
  src/assets/i18n/cs.json
  src/assets/i18n/fr.json
Labels: backport-24.10-RC.1

#10497 NAS-130672 / 25.04 / Rename Local Users/Groups to just Users/Groups
  src/app/services/navigation/navigation.service.ts
  src/assets/i18n/fr.json
Labels: backport-24.10-RC.1

#10469 NAS-130138 / 25.04 / Fix manual dataset unlocking
  src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.html
  src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
Labels: backport-24.10-RC.1

#10507 NAS-130607 / 25.04 / Mobile adjustments for dashboard widgets
  src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
  src/app/modules/ix-table/components/ix-table/ix-table.component.scss
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
  src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
  src/app/pages/dashboard/components/dashboard/dashboard.component.scss
  src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.scss
  src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.ts
  src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.scss
  src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.scss
  src/app/pages/dashboard/widgets/common/widget-datapoint/widget-datapoint.component.scss
  src/app/pages/dashboard/widgets/custom/arbitrary-text/widget-arbitrary-text-settings/widget-arbitrary-text-settings.component.scss
  src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
  src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.component.scss
  src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip-settings/widget-interface-ip-settings.component.scss
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.html
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-stats.scss
  src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.html
  src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.spec.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.scss
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.scss
  src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.html
  src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.scss
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.10-RC.1

#10527 NAS-130717 / 25.04 / Interface Widget | No chart is rendered (console.errors)
  src/app/modules/charts/components/view-chart-area/view-chart-area.component.ts
Labels: backport-24.10-RC.1

#10534 NAS-130716 / 25.04 / Margin issue in lists in apps
  src/app/modules/forms/ix-forms/components/ix-list/ix-list-item/ix-list-item.component.scss
Labels: backport-24.10-RC.1

#10536 NAS-130692 / 24.10-RC.1 / Some text is not translated in Pool creation
  src/app/modules/forms/ix-forms/components/ix-select/ix-select.component.html
Labels: backport-25.04

#10540 NAS-130729 / 24.10-RC.1 / Fixes usb ports on minis
  src/assets/images/new-hardware/minis/mini-3x-front.svg
  src/assets/images/new-hardware/minis/mini-3xl-plus-front.svg
Labels: backport-25.04

#10521 NAS-130521 / 25.04 / Fix disabled replication task form submission
  src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.html
  src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.spec.ts
  src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.ts
  src/assets/i18n/fr.json
Labels: backport-24.10-RC.1

#10510 NAS-130678 / 25.04 / Fix dRAID logic for number of children when creating a pool
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.ts
  src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
Labels: backport-24.10-RC.1

#10533 NAS-130719 / 25.04 / UI Global Search passes "undefined" url path to Docs Hub
  src/app/modules/global-search/components/global-search/global-search.component.ts
  src/app/modules/global-search/helpers/extract-version.spec.ts
  src/app/modules/global-search/helpers/extract-version.ts
  src/app/modules/global-search/services/global-search-sections.service.spec.ts
  src/app/modules/global-search/services/global-search-sections.service.ts
Labels: backport-24.10-RC.1

#10560 NAS-130711 / 25.04 / Fix the backup banner position
  src/app/pages/dashboard/widgets/backup/widget-backup/widget-backup.component.scss
Labels: backport-24.10-RC.1

#10561 NAS-130805 / 25.04 / Text overlap is not working in some places
  src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
  src/app/modules/ix-table/components/ix-table/ix-table.component.scss
  src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
  src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
  src/app/pages/dashboard/components/dashboard/dashboard.component.scss
  src/assets/i18n/fr.json
  src/assets/styles/other/_material-reduction.scss
Labels: backport-24.10-RC.1

#10572 NAS-130839 / 25.04 / Code cleanup id="lol"
  src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
Labels: backport-24.10-RC.1

#10573 NAS-130838 / 25.04 / API Keys deletion is not working
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/pages/api-keys/components/api-key-list/api-key-list.component.spec.ts
  src/app/pages/api-keys/components/api-key-list/api-key-list.component.ts
Labels: backport-24.10-RC.1

#10571 NAS-130837 / 25.04 / Send Feedback modal - buttons spacing is missing
  src/app/modules/feedback/components/file-review/file-review.component.scss
  src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.scss
  src/app/modules/feedback/components/file-ticket/file-ticket.component.scss
Labels: backport-24.10-RC.1

#10537 NAS-130644 / 25.04 / Fix subfolder path for `cloud_backup.restore`
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
Labels: backport-24.10-RC.1
