Repository truenas/webui, pull requests merged in 2024-12, with the labels that each got.

#11122 NAS-132751 / 25.04 / Cloud Credentials: It is not possible to delete cloud credentials
  src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.ts
Labels: backport-24.10.2

#11121 NAS-132725 / 25.04 / UI - Do not allow user to delete themselves
  src/app/pages/credentials/users/user-details-row/user-details-row.component.html
  src/app/pages/credentials/users/user-details-row/user-details-row.component.spec.ts
  src/app/pages/credentials/users/user-details-row/user-details-row.component.ts
Labels: backport-24.10.2

#11133 NAS-132767 / 25.04 / Fix payload for cloud sync task
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.spec.ts
  src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
  src/assets/i18n/pl.json
Labels: backport-24.10.1, backport-24.10.2

#11156 NAS-132928 / 25.04 / rsync task: mode == MODULE, ssh_credentials == null
  src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.spec.ts
  src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
Labels: backport-24.10.2

#11190 NAS-133032 / 25.04 / Lock icon is misaligned on some resolutions in apps
  src/app/directives/has-access/missing-access-wrapper.component.scss
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
  src/assets/styles/other/_material-overrides.scss
Labels: backport-24.10.2

#11197 NAS-132967 / 25.04 / Trusted Store option not present on CSR creation but is on edit
  src/app/pages/credentials/certificates-dash/certificate-authority-add/steps/ca-identifier-and-type/ca-identifier-and-type.component.html
  src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.html
  src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.spec.ts
  src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.ts
  src/app/pages/credentials/certificates-dash/forms/certificate-add/steps/certificate-identifier-and-type/certificate-identifier-and-type.component.html
Labels: backport-24.10.2

#11194 NAS-131851 / 25.04 / Custom Apps: Empty info cards (App Metadata) are visible
  src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
  src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.spec.ts
Labels: backport-24.10.2

#11196 NAS-132965 / 25.04 / Shell authenticator option for ACME DNS produces invalid fields
  src/app/interfaces/schema.interface.ts
  src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.ts
Labels: backport-24.10.2

#11209 NAS-131994 / 25.04 / Storage: Number of available disks doesn't update after a disconnect/destroy data until screen refresh
  src/app/pages/storage/components/unused-resources/unused-resources.component.spec.ts
  src/app/pages/storage/components/unused-resources/unused-resources.component.ts
Labels: backport-24.10.2

#11200 NAS-129926 / 25.04 / `enclosure.label.set`
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/pages/system/enclosure/components/set-enclosure-label-dialog/set-enclosure-label-dialog.component.spec.ts
  src/app/pages/system/enclosure/components/set-enclosure-label-dialog/set-enclosure-label-dialog.component.ts
Labels: skip jira status

#11231 NAS-133237 / 25.04 / Add search elements for API keys
  src/app/modules/layout/topbar/user-menu/user-menu.component.html
  src/app/modules/layout/topbar/user-menu/user-menu.elements.ts
  src/app/pages/credentials/users/user-api-keys/user-api-keys.elements.ts
  src/assets/ui-searchable-elements.json
Labels: backport-24.10.2

#11224 NAS-133139 / 25.04 / Replication has started spam
  src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
Labels: backport-24.10.2

#11225 NAS-133049: UI does not provide mechanism to remove an invalid NFS bind IP address
  src/app/interfaces/bind-ip.interface.ts
  src/app/interfaces/smb-config.interface.ts
  src/app/pages/services/components/service-nfs/service-nfs.component.ts
  src/app/pages/services/components/service-smb/service-smb.component.html
  src/app/pages/services/components/service-smb/service-smb.component.spec.ts
  src/app/pages/services/components/service-smb/service-smb.component.ts
  src/assets/i18n/ko.json
Labels: backport-24.10.2

#11230 NAS-133127 / 25.04 / Incorrect redirect for already installed app
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.scss
  src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.ts
  src/app/pages/apps/components/available-apps/app-card/app-card.component.html
  src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
  src/app/pages/apps/components/available-apps/app-card/app-card.component.ts
  src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.html
  src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.scss
  src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.spec.ts
  src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.ts
Labels: backport-24.10.2
