Repository truenas/webui, pull requests merged in 2025-09, with the labels that each got.

#12452 NAS-136321 / 26.04 / show TNC header icon by default
  src/app/interfaces/truenas-connect-config.interface.ts
  src/app/modules/layout/topbar/topbar.component.spec.ts
  src/app/modules/layout/topbar/topbar.component.ts
  src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.spec.ts
  src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.ts
  src/app/modules/truenas-connect/services/truenas-connect.service.spec.ts
  src/app/modules/truenas-connect/services/truenas-connect.service.ts
Labels: backport-25.10-RC.1

#12491 NAS-137360 / 26.04 / auto-generated SSH Keypair should be displayed on new SSH Connection creation
  src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.spec.ts
  src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.ts
  src/app/pages/credentials/backup-credentials/ssh-keypair-card/ssh-keypair-card.component.spec.ts
  src/app/pages/credentials/backup-credentials/ssh-keypair-card/ssh-keypair-card.component.ts
  src/app/services/keychain-credential.service.spec.ts
  src/app/services/keychain-credential.service.ts
Labels: backport-25.10-RC.1

#12488 NAS-137395 / 26.04 / Do not require Port in NVMe-oF and show 4420 as placeholder
  src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.html
  src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.spec.ts
  src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.ts
Labels: backport-25.10-RC.1

#12502 NAS-137417 / 26.04 / Fix parent slide-in not reappearing after closing child slide-in
  src/app/modules/slide-ins/slide-in.spec.ts
  src/app/modules/slide-ins/slide-in.ts
Labels: jira-high, backport-25.10-RC.1

#12487 NAS-137315 / 26.04 / Refactor syslog configuration to support multiple servers
  src/app/interfaces/advanced-config.interface.ts
  src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.html
  src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.spec.ts
  src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.ts
  src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.html
  src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.scss
  src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.spec.ts
  src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.ts
  src/assets/ui-searchable-elements.json
Labels: backport-25.10-RC.1

#12505 NAS-137426 / 26.04 / Avoid calling same API calls multiple times
  src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.spec.ts
  src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
  src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
  src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.spec.ts
  src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
  src/app/services/gpu/critical-gpu-prevention.service.spec.ts
  src/app/services/gpu/critical-gpu-prevention.service.ts
  src/app/services/gpu/gpu-service.spec.ts
  src/app/services/gpu/gpu.service.ts
Labels: jira

#12511 NAS-137432 / 26.04 / NVMe-of-service is locked for sharing admin (UI)
  src/app/services/services.service.spec.ts
  src/app/services/services.service.ts
Labels: backport-25.10-RC.1

#12515 NAS-137272 / 26.04 / Horizontal Scrolling and Key table placement Improvement request
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.spec.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.scss
  src/app/pages/reports-dashboard/components/report/report.component.spec.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
Labels: backport-25.10-RC.1

#12526 NAS-137428 / 26.04 / Applications Network reporting bytes vs bits
  src/app/modules/pipes/network-speed/network-speed.pipe.spec.ts
  src/app/modules/pipes/network-speed/network-speed.pipe.ts
  src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
  src/app/pages/dashboard/widgets/apps/common/app-network-info/app-network-info.component.spec.ts
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.spec.ts
Labels: backport-25.10-RC.1

#12534 NAS-137504 / 26.04 / Remove system.experimental
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/modules/layout/topbar/topbar.component.html
  src/app/modules/layout/topbar/topbar.component.spec.ts
  src/app/modules/layout/topbar/topbar.component.ts
Labels: backport-25.10-RC.1

#12567 NAS-137585 / 26.04 / Enclosure Mock is not working
  src/app/modules/websocket-debug-panel/websocket-debug-panel.component.ts
Labels: backport-25.10-RC.1, backport-25.10.0

#12572 NAS-137623 / 26.04 / Use tn-common-typescript to share scripts/config with other projects
  eslint.config.mjs
  eslint/eslint-html.mjs
  eslint/eslint-spec.mjs
  eslint/eslint-ts-rules-extra.mjs
  eslint/eslint-ts-rules-fix-later.mjs
  eslint/eslint-ts-rules-overrides.mjs
  package.json
  scripts/lint.ts
  scripts/test_changed.js
  yarn.lock
Labels: jira

#12566 NAS-137604 / 26.04 / Enclosure preview & main view does not fit properly
  src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-page.component.scss
  src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-selector/enclosure-selector.component.scss
Labels: backport-25.10-RC.1, backport-25.10.0

#12580 NAS-137611 / 26.04 / User Home Default Permissions checkbox remains checked after changing permissions
  src/app/modules/test-id/test.directive.ts
  src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.html
  src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.spec.ts
  src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.ts
Labels: backport-25.10-RC.1, backport-25.10.0

#12579 NAS-137622 / 26.04 / The Secondary Password Confirmation Field is missing in the New Users Edit/Creation UI
  src/app/helptext/account/user-form.ts
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.html
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.spec.ts
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts
Labels: backport-25.10-RC.1, backport-25.10.0

#12584 NAS-137646 / 26.04 / User UI: Enabling SSH access does not save although the text says that the user was updated
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.html
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.scss
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.spec.ts
  src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts
Labels: backport-25.10-RC.1, backport-25.10.0

#12585 NAS-137661 / 26.04 / User UI: Back button is not working
  src/app/modules/master-detail-view/master-detail-view.component.html
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
Labels: backport-25.10-RC.1, backport-25.10.0

#12594 NAS-137692 / 26.04 / Make 2FA setup optional and add unset functionality
  src/app/helptext/system/2fa.ts
  src/app/modules/auth/auth.service.ts
  src/app/modules/auth/blocking-action-guard.service.spec.ts
  src/app/modules/auth/blocking-action-guard.service.ts
  src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.html
  src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.scss
  src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.spec.ts
  src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.ts
  src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.html
  src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.scss
  src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.ts
  src/app/pages/system/advanced/global-two-factor-auth/global-two-factor-form/global-two-factor-form.component.ts
  src/app/pages/two-factor-auth/two-factor.component.html
  src/app/pages/two-factor-auth/two-factor.component.scss
  src/app/pages/two-factor-auth/two-factor.component.spec.ts
  src/app/pages/two-factor-auth/two-factor.component.ts
Labels: backport-25.10-RC.1, backport-25.10.0

#12604 NAS-137656 / 26.04 / Calendar on audit page is not rendered correctly
  src/app/modules/forms/search-input/components/advanced-search/advanced-search.component.scss
Labels: backport-25.10-RC.1, backport-25.10.0

#12611 NAS-137778 / 26.04 / Update angular to 20.3.2
  package.json
  src/app/app.component.ts
  src/app/modules/master-detail-view/master-detail-view.component.ts
  src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.ts
  src/app/pages/data-protection/cloud-backup/all-cloud-backups/all-cloud-backups.component.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/pages/instances/components/all-instances/all-instances.component.ts
  src/app/pages/storage/components/dashboard-pool/storage-health-card/storage-health-card.component.html
  src/app/pages/system/network/network.component.ts
  yarn.lock
Labels: jira
