Repository truenas/webui, pull requests merged in 2025-10, with the labels that each got.

#12630 NAS-137843 / 26.04 / Isolate deprecated Angular CDK TreeControl usage
  src/app/modules/ix-tree/components/tree/tree.component.ts
  src/app/modules/ix-tree/flat-tree-datasource.ts
  src/app/modules/ix-tree/tree-control.factory.spec.ts
  src/app/modules/ix-tree/tree-control.factory.ts
  src/app/modules/ix-tree/tree-datasource.ts
  src/app/modules/ix-tree/tree-expansion.interface.ts
  src/app/modules/ix-tree/tree-flattener.ts
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-disks/manual-selection-disks.component.ts
  src/app/pages/storage/modules/vdevs/components/vdevs-list/vdevs-list.component.ts
  src/app/pages/storage/modules/vdevs/components/zfs-info-card/zfs-info-card.component.ts
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.html
  src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
Labels: jira-medium

#12625 NAS-137781 / 26.04 / Do not show update summary if there is a release notes
  src/app/pages/system/update/update.component.html
Labels: backport-25.10.0

#12633 NAS-137847 / 26.04 / Handle several deprecated usages
  src/app/interfaces/dash-config-item.interface.ts
  src/app/interfaces/schema.interface.ts
  src/app/modules/auth/auth.service.ts
  src/app/modules/buttons/copy-button/copy-button.component.ts
  src/app/modules/charts/gauge-chart/gauge-chart.component.ts
  src/app/modules/dialog/components/error-dialog/error-dialog.component.ts
  src/app/modules/theme/theme.service.ts
  src/app/modules/theme/utils/theme-utils.spec.ts
  src/app/modules/theme/utils/theme-utils.ts
  src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.spec.ts
  src/app/modules/websocket-debug-panel/services/mock-response.service.ts
  src/app/pages/dashboard/services/dashboard.store.ts
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.utils.ts
  src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-form/kerberos-keytabs-form.component.ts
  src/app/pages/reports-dashboard/components/exporters/reporting-exporters-form/reporting-exporters-form.component.ts
  src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
  src/app/store/preferences/preferences.reducer.ts
  tsconfig.strictNullChecks.json
Labels: jira

#12639 NAS-137881 / 26.04 / Add review-branch command to Claude CLI
  .claude/commands/review-branch.md
  .claude/review-prompt.md
  .github/workflows/claude.yml
Labels: jira

#12640 NAS-137884 / 26.04 / Use newer version of tn-common-typescript with sonarjs/deprecation turned on
  src/app/modules/buttons/copy-button/copy-button.component.ts
  src/app/modules/forms/ix-forms/services/form-error-handler.service.spec.ts
  src/app/modules/ix-tree/tree-control.factory.ts
  yarn.lock
Labels: jira

#12627 NAS-137665 / 26.04 / Credentials/ACME DNS-Auth: Validation messages appear as errors after attempting to save the form
  src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.html
  src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.scss
  src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.spec.ts
  src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.ts
  src/app/pages/credentials/certificates-dash/acmedns-form/cloudflare-auth.validator.spec.ts
  src/app/pages/credentials/certificates-dash/acmedns-form/cloudflare-auth.validator.ts
Labels: backport-25.10.0

#12647 NAS-137813 / 26.04 / fix: send `null` as speed limit when field empty
  src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.spec.ts
  src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts
Labels: backport-25.10.0

#12655 NAS-137861 / 26.04 / Fix editing a zvol
  src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
  src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
Labels: backport-25.10.0
