Repository truenas/webui, pull requests merged in 2025-02, with the labels that each got.

#11345 NAS-133494 / 25.04 / WIP: Enclosure Colors
  src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.scss
  src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.spec.ts
  src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.ts
  src/app/pages/system/enclosure/components/enclosure-side/not-supported-model/not-supported-model.component.html
  src/assets/images/new-hardware/es102/es102-top.svg
  src/assets/images/new-hardware/es102g2/es102g2-top.svg
  src/assets/images/new-hardware/es12/es12-front.svg
  src/assets/images/new-hardware/es24/es24-front.svg
  src/assets/images/new-hardware/es24f/es24f-front.svg
  src/assets/images/new-hardware/es24n/es24n-front.svg
  src/assets/images/new-hardware/es60/es60-top.svg
  src/assets/images/new-hardware/es60g2/es60g2-top.svg
  src/assets/images/new-hardware/es60g3/es60g3-top.svg
  src/assets/images/new-hardware/f-series/f-series-front.svg
  src/assets/images/new-hardware/h-series/h-series-front.svg
  src/assets/images/new-hardware/m-series/m-series-front.svg
  src/assets/images/new-hardware/m-series/m-series-rear.svg
  src/assets/images/new-hardware/minis/mini-3e-front.svg
  src/assets/images/new-hardware/minis/mini-3x-front.svg
  src/assets/images/new-hardware/minis/mini-3xl-plus-front.svg
  src/assets/images/new-hardware/minis/mini-r-front.svg
  src/assets/images/new-hardware/r10/r10-front.svg
  src/assets/images/new-hardware/r20/r20-front.svg
  src/assets/images/new-hardware/r20/r20-rear.svg
  src/assets/images/new-hardware/r20a/r20a-front.svg
  src/assets/images/new-hardware/r20a/r20a-rear.svg
  src/assets/images/new-hardware/r20b/r20b-front.svg
  src/assets/images/new-hardware/r20b/r20b-rear.svg
  src/assets/images/new-hardware/r30/r30-front.svg
  src/assets/images/new-hardware/r40/r40-front.svg
  src/assets/images/new-hardware/r50/r50-rear.svg
  src/assets/images/new-hardware/r50/r50-top.svg
  src/assets/images/new-hardware/r50b/r50b-rear.svg
  src/assets/images/new-hardware/r50b/r50b-top.svg
  src/assets/images/new-hardware/r50bm/r50bm-rear.svg
  src/assets/images/new-hardware/r50bm/r50bm-top.svg
  src/assets/images/new-hardware/x-series/x-series-front.svg
Labels: backport-25.04-RC.1

#11356 Pass location.hostname as host_ip to app.query
  src/app/pages/apps/services/applications.service.ts
Labels: backport-25.04-RC.1

#11458 NAS-133822 / 25.10 / Fix updateRowJob at cloud backups
  src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
Labels: backported, backport-25.04-RC.1

#11462 NAS-133861 / 25.10 / Cannot create VM with GPU selected
  src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
  src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts
Labels: backport-25.04-RC.1, backport-25.04-BETA.1

#11477 NAS-133970 / 25.10 / Add error handling for removal the extent association from the iSCSI Targets page
  src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.ts
Labels: backport-25.04-RC.1

#11404 NAS-133598 / 25.10 / Fix `saveUpdatedPreferences` effect
  src/app/store/preferences/preferences.effects.spec.ts
  src/app/store/preferences/preferences.effects.ts
Labels: backport-25.04-RC.1

#11489 NAS-133998 / 25.10 / Do not show root disk size field when importing a zvol
  src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.html
  src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
  src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts
Labels: backport-25.04-RC.1, backport-25.04-BETA.1

#11501 NAS-134043 / 25.10 / Clear token when STIG is enabled
  src/app/modules/layout/admin-layout/admin-layout.component.ts
  src/app/modules/layout/topbar/topbar.component.ts
  src/app/pages/credentials/groups/privilege/privilege-form/privilege-form.component.html
  src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.spec.ts
  src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
Labels: backport-25.04-RC.1

#11461 NAS-133853 / 25.10 / ix-blue theme wrong icon colors
  src/app/modules/layout/topbar/topbar.component.scss
  src/assets/styles/other/_material-overrides.scss
Labels: backport-25.04-RC.1

#11503 NAS-134050 / 25.10 / Restart dialog layout shifts because of validation message
  src/app/modules/layout/topbar/power-menu/power-menu.component.spec.ts
  src/app/modules/layout/topbar/power-menu/power-menu.component.ts
  src/app/modules/layout/topbar/reboot-or-shutdown-dialog/reboot-or-shutdown-dialog.component.html
Labels: backport-25.04-RC.1

#11505 NAS-134046 / 25.10 / Auth error in Export Key is not properly handled
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
  src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.spec.ts
  src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.ts
Labels: backport-25.04-RC.1

#11432 NAS-133818 / 25.04-BETA.1 / Update system version utils for new naming (by denysbutenko)
  src/app/enums/codename.enum.ts
  src/app/modules/layout/topbar/about-dialog/about-dialog.component.html
  src/app/modules/layout/topbar/about-dialog/about-dialog.component.spec.ts
  src/app/modules/layout/topbar/about-dialog/about-dialog.component.ts
  src/app/pages/dashboard/widgets/system/common/system-version.pipe.spec.ts
  src/app/pages/dashboard/widgets/system/common/system-version.pipe.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
  src/assets/icons/sprite-config.json
  src/assets/icons/sprite.svg
Labels: blocked

#11509 NAS-134022 / 25.10 / Long admin names do not fit on the screen
  src/app/modules/layout/topbar/user-menu/user-menu.component.scss
  src/assets/i18n/fr.json
Labels: backport-25.04-RC.1

#11520 NAS-134021 / 25.10 / Update in progress icon sticks around after job fails
  src/app/modules/layout/topbar/topbar.component.spec.ts
  src/app/modules/layout/topbar/topbar.component.ts
Labels: backport-25.04-RC.1

#11463 NAS-133774 / 25.10 / Reload node children on toggle in ix-explorer
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts
  src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
  src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
  src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
  src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
  src/app/services/filesystem.service.spec.ts
Labels: backport-25.04-RC.1, backport-25.04-BETA.1

#11536 NAS-133841 / 25.10 / Warning on new Virtualization feature
  src/app/pages/instances/components/all-instances/all-instances.component.spec.ts
  src/app/pages/instances/components/all-instances/all-instances.component.ts
Labels: backport-25.04-RC.1

#11537 NAS-134145 / 25.10 / Help widget has scrollbar & other widgets checkup
  src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.html
  src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
  src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
  src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
Labels: backport-25.04-RC.1

#11530 NAS-134061 / 25.10 / Apps - UI validates `uri` type more strictly than middleware
  src/app/modules/forms/ix-forms/validators/url-validation.service.spec.ts
  src/app/modules/forms/ix-forms/validators/url-validation.service.ts
Labels: backport-25.04-RC.1

#11558 NAS-134165 / 25.10 / New TrueNAS logo does not sit well in mobile
  src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.scss
Labels: backport-25.04-RC.1

#11542 NAS-133897 / 25.10 / Add disk reporting temps
  src/app/pages/reports-dashboard/reports-dashboard.component.ts
Labels: backport-25.04-RC.1

#11535 NAS-134036 / 25.10 / Add logs to Cloud Sync Task card
  src/app/modules/ix-table/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
  src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
Labels: backport-25.04-RC.1

#11550 NAS-131881 / 25.10 / GUI restrictions/issues present when accessing TrueNAS in Mobile display size
  src/app/modules/forms/search-input/components/advanced-search/advanced-search.component.scss
  src/app/modules/forms/search-input/components/basic-search/basic-search.component.scss
  src/app/modules/ix-table/components/ix-table-head/head-cells/ix-header-cell-text/ix-header-cell-text.component.scss
  src/app/modules/ix-table/components/ix-table-head/head-cells/ix-header-cell-text/ix-header-cell-text.component.ts
  src/app/modules/layout/admin-layout/admin-layout.component.scss
  src/app/pages/audit/components/audit-list/audit-list.component.ts
  src/app/pages/audit/components/audit-search/audit-search.component.scss
  src/app/pages/dashboard/components/dashboard/dashboard.component.scss
  src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.scss
  src/app/pages/reports-dashboard/reports-dashboard.component.scss
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/disk-info/disk-info.component.scss
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/enclosure-wrapper/enclosure-wrapper.component.scss
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.scss
  src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss
  src/app/pages/system-tasks/failover/failover.component.scss
  src/app/pages/system-tasks/restart/restart.component.scss
  src/app/pages/system-tasks/shutdown/shutdown.component.scss
  src/app/pages/system/general-settings/support/support-card/support-card.component.scss
  src/assets/styles/mixins/cards.scss
  src/assets/styles/other/_material-reduction.scss
Labels: backport-25.04-RC.1

#11553 NAS-132203 / 25.10 / Changing the owner group of a dataset with an AD group does not work if the AD cache is disabled.
  src/app/services/user.service.ts
Labels: backport-25.04-RC.1

#11579 NAS-134273 / 25.10 / Remove ix-logo
  src/app/modules/layout/admin-layout/admin-layout.component.scss
  src/app/modules/layout/copyright-line/copyright-line.component.html
  src/app/modules/layout/copyright-line/copyright-line.component.scss
  src/app/modules/layout/copyright-line/copyright-line.component.ts
  src/app/modules/layout/topbar/ix-logo/ix-logo.component.html
  src/app/modules/layout/topbar/ix-logo/ix-logo.component.scss
  src/app/modules/layout/topbar/ix-logo/ix-logo.component.spec.ts
  src/app/modules/layout/topbar/ix-logo/ix-logo.component.ts
  src/app/modules/layout/topbar/topbar.component.scss
  src/app/pages/signin/signin.component.html
  src/app/pages/signin/signin.component.scss
  src/assets/i18n/fr.json
  src/assets/styles/other/_tn-styles.scss
Labels: backport-25.04-RC.1

#11574 NAS-134027 / 25.10 / Minor fixes for iscsi pages
  src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-ports.component.ts
  src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
  src/app/pages/sharing/iscsi/iscsi.component.ts
  src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.ts
  src/app/services/iscsi.service.ts
Labels: backport-25.04-RC.1

#11589 NAS-134213 / 25.10 / Disable username in API keys on edit
  src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.spec.ts
  src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.ts
Labels: backport-25.04-RC.1

#11586 NAS-134210 / 25.10 / Incus Container Instance won't allow empty memory after c…
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
Labels: backport-25.04-RC.1

#11596 NAS-134221 / 25.10 / Adjust Copyright in the UI
  src/app/helpers/copyright-text.helper.spec.ts
  src/app/helpers/copyright-text.helper.ts
  src/app/modules/layout/admin-layout/admin-layout.component.html
  src/app/modules/layout/admin-layout/admin-layout.component.ts
  src/app/modules/layout/copyright-line/copyright-line.component.html
  src/app/modules/layout/copyright-line/copyright-line.component.spec.ts
  src/app/modules/layout/copyright-line/copyright-line.component.ts
  src/app/store/system-info/system-info.selectors.ts
Labels: backport-25.04-RC.1

#11612 NAS-134368 / 25.10 / Help widget has scrollbar again
  src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
Labels: backport-25.04.0

#11620 NAS-134289 / 25.10 / Missing space between sentences
  src/app/helptext/topbar.ts
  src/app/modules/layout/topbar/topbar.component.ts
Labels: backport-25.04.0

#11626 NAS-134337 / 25.10 / Dashboard Network Graph shrinks and disappears
  src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.scss
  src/app/pages/dashboard/widgets/network/common/network-chart/network-chart.component.scss
Labels: backport-25.04.0

#11635 NAS-134470 / 25.10 / Fix missing unit tests in master
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
Labels: jira

#11631 NAS-134405 / 25.10 / Incorrect name hyperlink in apps
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: backport-25.04.0

#11524 NAS-133904 / 25.10 / Editing the Network Widget saved the values to the other portion of the widget
  src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.ts
  src/app/pages/dashboard/widgets/custom/arbitrary-text/widget-arbitrary-text-settings/widget-arbitrary-text-settings.component.ts
  src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip-settings/widget-interface-ip-settings.component.ts
  src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.ts
  src/assets/i18n/ko.json
Labels: backport-25.04.0

#11627 NAS-134385 / 25.10 / Cannot retrieve response after adding Authorized access
  src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
  src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
  src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
  src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
  src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.ts
  src/app/services/iscsi.service.ts
Labels: backport-25.04.0
