Repository truenas/webui, pull requests merged in 2025-08, with the labels that each got.

#12350 NAS-136933 / 25.10 / Replace 9 year old angular2-uuid with already installed uuid package
  package.json
  src/app/modules/charts/view-chart-gauge/view-chart-gauge.component.ts
  src/app/modules/interface-status-icon/interface-status-icon.component.ts
  src/app/modules/slide-ins/slide-in.ts
  src/app/modules/websocket-debug-panel/services/websocket-debug.service.ts
  src/app/modules/websocket/api.service.spec.ts
  src/app/modules/websocket/api.service.ts
  src/app/modules/websocket/ping.service.ts
  src/app/modules/websocket/subscription-manager.service.spec.ts
  src/app/modules/websocket/subscription-manager.service.ts
  src/app/modules/websocket/websocket-handler.service.ts
  src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
  src/app/pages/reports-dashboard/components/report/report.component.spec.ts
  src/app/pages/reports-dashboard/components/report/report.component.ts
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/manual-disk-selection.component.spec.ts
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-selection.store.spec.ts
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-selection.store.ts
  src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/utils/vdevs-to-manual-selection-vdevs.utils.ts
  src/app/services/errors/sentry-configuration.service.ts
  yarn.lock
Labels: jira-medium

#12354 NAS-136950 / 25.10 / Lint fixes
  src/app/modules/charts/view-chart-gauge/view-chart-gauge.component.ts
  src/app/modules/slide-ins/slide-in.ts
  src/app/modules/websocket/api.service.ts
  src/app/modules/websocket/subscription-manager.service.ts
  src/app/pages/sharing/iscsi/target/all-targets/target-details/iscsi-groups-card/iscsi-groups-card.component.ts
Labels: jira-medium

#12355 NAS-136954 / 25.10 / Fix interface dashboard widgets
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.utils.ts
Labels: jira-medium

#12359 NAS-136799 / 26.04 / To block feedback/bugs on experimental builds, gray out button.
  src/app/interfaces/api/api-call-directory.interface.ts
  src/app/modules/layout/topbar/topbar.component.html
  src/app/modules/layout/topbar/topbar.component.scss
  src/app/modules/layout/topbar/topbar.component.spec.ts
  src/app/modules/layout/topbar/topbar.component.ts
Labels: do not merge

#12362 NAS-136988 / 26.04 / Fix and improve External Share for Goldeye
  src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.html
  src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
  src/app/pages/sharing/smb/smb-form/smb-form.component.ts
  src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Labels: backport-25.10-RC.1

#12371 NAS-137028 / 26.04 / Improve description for mock config item
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.spec.ts
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.ts
Labels: jira

#12382 NAS-136903 / 26.04 / Validation Inconsistency in Storage Disk Source Field of Container Form
  src/app/modules/forms/ix-forms/components/ix-explorer/explorer-create-dataset/explorer-create-dataset.component.spec.ts
  src/app/modules/forms/ix-forms/components/ix-explorer/explorer-create-dataset/explorer-create-dataset.component.ts
Labels: backport-25.10-RC.1

#12389 NAS-137086 / 26.04 / Update claude action version
  .github/workflows/claude.yml
Labels: jira

#12369 NAS-136964 / 26.04 / Directory Services summary for LDAP always shows BindDN
  src/app/helptext/directory-service/dashboard.ts
  src/app/pages/directory-service/directory-services.component.html
  src/app/pages/directory-service/directory-services.component.spec.ts
  src/app/pages/directory-service/directory-services.component.ts
  src/app/pages/directory-service/directory-services.elements.ts
  src/assets/ui-searchable-elements.json
Labels: backport-25.10-RC.1

#12397 NAS-137125 / 26.04 / Ignore dist/ for lint
  eslint.config.mjs
Labels: jira

#12395 NAS-136335 / 26.04 / Password managers intermittent recognition of user/pass fields in WebUI login
  src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.html
  src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.spec.ts
  src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.ts
  src/app/pages/signin/signin-form/signin-form.component.html
  src/app/pages/signin/signin-form/signin-form.component.spec.ts
  src/app/pages/signin/signin-form/signin-form.component.ts
Labels: backport-25.10-RC.1

#12400 NAS-137085 / 26.04 / NAS-137084: fix creating non-inherited encrypted zvols
  src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
  src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
Labels: backport-25.10-RC.1

#12410 NAS-137161 / 26.04 / Clean up build scripts and remove unused dependencies
  .github/workflows/main.yml
  Dockerfile
  debian/rules
  package.json
  scripts/setup_prod.js
  setup-production-env.js
  yarn.lock
Labels: jira-medium, backport-25.10-RC.1

#12415 NAS-137177 / 26.04 / self hosted tests for ux team
  .github/actions/prepare/action.yml
  .github/workflows/main.yml
  package.json
Labels: jira-medium

#12430 NAS-137233 / 26.04 / Custom App -> Notes is not rendering any input
  src/app/interfaces/dynamic-form-schema.interface.ts
  src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
  src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
  src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.component.ts
Labels: backport-25.10-RC.1

#12441 NAS-137241 / 26.04 / warn users about adding special/dedup VDEVs with no redundancy
  src/app/helptext/storage/volumes/pool-creation/pool-creation.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.spec.ts
  src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts
Labels: backport-25.10-RC.1

#12449 NAS-137263 / 26.04 / disable ANA for non-HA
  src/app/helptext/sharing/nvme-of/nvme-of.ts
  src/app/pages/sharing/nvme-of/nvme-of-configuration/nvme-of-configuration.component.spec.ts
  src/app/pages/sharing/nvme-of/nvme-of-configuration/nvme-of-configuration.component.ts
Labels: backport-25.10-RC.1

#12462 NAS-137230 / 26.04 / Fix misleading help text for Show Text Console without Password Prompt
  src/app/helptext/system/advanced.ts
Labels: backport-25.10-RC.1

#12463 NAS-137088 / 26.04 / Handle network activity disabled status in update page
  src/app/enums/api.enum.ts
  src/app/enums/system-update.enum.ts
  src/app/pages/system/update/update.component.html
  src/app/pages/system/update/update.component.spec.ts
  src/app/pages/system/update/update.component.ts
Labels: backport-25.10-RC.1

#12471 NAS-137215 / 26.04 / Clean up Containers screen areas that are specific to the disabled VMs area
  src/app/enums/virtualization.enum.ts
  src/app/pages/instances/components/all-instances/all-instances-header/all-instances-header.component.spec.ts
  src/app/pages/instances/components/all-instances/all-instances-header/all-instances-header.component.ts
  src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
  src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.html
  src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.spec.ts
  src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.ts
Labels: backport-25.10-RC.1

#12477 NAS-137348 / 26.04 / Add error response mocking support to WebSocket debug panel
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.html
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.spec.ts
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.ts
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.html
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.scss
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.spec.ts
  src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.ts
  src/app/modules/websocket-debug-panel/interfaces/mock-config.interface.ts
  src/app/modules/websocket-debug-panel/services/mock-response.service.spec.ts
  src/app/modules/websocket-debug-panel/services/mock-response.service.ts
  src/app/modules/websocket-debug-panel/store/websocket-debug.effects.spec.ts
  src/app/modules/websocket-debug-panel/store/websocket-debug.effects.ts
  src/app/modules/websocket-debug-panel/store/websocket-debug.reducer.spec.ts
  src/app/modules/websocket-debug-panel/store/websocket-debug.selectors.spec.ts
  src/app/services/enclosure-mock.service.integration.spec.ts
  src/app/services/enclosure-mock.service.spec.ts
  src/app/services/enclosure-mock.service.ts
Labels: jira

#12479 NAS-137349 / 26.04 / Fix scripts/lint.ts to support directory parameters and recursive file discovery
  scripts/lint.ts
Labels: jira
