Repository truenas/webui, pull requests merged in 2025-03, with the labels that each got.

#11651 NAS-134482 / 25.10 / The webui should tighten up pre-submission validation of incus instance names
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
  src/assets/i18n/it.json
Labels: backport-25.04.0

#11659 NAS-134459 / 25.10 / NTP host addition
  src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.html
  src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.spec.ts
Labels: backport-25.04.0

#11663 NAS-134556 / 25.10 / Fix bind_ip for smb service config
  src/app/interfaces/bind-ip.interface.ts
  src/app/interfaces/smb-config.interface.ts
  src/app/pages/services/components/service-smb/service-smb.component.html
  src/app/pages/services/components/service-smb/service-smb.component.spec.ts
  src/app/pages/services/components/service-smb/service-smb.component.ts
Labels: backport-25.04-RC.1, backport-25.04.0

#11667 NAS-133871 / 25.10 / Fix virt instance is not selected when it is created
  src/app/pages/instances/components/all-instances/instance-list/instance-list.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-list/instance-list.component.ts
  src/app/pages/instances/stores/virtualization-instances.store.ts
Labels: backport-25.04.0

#11669 NAS-134555 / 25.10 / Remove ability to set zvol as a container disk
  src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
  src/app/services/filesystem.service.ts
Labels: backport-25.04.0

#11660 NAS-134504 / 25.10 / Edit Instance Screen Shows Environment Variables for VMs
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.html
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.ts
Labels: backport-25.04.0

#11679 NAS-134553 / 25.10 / Hide proxies for VMs
  src/app/pages/instances/components/all-instances/instance-details/instance-details.component.html
  src/app/pages/instances/components/all-instances/instance-details/instance-details.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-details/instance-details.component.ts
  src/app/pages/instances/components/all-instances/instance-details/instance-idmap/instance-idmap.component.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
  src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
Labels: backport-25.04.0

#11670 NAS-134566 / 25.10 / Unexpected warning next to Security in Instances
  src/app/modules/forms/ix-forms/components/ix-form-glossary/ix-form-glossary.component.ts
Labels: backport-25.04.0

#11688 NAS-134611 / 25.10 / Share admin not able to run/start FTP service
  src/app/services/services.service.ts
Labels: backport-25.04.0

#11677 NAS-134428 / 25.10 / Only reload explorer node children if going through zvols
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts
Labels: backport-25.04-RC.1, backport-25.04.0

#11689 NAS-134610 / 25.10 / "Input should be a valid string" when reloading ACL editor
  src/app/modules/auth/auth-guard.service.spec.ts
  src/app/modules/auth/auth-guard.service.ts
  src/app/pages/signin/store/signin.store.spec.ts
  src/app/pages/signin/store/signin.store.ts
Labels: backport-25.04.0

#11692 NAS-134605 / 25.10 / TrueNAS hint does not look good when there is a serial number
  src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.scss
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.scss
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
  src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
Labels: backport-25.04.0

#11693 NAS-134631 / 25.10 / Fixes reselection when instance is already selected
  src/app/pages/instances/components/all-instances/instance-list/instance-list.component.ts
Labels: backport-25.04.0

#11727 NAS-134706 / 25.10 / Improve URI validation in Create Docker Registry screen
  src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.html
  src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.ts
Labels: backport-25.04.0

#11719 NAS-134684 / 25.10 / Unify design language of apps and instances
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-general-info.component.html
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-general-info.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-general-info.component.ts
  src/app/pages/instances/components/all-instances/instance-list/instance-list.component.html
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-row.component.html
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-row.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-row.component.ts
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-status-cell/instance-status-cell.component.html
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-status-cell/instance-status-cell.component.scss
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-status-cell/instance-status-cell.component.spec.ts
  src/app/pages/instances/components/all-instances/instance-list/instance-row/instance-status-cell/instance-status-cell.component.ts
Labels: backport-25.04.0

#11725 NAS-134729 / 25.10 / Change defaults for Export Password Secret Seed
  src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.spec.ts
  src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.ts
Labels: backport-25.04.0

#11742 NAS-134490 / 25.04.0 / Load apps catalog when pool is updated (by denysbutenko)
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
  src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
Labels: no-time-tracked

#11743 NAS-134842 / 25.10 / Explore TrueNAS Enterprise text vanishes
  src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.html
  src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss
Labels: backport-25.04.0

#11757 NAS-134873 / 25.10 / iSCSI Portal form can be submitted without required `IP Address` field
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.html
  src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
Labels: backport-25.04.0

#11756 NAS-134844 / 25.10 / Discover Search, with Category filter returns broken App icons
  src/app/constants/catalog.constants.ts
  src/app/pages/apps/components/app-card-logo/app-card-logo.component.html
  src/app/pages/apps/components/app-card-logo/app-card-logo.component.spec.ts
  src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts
Labels: backport-25.04.0

#11770 NAS-134910 / 25.10 / Fix tests
  src/app/pages/apps/components/app-card-logo/app-card-logo.component.spec.ts
Labels: backport-25.04.0

#11791 NAS-134995 / 25.10 / Sort Apps by title, not by an internal key string
  src/app/interfaces/apps-filters-values.interface.ts
  src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
  src/app/pages/apps/store/apps-filter-store.service.spec.ts
  src/app/pages/apps/store/apps-filter-store.service.ts
Labels: backport-25.04.1

#11796 NAS-135021 / 25.10 / Remove ix logo from Settings page
  src/app/pages/dashboard/widgets/system/common/product-image/product-image.component.html
  src/app/pages/dashboard/widgets/system/common/product-image/product-image.component.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
  src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.ts
  src/app/pages/system/general-settings/support/support-card/support-card.component.html
  src/app/pages/system/general-settings/support/support-card/support-card.component.scss
  src/app/pages/system/general-settings/support/support-card/support-card.component.ts
  src/assets/images/ix.svg
  src/assets/images/ix_logo_full.png
Labels: backport-25.04.1

#11805 NAS-134342 / 25.10 / Check for old code earlier
  src/app/pages/signin/store/signin.store.ts
  src/assets/i18n/ko.json
Labels: backport-25.04.0

#11812 NAS-135044 / 25.10 / Too many quotas are reported in Dataset Space Management card
  src/app/helpers/storage.helper.spec.ts
  src/app/helpers/storage.helper.ts
  src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
  src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.spec.ts
  src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
  src/app/pages/datasets/components/dataset-quotas/dataset-quotas-list/dataset-quotas-list.component.ts
Labels: backport-25.04.1
