Repository truenas/webui, pull requests merged in 2025-01, with the labels that each got.

#11304 NAS-133128 / 24.10.2 / Simplify CPU widget logic
  src/app/pages/dashboard/widgets/cpu/common/cpu-core-bar/cpu-core-bar.component.spec.ts
  src/app/pages/dashboard/widgets/cpu/common/cpu-core-bar/cpu-core-bar.component.ts
  src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts
Labels: backport-25.04

#11303 NAS-133299 / 24.10.2 / Extend window not showing up for spares
  src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
  src/app/pages/storage/modules/devices/components/zfs-info-card/raidz-extend-dialog/raidz-extend-dialog.component.ts
Labels: backport-25.04

#11332 NAS-132372 / 24.10.3 / Add `/dev/zvol` root for explorer
  package.json
  src/app/enums/explorer-type.enum.ts
  src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
  src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
  src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
  src/app/services/filesystem.service.spec.ts
  src/app/services/filesystem.service.ts
  yarn.lock
Labels: backported, backport-24.10.2

#11374 NAS-133582 / 24.10.2 / Fix force_remove_ix_volumes
  src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
Labels: backport-24.04.2.1

#11378 NAS-133634 / 24.10.2.1 / Fix paths when they are not absolute
  src/app/interfaces/cloud-backup.interface.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
Labels: backport-25.04, backport-24.10.2

#11388 NAS-133792 / 25.10 / NAS0-133792: Only allow local groups for groups in user form
  src/app/pages/credentials/users/user-form/user-form.component.ts
  src/app/services/user.service.ts
Labels: backport-25.04-RC.1, backport-24.10.2, backport-24.10.3

#11386 NAS-133740 / 25.10 / Permission checks
  src/app/pages/services/services.component.ts
  src/app/pages/sharing/iscsi/iscsi.component.html
  src/app/pages/sharing/iscsi/iscsi.component.ts
  src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.html
  src/assets/ui-searchable-elements.json
Labels: backport-25.04-RC.1

#11383 NAS-133634 / 25.04 / Fix paths when they are not absolute (by bvasilenko)
  src/app/interfaces/cloud-backup.interface.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
  src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
  src/assets/i18n/fr.json
Labels: backport-25.04-RC.1

#11428 NAS-133816 / 25.10 / YAML is not available during edit when app is created
  src/app/pages/apps/components/custom-app-form/custom-app-form.component.html
  src/app/pages/apps/components/custom-app-form/custom-app-form.component.spec.ts
  src/app/pages/apps/components/custom-app-form/custom-app-form.component.ts
Labels: backport-25.04-RC.1

#11421 NAS-133773 / 25.10 / Fix Dashboard issues
  src/app/pages/dashboard/components/dashboard/dashboard.component.ts
  src/assets/i18n/es-ar.json
Labels: backport-25.04-RC.1

#11437 NAS-133815 / 25.10 / Code editor gets marked dirty incorrectly
  src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.component.ts
  src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.spec.ts
Labels: backport-25.04-RC.1

#11436 NAS-133707 / 25.10 / App icons are not initially rendered when searching until screen redraw
  src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts
Labels: backport-25.04-RC.1
